### ISSUE TITLE
Add checkout options to release build

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1044]
Been getting errors during checkout along the lines of this on the arm machines:

```
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* # timeout=30
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:825)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1092)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1123)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1212)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:566)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:491)
	at hudson.model.Run.execute(Run.java:1737)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: The remote end hung up unexpectedly
```

Tried cloning on local machine and was ok.

Tried adding an extended timeout using 'Advanced checkout behaviours' to the armV6 only job

![additional behaviour](https://user-images.githubusercontent.com/9373002/33959241-dc065008-e014-11e7-951a-14803de52b89.jpg)

Next runs seemed to be ok.  Not 100% sure this was related but would like to add to the regular release job just in case.

**Comment by mhdawson** [comment]
@rvagg @joaocgreis @jbergstroem any concerns ?

**Comment by rvagg** [comment]
lgtm, no concerns at all except that if we're taking 30 minutes then we have serious problems!

**Comment by mhdawson** [comment]
Agreed, it was failing long before 10 mins which I thought was the default timeout, we have 30 for the git  clone option so just used the same value.

**Comment by mhdawson** [comment]
Added to main release job, closing.
