### ISSUE TITLE
Significant infrastructure failures 

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1105]
Seems like our infrastructure has significant issues right now. There were multiple builds that looked like those:

https://ci.nodejs.org/job/node-test-commit/15987/
https://ci.nodejs.org/job/node-test-commit/15989/

**Comment by joyeecheung** [comment]
```

/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:171
  throw generateError(state, message);
  ^
YAMLException: bad indentation of a mapping entry at line 3, column 12:
      - version: REPLACEME
               ^
    at generateError (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
    at composeNode (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at Object.extractAndParseYAML (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/doc/common.js:22:21)
    at parseYAML (/home/iojs/build/workspace/node-test-commit-linux-containered/nodes/ubuntu1604_sharedlibs_openssl102_x64/tools/doc/html.js:368:23)
Makefile:670: recipe for target 'out/doc/api/all.html' failed
make[2]: *** [out/doc/api/all.html] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:619: recipe for target 'doc-only' failed
make[1]: *** [doc-only] Error 2
```

The root cause looks like this

**Comment by addaleax** [comment]
I think those were fixed by https://github.com/nodejs/node/pull/18605?

**Comment by joyeecheung** [comment]
@addaleax Yeah, the builds in the OP looks older than that PR...so I think this is fixed now? Or are there any other major failures like this?

**Comment by BridgeAR** [comment]
Uh, true. Sorry for the noise.
