### ISSUE TITLE
Fedora 24 is downnnn

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1106]
Broken for 11 hours

https://ci.nodejs.org/computer/test-rackspace-fedora24-x64-1/builds

**Comment by Trott** [comment]
Most recent attempt to build looks like this:

```console
Started by upstream project "node-test-commit-linux" build number 16205
originally caused by:
 Started by upstream project "node-test-commit" build number 16039
 originally caused by:
  Started by upstream project "node-test-pull-request" build number 13017
  originally caused by:
   Started by user Myles Borins
[EnvInject] - Loading node environment variables.
Building remotely on test-rackspace-fedora24-x64-1 (v8test fedora24) in workspace /home/iojs/build/workspace/node-test-commit-linux/nodes/fedora24
FATAL: java.io.IOException: Remote call on Channel to /119.9.51.165 failed
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at hudson.remoting.Request.call(Request.java:147)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:252)
Caused: hudson.remoting.RemotingSystemException
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:265)
	at com.sun.proxy.$Proxy6.fetch3(Unknown Source)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.commons.beanutils.ConvertUtilsBean.registerPrimitives(ConvertUtilsBean.java:628)
	at org.apache.commons.beanutils.ConvertUtilsBean.deregister(ConvertUtilsBean.java:578)
	at org.apache.commons.beanutils.ConvertUtilsBean.<init>(ConvertUtilsBean.java:164)
	at org.kohsuke.stapler.Stapler.<clinit>(Stapler.java:1040)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to Channel to /119.9.51.165
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
		at com.sun.proxy.$Proxy84.addCredentials(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.addCredentials(RemoteGitImpl.java:200)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:816)
		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:786)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1154)
		at hudson.scm.SCM.checkout(SCM.java:495)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1724)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:421)
Caused: java.lang.ExceptionInInitializerError
	at hudson.util.Secret.<clinit>(Secret.java:309)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.getLong(Field.java:611)
	at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1707)
	at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
	at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1843)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1933)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2245)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2169)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2027)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at hudson.remoting.UserRequest.deserialize(UserRequest.java:216)
	at hudson.remoting.UserRequest.perform(UserRequest.java:130)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:85)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on Channel to /119.9.51.165 failed
	at hudson.remoting.Channel.call(Channel.java:916)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
Caused: hudson.remoting.RemotingSystemException
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:297)
	at com.sun.proxy.$Proxy84.addCredentials(Unknown Source)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.addCredentials(RemoteGitImpl.java:200)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:816)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:786)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1154)
	at hudson.scm.SCM.checkout(SCM.java:495)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Run condition [Always] enabling perform for step [[]]
Run condition [Always] enabling perform for step [[]]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: *.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/fedora24/builds/16205/tap-master-files/cctest.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/fedora24/builds/16205/tap-master-files/cctest.tap].
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/fedora24/builds/16205/tap-master-files/test.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/fedora24/builds/16205/tap-master-files/test.tap].
TAP Reports Processing: FINISH
Checking ^not ok
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by Trott** [comment]
@nodejs/build

**Comment by Trott** [comment]
Looks like  test-digitalocean-fedora24-x64-1 seems OK but test-rackspace-fedora24-x64-1 seems down hard. I'll take the Rackspace host offline. Hopefully @rvagg or someone else can take a look and fix. (Maybe it just needs a reboot?)

**Comment by maclover7** [comment]
Sent reboot command to `test-rackspace-fedora24-x64-1`, waiting for it to come back online

**Comment by maclover7** [comment]
Ran `systemctl status jenkins` and things _seem_ ok, going to add back to the pool. Asked over IRC if a new pipeline job could be created, I would like to have a "run a basic command on a machine to see if acting weird" job available where we can type in a machine identifier and run that. Would help in these cases, since we can't _really_ tell if the machine is working well again until something like `node-test-commit` runs on it.

**Comment by mhdawson** [comment]
Is this ok now ?

**Comment by maclover7** [comment]
Looks like recent builds have been able to run, going to close this.
