### ISSUE TITLE
Persistent Jenkins/Git-plugin errors

### ISSUE THREAD

**Issue by rvagg** [nodejs/build#1122]
These happen pretty regularly and Googling has not been helpful in finding a resolution. I think it's a bug in the Git plugin that hasn't been properly identified and there's either something particular about our configuration or it's simply the fact that we run so many and therefore the %x of failures seems large to us.

This is a _help wanted_ issue and also an acknowledgement that we know of the problem and if CI users see it and are frustrated then we're with you but don't have an answer!

I believe the key to this stack trace is:

```
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer
 	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
```

```
00:00:02.913 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 138.68.241.115/138.68.241.115:49110
00:00:02.913 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
00:00:02.914 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
00:00:02.914 		at hudson.remoting.Channel.call(Channel.java:908)
00:00:02.915 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
00:00:02.915 		at com.sun.proxy.$Proxy80.withRepository(Unknown Source)
00:00:02.916 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
00:00:02.916 		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
00:00:02.916 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
00:00:02.917 		at hudson.scm.SCM.checkout(SCM.java:495)
00:00:02.917 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
00:00:02.918 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
00:00:02.918 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:02.919 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
00:00:02.919 		at hudson.model.Run.execute(Run.java:1724)
00:00:02.919 		at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
00:00:02.920 		at hudson.model.ResourceController.execute(ResourceController.java:97)
00:00:02.920 		at hudson.model.Executor.run(Executor.java:421)
00:00:02.921 java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer
00:00:02.921 	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
00:00:02.922 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
00:00:02.923 	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source)
00:00:02.923 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:02.924 	at java.lang.reflect.Method.invoke(Method.java:498)
00:00:02.924 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:922)
00:00:02.925 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:896)
00:00:02.926 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:853)
00:00:02.926 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
00:00:02.927 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
00:00:02.927 	at hudson.remoting.Request$2.run(Request.java:358)
00:00:02.928 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
00:00:02.928 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:00:02.929 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:00:02.929 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:00:02.930 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
00:00:02.930 	at java.lang.Thread.run(Thread.java:748)
00:00:02.931 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 138.68.241.115/138.68.241.115:49110 failed
00:00:02.932 	at hudson.remoting.Channel.call(Channel.java:916)
00:00:02.932 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:281)
00:00:02.933 	at com.sun.proxy.$Proxy80.withRepository(Unknown Source)
00:00:02.933 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
00:00:02.934 	at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
00:00:02.934 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
00:00:02.935 	at hudson.scm.SCM.checkout(SCM.java:495)
00:00:02.935 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
00:00:02.936 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
00:00:02.936 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
00:00:02.937 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
00:00:02.938 	at hudson.model.Run.execute(Run.java:1724)
00:00:02.938 	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
00:00:02.938 	at hudson.model.ResourceController.execute(ResourceController.java:97)
00:00:02.939 	at hudson.model.Executor.run(Executor.java:421)
```

**Comment by joaocgreis** [comment]
I haven't used the git plugin in `git-nodesource-update-reference` and `node-test-binary-arm` because it isn't flexible enough for what I wanted to do there. After a few initial problems, I haven't seen any issues with git in those jobs. I believe the git plugin brings some complexity that we don't need (ref https://github.com/nodejs/build/issues/729), it might be worth developing a small script that we can use instead of it - should be easy in the new pipeline jobs.

**Comment by juggernaut451** [comment]
@rvagg @maclover7 @joaocgreis i can work on it

**Comment by maclover7** [comment]
It _seems_ like the Git errors have largely stopped? Going to close for now, but please reopen if the errors appear again
