### ISSUE TITLE
CI Windows failures

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1133]
https://ci.nodejs.org/job/node-test-binary-windows/15104/COMPILED_BY=vs2017,RUNNER=win10,RUN_SUBSET=1/console
https://ci.nodejs.org/job/node-test-binary-windows/15104/COMPILED_BY=vs2017,RUNNER=win10,RUN_SUBSET=3/console

```
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'c:\\workspace\\node-test-binary-windows\\deps\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\workspace\\node-test-binary-windows\\test\\addons\\01_function_arguments\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\workspace\\node-test-binary-windows\\deps\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\workspace\\node-test-binary-windows\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=c:\\workspace\\node-test-binary-windows',
gyp info spawn args   '-Dnode_gyp_dir=c:\\workspace\\node-test-binary-windows\\deps\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=c:\\workspace\\node-test-binary-windows\\$(Configuration)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\workspace\\node-test-binary-windows\\test\\addons\\01_function_arguments',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\workspace\\node-test-binary-windows\\test\\addons\\01_function_arguments\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
FileTracker : error : Could not load UI satellite dll 'TrackerUI.dll'.  Make sure it exists in an LCID subdirectory of 'C:\Program Files (x86)\MSBuild\14.0\bin\'. [c:\workspace\node-test-binary-windows\test\addons\01_function_arguments\build\addon.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\workspace\node-test-binary-windows\deps\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:129:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "c:\\workspace\\node-test-binary-windows\\Release\\node.exe" "c:\\workspace\\node-test-binary-windows\\deps\\npm\\node_modules\\node-gyp\\bin\\node-gyp" "rebuild" "--directory=test\\addons\\01_function_arguments" "--nodedir=c:\\workspace\\node-test-binary-windows"
gyp ERR! cwd c:\workspace\node-test-binary-windows\test\addons\01_function_arguments
gyp ERR! node -v v10.0.0-pre
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

c:\workspace\node-test-binary-windows>TASKKILL /F /IM node.exe /T   || TRUE
ERROR: The process "node.exe" not found.

c:\workspace\node-test-binary-windows>TASKKILL /F /IM cctest.exe /T   || TRUE
ERROR: The process "cctest.exe" not found.

c:\workspace\node-test-binary-windows>TASKKILL /F /IM run-tests.exe /T   || TRUE
ERROR: The process "run-tests.exe" not found.

c:\workspace\node-test-binary-windows>TASKKILL /F /IM yes.exe /T   || TRUE
ERROR: The process "yes.exe" not found.

c:\workspace\node-test-binary-windows>rm -rfv test/tmp*   || true

c:\workspace\node-test-binary-windows>if not exist test.tap (
echo "Missing test.tap file"  
 set "EXIT_RETURN_VALUE=1" 
) 
"Missing test.tap file"

c:\workspace\node-test-binary-windows>if not exist cctest.tap (
echo "Missing cctest.tap file"  
 set "EXIT_RETURN_VALUE=1" 
) 
"Missing cctest.tap file"

c:\workspace\node-test-binary-windows>rm -vf ../test.tap   || true

c:\workspace\node-test-binary-windows>rm -vf ../cctest.tap   || true

c:\workspace\node-test-binary-windows>mv test.tap ../test.tap   || true
mv: cannot stat 'test.tap': No such file or directory

c:\workspace\node-test-binary-windows>mv cctest.tap ../cctest.tap   || true
mv: cannot stat 'cctest.tap': No such file or directory

c:\workspace\node-test-binary-windows>git clean -fdx   || true
Removing Release/
Removing config.gypi
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSNew.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSProject.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSSettings.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSToolFile.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUserFile.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSUtil.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/MSVSVersion.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/common.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/easy_xml.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/__init__.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/msvs.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/ninja.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/input.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/msvs_emulation.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/ninja_syntax.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/simple_copy.pyc
Removing deps/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.pyc
Removing icu_config.gypi
Removing test/addons/01_function_arguments/
Removing test/addons/02_callbacks/
Removing test/addons/03_object_factory/
Removing test/addons/04_function_factory/
Removing test/addons/05_wrapping_c_objects/
Removing test/addons/06_factory_of_wrapped_objects/
Removing test/addons/07_passing_wrapped_objects_around/
Removing test/addons/08_void_atexitcallback_args/

c:\workspace\node-test-binary-windows>git reset --hard   || true
HEAD is now at 929d87567c added binaries

c:\workspace\node-test-binary-windows>mv ../test.tap test.tap   || true
mv: cannot stat '../test.tap': No such file or directory

c:\workspace\node-test-binary-windows>mv ../cctest.tap cctest.tap   || true
mv: cannot stat '../cctest.tap': No such file or directory

c:\workspace\node-test-binary-windows>exit /b 1 
Build step 'Execute Windows batch command' marked build as failure
TAP Reports Processing: START
```

**Comment by maclover7** [comment]
cc @joaocgreis

**Comment by joaocgreis** [comment]
There are 3 failed runs on that `node-test-binary-windows` job, all from the same machine. The machine only failed here, then resumed operating normally. I checked the update history and a Visual Studio update was installed in the same day, probably while this job was running causing it to fail.

I'll close this issue, let me know if I missed something.

**Comment by BridgeAR** [comment]
Top, thanks for looking into it!
