### ISSUE TITLE
Changed error logging

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/build#1225]
It seems like since a short time failed tests are not showing up directly in the console anymore (no stack). They show up in the TAP result and are listed as failed but without any further details. Was that intentionally?

E.g., https://ci.nodejs.org/job/node-test-commit-aix/14052/nodes=aix61-ppc64/console
https://ci.nodejs.org/job/node-test-commit-aix/14052/nodes=aix61-ppc64/tapResults/

```
Checking ^not ok
/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/test.tap:
not ok 114 parallel/test-buffer-arraybuffer
not ok 147 parallel/test-buffer-readfloat
not ok 149 parallel/test-buffer-read
not ok 150 parallel/test-buffer-readdouble
not ok 163 parallel/test-buffer-writefloat
not ok 164 parallel/test-buffer-writedouble
```

**Comment by richardlau** [comment]
They're there, but Jenkins only shows the tail of the console log by default so you have to look at the full console log for the failures since they were in the early part of the test run. e.g., https://ci.nodejs.org/job/node-test-commit-aix/14052/nodes=aix61-ppc64/consoleFull

```not ok 114 parallel/test-buffer-arraybuffer
  ---
  duration_ms: 2.101
  severity: fail
  stack: |-
    assert.js:79
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: 1.0965097570907576e+227 strictEqual 3.1415
        at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-aix/nodes/aix61-ppc64/test/parallel/test-buffer-arraybuffer.js:33:8)
        at Module._compile (internal/modules/cjs/loader.js:678:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
        at Module.load (internal/modules/cjs/loader.js:589:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
        at Function.Module._load (internal/modules/cjs/loader.js:520:3)
        at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
        at startup (internal/bootstrap/node.js:228:19)
        at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)
  ...
```

**Comment by refack** [comment]
I'm closing this as it seems @richardlau's answer is correct and sufficient.
I'm working on getting better/simpler test output to the jenkins GUI.
