### ISSUE TITLE
Workspace has a .git repository, but it appears to be corrupt

### ISSUE THREAD

**Issue by gibfahn** [nodejs/build#1227]
Just seen this here: [node-test-commit-plinux/16819](https://ci.nodejs.org/job/node-test-commit-plinux/16819/nodes=ppcle-ubuntu1404/console)

```bash
Building remotely on test-osuosl-ubuntu1404-ppc64_le-3 (ppcle-ubuntu1404) in workspace /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404
 > git rev-parse --is-inside-work-tree # timeout=10
ERROR: Workspace has a .git repository, but it appears to be corrupt.
FATAL: java.io.IOException: Remote call on JNLP4-connect connection from 140-211-168-221-openstack.osuosl.org/140.211.168.221:45357 failed
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 140-211-168-221-openstack.osuosl.org/140.211.168.221:45357
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
		at com.sun.proxy.$Proxy79.hasGitRepo(Unknown Source)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.hasGitRepo(RemoteGitImpl.java:280)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1105)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
		at hudson.scm.SCM.checkout(SCM.java:504)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1203)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1727)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.NoClassDefFoundError: java/lang/Throwable$WrappedPrintWriter
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at java.util.logging.SimpleFormatter.format(SimpleFormatter.java:157)
	at java.util.logging.StreamHandler.publish(StreamHandler.java:211)
	at java.util.logging.ConsoleHandler.publish(ConsoleHandler.java:116)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:876)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 140-211-168-221-openstack.osuosl.org/140.211.168.221:45357 failed
	at hudson.remoting.Channel.call(Channel.java:958)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
Caused: hudson.remoting.RemotingSystemException
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:294)
	at com.sun.proxy.$Proxy79.hasGitRepo(Unknown Source)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.hasGitRepo(RemoteGitImpl.java:280)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1105)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1203)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by gibfahn** [comment]
Doesn't seem to be recurring on rebuild, so will close this, just raised it to document the failure.

**Comment by refack** [comment]
I just saw this on:
* https://ci.nodejs.org/computer/test-digitalocean-alpine37_container-x64-2
  job (https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/25151/console)
* https://ci.nodejs.org/computer/test-softlayer-alpine38_container-x64-1/
  job (https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/25091/console)
Had to rimraf workspace to resolve.

**Comment by VijayasaiVS** [comment]
> Doesn't seem to be recurring on rebuild, so will close this, just raised it to document the failure.

When the build is triggered by an Upstream job I'm facing this issue, but when rebuilding it doesn't. Is there any work-around to this. Also may I know why this doesn't happen during rebuild (bc with every build I am trying to clean the workspace the git is initialized freshly)
