### ISSUE TITLE
test-joyent-alpine36_container-x64-1 seems in perma-fail mode

### ISSUE THREAD

**Issue by Trott** [nodejs/build#1239]
<img width="832" alt="screen shot 2018-04-16 at 11 55 48 am" src="https://user-images.githubusercontent.com/718899/38829180-2a3353f2-416d-11e8-9e70-e9a7754064e0.png">

https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/18061/console:

```console
13:58:11 Started by upstream project "node-test-commit-linux" build number 18061
13:58:11 originally caused by:
13:58:11  Started by upstream project "node-test-commit" build number 17812
13:58:11  originally caused by:
13:58:11   Started by upstream project "node-test-pull-request" build number 14337
13:58:11   originally caused by:
13:58:11    Started by user Luigi Pinca
13:58:11 [EnvInject] - Loading node environment variables.
13:58:11 Building remotely on test-joyent-alpine36_container-x64-1 (alpine-last-latest-x64 alpine36-container-x64) in workspace /home/iojs/build/workspace/node-test-commit-linux/nodes/alpine-last-latest-x64
13:58:12  > git rev-parse --is-inside-work-tree # timeout=10
13:58:12 Fetching changes from the remote Git repository
13:58:12  > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
13:58:12 Fetching upstream changes from https://github.com/nodejs/node.git
13:58:12  > git --version # timeout=10
13:58:12 using GIT_SSH to set credentials 
13:58:12  > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/19960/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
13:58:23 Checking out Revision 31461543f40854fe575c05abbbce7e903b1534e4 (refs/remotes/origin/_jenkins_local_branch)
13:58:23  > git config core.sparsecheckout # timeout=10
13:58:23  > git checkout -f 31461543f40854fe575c05abbbce7e903b1534e4
13:58:24 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 165.225.138.30/165.225.138.30:50542
13:58:24 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
13:58:24 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
13:58:24 		at hudson.remoting.Channel.call(Channel.java:952)
13:58:24 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
13:58:24 		at com.sun.proxy.$Proxy78.withRepository(Unknown Source)
13:58:24 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
13:58:24 		at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
13:58:24 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
13:58:24 		at hudson.scm.SCM.checkout(SCM.java:504)
13:58:24 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
13:58:24 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
13:58:24 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
13:58:24 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
13:58:24 		at hudson.model.Run.execute(Run.java:1727)
13:58:24 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
13:58:24 		at hudson.model.ResourceController.execute(ResourceController.java:97)
13:58:24 		at hudson.model.Executor.run(Executor.java:429)
13:58:24 java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins$MasterComputer
13:58:24 	at org.jenkinsci.plugins.gitclient.AbstractGitAPIImpl.withRepository(AbstractGitAPIImpl.java:29)
13:58:24 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.withRepository(CliGitAPIImpl.java:72)
13:58:24 	at sun.reflect.GeneratedMethodAccessor65.invoke(Unknown Source)
13:58:24 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:58:24 	at java.lang.reflect.Method.invoke(Method.java:498)
13:58:24 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:927)
13:58:24 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:901)
13:58:24 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:850)
13:58:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
13:58:24 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
13:58:24 	at hudson.remoting.Request$2.run(Request.java:364)
13:58:24 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
13:58:24 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13:58:24 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
13:58:24 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
13:58:24 	at hudson.remoting.Engine$1$1.run(Engine.java:94)
13:58:24 	at java.lang.Thread.run(Thread.java:748)
13:58:24 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 165.225.138.30/165.225.138.30:50542 failed
13:58:24 	at hudson.remoting.Channel.call(Channel.java:958)
13:58:24 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:278)
13:58:24 	at com.sun.proxy.$Proxy78.withRepository(Unknown Source)
13:58:24 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.withRepository(RemoteGitImpl.java:235)
13:58:24 	at hudson.plugins.git.GitSCM.printCommitMessageToLog(GitSCM.java:1245)
13:58:24 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1218)
13:58:24 	at hudson.scm.SCM.checkout(SCM.java:504)
13:58:24 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
13:58:24 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
13:58:24 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
13:58:24 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
13:58:24 	at hudson.model.Run.execute(Run.java:1727)
13:58:24 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
13:58:24 	at hudson.model.ResourceController.execute(ResourceController.java:97)
13:58:24 	at hudson.model.Executor.run(Executor.java:429)
13:58:24 Run condition [Always] enabling perform for step [[]]
13:58:24 Run condition [Always] enabling perform for step [[]]
13:58:24 TAP Reports Processing: START
13:58:24 Looking for TAP results report in workspace using pattern: *.tap
13:58:24 Saving reports...
13:58:24 Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/alpine-last-latest-x64/builds/18061/tap-master-files/cctest.tap'
13:58:24 Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/alpine-last-latest-x64/builds/18061/tap-master-files/cctest.tap].
13:58:24 Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/alpine-last-latest-x64/builds/18061/tap-master-files/test.tap'
13:58:24 Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/alpine-last-latest-x64/builds/18061/tap-master-files/test.tap].
13:58:25 TAP Reports Processing: FINISH
13:58:25 Checking ^not ok
13:58:25 Notifying upstream projects of job completion
13:58:25 Finished: FAILURE
```

**Comment by Trott** [comment]
I marked it temporarily offline.

**Comment by maclover7** [comment]
@Trott Has this happened recently? If not, then probably safe to close for now
