### ISSUE TITLE
Extensive infra failures for citgm with v10.x

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1285]
Take a look at https://ci.nodejs.org/view/Node.js-citgm/job/citgm-smoker/1437/

Failures to look at include 
ubuntu1204
rhel72
ppcle
debian9
aix61

**Comment by M3kH** [comment]
In debian the first `error:` in logs where:
```
verbose: socket.io npm-test: | 1) socket.io server attachment port should be bound:      
verbose:                     | Uncaught Error: listen EADDRINUSE :::54010                
verbose:                     | at Server.setupListenHandle [as _listen2] (net.js:1330:14)
verbose:                     | at listenInCluster (net.js:1378:12)                       
verbose:                     | at Server.listen (net.js:1466:7)                          
verbose:                     | at Server.listen.Server.attach (lib/index.js:64:524)      
verbose:                     | at new Server (lib/index.js:13:1381)                      
verbose:                     | at Server (lib/index.js:13:160)                           
verbose:                     | at Context.<anonymous> (test/socket.io.js:212:23) 
...
error: socket.io done      | done - the test suite for socket.io version 2.1.1 failed
...
error: failing module(s)   |                     
error: module name:        | eslint              
error: version:            | 4.19.1              
error: error:              | The canary is dead: 
error: error:              | undefined  
```
If does help :-)

Not sure the two errors are related. But seems that parallel building might be running in the same machine.
