### ISSUE TITLE
libuv: persistent osx1010 'could not init' GitException

### ISSUE THREAD

**Issue by bnoordhuis** [nodejs/build#1343]
https://ci.nodejs.org/job/libuv-test-commit-osx/926/nodes=osx1010/consoleText - 
has been happening all day.
<details>

```
Started by upstream project "libuv-test-commit-osx" build number 926
originally caused by:
 Started by upstream project "libuv-test-commit" build number 924
 originally caused by:
  Started by user Ben Noordhuis
[EnvInject] - Loading node environment variables.
Building remotely on test-macstadium-macos10.10-x64-1 (osx1010) in workspace /Users/iojs/build/workspace/libuv-test-commit-osx/nodes/osx1010
Wiping out workspace first.
Cloning the remote Git repository
Cloning repository https://github.com/bnoordhuis/libuv.git
 > git init /Users/iojs/build/workspace/libuv-test-commit-osx/nodes/osx1010 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /Users/iojs/build/workspace/libuv-test-commit-osx/nodes/osx1010
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:772)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:564)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:208)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:360)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:844)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 207.254.58.162/207.254.58.162:61391
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
		at hudson.remoting.Channel.call(Channel.java:952)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor473.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy94.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1137)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
		at hudson.scm.SCM.checkout(SCM.java:504)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1727)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Error performing command: git init /Users/iojs/build/workspace/libuv-test-commit-osx/nodes/osx1010
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2057)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2018)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2014)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1619)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:770)
	... 12 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "/Users/iojs/build/workspace/libuv-test-commit-osx/nodes/osx1010"): error=0, posix_spawn failed
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at hudson.Proc$LocalProc.<init>(Proc.java:249)
	at hudson.Proc$LocalProc.<init>(Proc.java:218)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:929)
	at hudson.Launcher$ProcStarter.start(Launcher.java:449)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2046)
	... 16 more
Caused by: java.io.IOException: error=0, posix_spawn failed
	at java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:339)
	at java.lang.ProcessImpl.start(ProcessImpl.java:270)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 22 more
ERROR: Error cloning remote repo 'origin'
Notifying upstream projects of job completion
Finished: FAILURE
```

</details>

**Comment by maclover7** [comment]
Hmm, maybe some kind of permissions error? Tried refreshing the machine's workspace, now rebuilding the job: https://ci.nodejs.org/job/libuv-test-commit-osx/931/

**Comment by bnoordhuis** [comment]
Yep, it's working again.  Thanks, Jon!
