### ISSUE TITLE
pi1-docker is failing to build in release ci

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#1462]
https://ci-release.nodejs.org/job/iojs+release/3668/nodes=pi1-docker/console

```
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* # timeout=30
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1798)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/*" returned status code 1:
```

**Comment by maclover7** [comment]
cc @rvagg

**Comment by rvagg** [comment]
Looks like I've got it sorted: https://ci-release.nodejs.org/job/iojs+release/3678/nodes=pi1-docker/console

So here's the story: the node repo is too huge to download and unpack on the Pi's in the timeout that Jenkins allows (also if we didn't have timeout it'd make release builds take way longer). So we have a local bare mirror that's used with `--reference ...` so commits are stored ready locally and git only has to fetch the commits unavailable in the reference. We don't keep it updated automatically, it's just a manual thing that someone gets in there (usually me) and runs a `git fetch` to update it. Currently it's stored in ~/.ccache/node.shared.reference (same across all Pis, test and release, so this can all be done from a standard test Pi too, even a Pi 3 for speed) and iojs+release is configured to reference it there.

But it seems that a plain `fetch` in a bare repository doesn't do what it does in a fully checked out one, maybe it only fetches commits on `master` (my guess, I don't know for sure). So in this case, it's trying to clone for `v8.x` and but the delta is getting really big so it has to fetch store a lot of commits that are unavailable in the mirror.

What I've done is be explicit and done a `git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/*` and it seems to have fetched a heap of new stuff that wasn't there before. Now the `fetch` and `checkout` for iojs+release is pretty fast and it's on its way.

This can be closed if the linked job finishes green.
