### ISSUE TITLE
failures on centos7-64-gcc6

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#1468]
See https://ci.nodejs.org/job/node-test-commit-linux/20945/nodes=centos7-64-gcc6/console.

```
18:34:56 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
18:34:56 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:889)
18:34:56 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
18:34:56 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
18:34:56 	at hudson.scm.SCM.checkout(SCM.java:504)
18:34:56 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
18:34:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
18:34:56 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
18:34:56 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
18:34:56 	at hudson.model.Run.execute(Run.java:1798)
18:34:56 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
18:34:56 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:34:56 	at hudson.model.Executor.run(Executor.java:429)
18:34:56 Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/22209/head:refs/remotes/origin/_jenkins_local_branch" returned status code 128:
18:34:56 stdout: 
18:34:56 stderr: ssh: Could not resolve hostname github.com: Name or service not known
18:34:56 fatal: Could not read from remote repository.
```

**Comment by refack** [comment]
Thank you for the report @mcollina.
This was caused by a temporary network failure:
```
14:26:33 stderr: ssh: Could not resolve hostname github.com: Name or service not known
14:26:33 fatal: Could not read from remote repository.
```

We are trying to automate the process of removing such machines from the rotation, and automatically retrying the job on other worker of that type.
