### ISSUE TITLE
Unable to create '/home/iojs/build/workspace/node-test-commit-linuxone/.git/index.lock'

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#1469]
I've seen this 2-3 times today.

https://ci.nodejs.org/job/node-test-commit-linuxone/4273/console
https://ci.nodejs.org/job/node-test-commit-linuxone/4278/console

```
15:42:42 Started by upstream project "node-test-commit" build number 20820
15:42:42 originally caused by:
15:42:42  Started by upstream project "node-test-pull-request" build number 16681
15:42:42  originally caused by:
15:42:42   Started by user Matteo Collina
15:42:42 [EnvInject] - Loading node environment variables.
15:42:42 Building remotely on test-packetnet-ubuntu1604-x64-1 (jenkins-workspace) in workspace /home/iojs/build/workspace/node-test-commit-linuxone
15:42:42  > git rev-parse --is-inside-work-tree # timeout=10
15:42:42 Fetching changes from the remote Git repository
15:42:42  > git config remote.origin.url git@github.com:nodejs/node.git # timeout=10
15:42:42 Fetching upstream changes from git@github.com:nodejs/node.git
15:42:42  > git --version # timeout=10
15:42:42 using GIT_SSH to set credentials 
15:42:42  > git fetch --no-tags --progress git@github.com:nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/22374/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
15:42:43  > git rev-parse refs/remotes/origin/_jenkins_local_branch^{commit} # timeout=10
15:42:43  > git rev-parse refs/remotes/origin/refs/heads/_jenkins_local_branch^{commit} # timeout=10
15:42:43 Checking out Revision 8f4ad83802dbe294c0b2ff059ffd858262e5d5e4 (refs/remotes/origin/_jenkins_local_branch)
15:42:43  > git config core.sparsecheckout # timeout=10
15:42:43  > git checkout -f 8f4ad83802dbe294c0b2ff059ffd858262e5d5e4
15:42:43 hudson.plugins.git.GitException: Command "git checkout -f 8f4ad83802dbe294c0b2ff059ffd858262e5d5e4" returned status code 128:
15:42:43 stdout: 
15:42:43 stderr: fatal: Unable to create '/home/iojs/build/workspace/node-test-commit-linuxone/.git/index.lock': File exists.
15:42:43 
15:42:43 Another git process seems to be running in this repository, e.g.
15:42:43 an editor opened by 'git commit'. Please make sure all processes
15:42:43 are terminated then try again. If it still fails, a git process
15:42:43 may have crashed in this repository earlier:
15:42:43 remove the file manually to continue.
15:42:43 
15:42:43 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2050)
15:42:43 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:72)
15:42:43 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2349)
15:42:43 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 147.75.70.237/147.75.70.237:36492
15:42:43 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
15:42:43 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:389)
15:42:43 		at hudson.remoting.Channel.call(Channel.java:955)
15:42:43 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
15:42:43 		at sun.reflect.GeneratedMethodAccessor383.invoke(Unknown Source)
15:42:43 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:42:43 		at java.lang.reflect.Method.invoke(Method.java:498)
15:42:43 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
15:42:43 		at com.sun.proxy.$Proxy79.execute(Unknown Source)
15:42:43 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1227)
15:42:43 		at hudson.scm.SCM.checkout(SCM.java:504)
15:42:43 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
15:42:43 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
15:42:43 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:42:43 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
15:42:43 		at hudson.model.Run.execute(Run.java:1798)
15:42:43 		at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
15:42:43 		at hudson.model.ResourceController.execute(ResourceController.java:97)
15:42:43 		at hudson.model.Executor.run(Executor.java:429)
15:42:43 Caused: hudson.plugins.git.GitLockFailedException: Could not lock repository. Please try again
15:42:43 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2368)
15:42:43 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
15:42:43 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
15:42:43 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
15:42:43 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
15:42:43 	at hudson.remoting.Request$2.run(Request.java:364)
15:42:43 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
15:42:43 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:42:43 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:42:43 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:42:43 	at hudson.remoting.Engine$1$1.run(Engine.java:94)
15:42:43 	at java.lang.Thread.run(Thread.java:748)
15:42:43 Caused: java.io.IOException: Could not checkout 8f4ad83802dbe294c0b2ff059ffd858262e5d5e4
15:42:43 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1230)
15:42:43 	at hudson.scm.SCM.checkout(SCM.java:504)
15:42:43 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
15:42:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
15:42:43 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:42:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
15:42:43 	at hudson.model.Run.execute(Run.java:1798)
15:42:43 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
15:42:43 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:42:43 	at hudson.model.Executor.run(Executor.java:429)
15:42:43 Notifying upstream projects of job completion
15:42:43 Finished: FAILURE
```

**Comment by refack** [comment]
Thank you for the report.
I'm on it.

**Comment by refack** [comment]
Issue seems to be resolved - https://ci.nodejs.org/job/node-test-commit-linuxone/4293/console
