### ISSUE TITLE
Git memory failures on ubuntu1404-32

### ISSUE THREAD

**Issue by tniessen** [nodejs/build#1499]
I saw a couple of weird Git failures on ubuntu1404-32 recently:

From https://ci.nodejs.org/job/node-test-commit-linux/21641/nodes=ubuntu1404-32/console:

```
11:27:16 + git rebase --committer-date-is-author-date dafaa6ecb520df3761ed68115ee3e6b102963092
11:27:17 First, rewinding head to replay your work on top of it...
11:27:17 git: malloc.c:2374: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.
11:27:17 Aborted
11:27:17 
11:27:17 git encountered an error while preparing the patches to replay
11:27:17 these revisions:
11:27:17 
11:27:17     dafaa6ecb520df3761ed68115ee3e6b102963092...daa0bdf14f21898dc65807ec0a21a9130885c786
```

From https://ci.nodejs.org/job/node-test-commit-linux/21625/nodes=ubuntu1404-32/console:

```
00:08:58 + git rebase --committer-date-is-author-date 8df13ec33d1fe80922e624d301524ade8ef3b669
00:08:59 First, rewinding head to replay your work on top of it...
00:08:59 *** Error in `git': double free or corruption (out): 0x099e9868 ***
00:08:59 Aborted
00:08:59 
00:08:59 git encountered an error while preparing the patches to replay
00:08:59 these revisions:
00:08:59 
00:08:59     8df13ec33d1fe80922e624d301524ade8ef3b669...e38666f2d024a528b353d40c12a2f06e0feb8ce7
```

**Comment by addaleax** [comment]
This seems to be the same issue as https://github.com/nodejs/node/issues/22628 – `python` has been seeing memory errors there too, which sounds like something with the OS or the hardware is broken.

**Comment by tniessen** [comment]
Even more failures:

```
13:21:03 ok 1395 parallel/test-process-exit-from-before-exit
13:21:03   ---
13:21:03   duration_ms: 0.972
13:21:03   ...
13:21:03 make[1]: *** [test-ci] Segmentation fault
13:21:03 make[1]: Leaving directory `/home/iojs/build/workspace/node-test-commit-linux/nodes/ubuntu1404-32'
13:21:03 make: *** [run-ci] Error 2
13:21:03 Build step 'Execute shell' marked build as failure
13:21:03 Performing Post build task...
13:21:03 Match found for : : True
13:21:03 Logical operation result is TRUE
13:21:03 Running script  : #/bin/bash
13:21:03 
13:21:03 set -x
13:21:03 mkdir out/junit
13:21:03 tap2junit -i test.tap -o out/junit/test.xml
13:21:03 tap2junit -i cctest.tap -o out/junit/cctest.xml
13:21:03 [ubuntu1404-32] $ /bin/sh -xe /tmp/jenkins4521245405560941818.sh
13:21:03 + set -x
13:21:03 + mkdir out/junit
13:21:03 + tap2junit -i test.tap -o out/junit/test.xml
13:21:04 Traceback (most recent call last):
13:21:04   File "/usr/local/bin/tap2junit", line 9, in <module>
13:21:04     load_entry_point('tap2junit==0.1.4', 'console_scripts', 'tap2junit')()
13:21:04   File "/usr/local/lib/python2.7/dist-packages/tap2junit/__main__.py", line 44, in main
13:21:04     result = parse(os.path.splitext(args.input.name)[0], data)
13:21:04   File "/usr/local/lib/python2.7/dist-packages/tap2junit/__main__.py", line 15, in parse
13:21:04     t = TestCase(test.description, None, test.yaml['duration_ms'])
13:21:04 TypeError: 'NoneType' object has no attribute '__getitem__'
13:21:04 POST BUILD TASK : FAILURE
13:21:04 END OF POST BUILD TASK : 0
13:21:04 Recording test results
13:21:04 Recording fingerprints
13:21:04 Notifying upstream projects of job completion
13:21:04 Finished: FAILURE
```

make had a segmentation fault...

**Comment by refack** [comment]
We actually shouldn't be testing node >= v10 on 32bit platforms. I'm waiting for reviews on https://github.com/nodejs/build/pull/1498 to solve that.

**Comment by refack** [comment]
Ok. #1498 landed, and I marked https://ci.nodejs.org/computer/test-softlayer-ubuntu1404-x86-1/ as offline.
