### ISSUE TITLE
OSX Release failures

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1518]
Not sure why these are failing now but the osx builds on 1010 seems to be failing consistently with the following running on  release-requireio-osx1010-x64-1.

The second might be because of the failure to checkout in the first?

```
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* # timeout=30
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:888)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1155)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1186)
	at hudson.scm.SCM.checkout(SCM.java:504)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
	at hudson.model.Run.execute(Run.java:1798)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

and

```
+ '[' 'XDeveloper ID Application: Node.js Foundation' == X ']'
+ codesign -s 'Developer ID Application: Node.js Foundation' out/macos/dist/node/usr/local/bin/node
out/macos/dist/node/usr/local/bin/node: A timestamp was expected but was not found.
make: *** [node-v10.11.1-nightly201810037d21cc2177.pkg] Error 1
```

**Comment by mhdawson** [comment]
@rvagg can you take a look as I think it might be a environment issue with the osx1010 machine.

**Comment by rvagg** [comment]
On it, same network issues that have been plaguing the arm cluster for a while. I'm going to do a refresh on the machine and upgrade Fusion, we'll see how it goes after that.

**Comment by rvagg** [comment]
I think we're sorted. I did a big clean up, upgrade, including Fusion and the OS on the host machine. Getting green now https://ci-release.nodejs.org/job/iojs+release/3808/
