### ISSUE TITLE
Channel "unknown": Remote call on JNLP4-connect connection 

### ISSUE THREAD

**Issue by f4th3r** [nodejs/build#1562]
hello everyone!
I use the kubernates plugin for building.
Sometimes i get this kinda error. What ive alredy done is:
-adding more memory and cpu resurces.
i hope anyone will help me:( 2 days without sleeping)))))
Thanks...
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
	at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
	at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:795)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from

**Comment by refack** [comment]
Hello @f4th3r,
This should really go the the Jenkins people... https://jenkins.io/participate/

(P.S. we're having the same issue, with no better solution then "restart and pray")

**Comment by refack** [comment]
Closing since it's not actionable on our side.

**Comment by yakupseker** [comment]
Hi, 

We received similar errors. The source of our problem was that the windows slave took the self-update and then closed and reopened. If any work or pipeline was running during this shutdown, we were getting this error. Make sure the slaves are not disconnected. Good work.
