### ISSUE TITLE
node-stress-test job does not work against node-private

### ISSUE THREAD

**Issue by mcollina** [nodejs/build#1603]
As titled. See https://ci.nodejs.org/job/node-stress-single-test/2111/console for more details:

```
15:34:56 Started by user Matteo Collina
15:34:56 [EnvInject] - Loading node environment variables.
15:34:56 Building remotely on test-packetnet-ubuntu1604-x64-1 (Ubuntu Ubuntu-16.04 amd64-Ubuntu jenkins-workspace amd64-Ubuntu-16.04 16.04 amd64) in workspace /home/iojs/build/workspace/node-stress-single-test
15:34:56  > git rev-parse --is-inside-work-tree # timeout=10
15:34:56 Fetching changes from the remote Git repository
15:34:56  > git config remote.origin.url https://github.com/nodejs-private/node-private.git # timeout=10
15:34:56 Fetching upstream changes from https://github.com/nodejs-private/node-private.git
15:34:56  > git --version # timeout=10
15:34:56  > git fetch --no-tags --progress https://github.com/nodejs-private/node-private.git +refs/heads/*:refs/remotes/origin/* +refs/heads/master:refs/remotes/origin/_jenkins_local_branch # timeout=20
15:34:57 ERROR: Error fetching remote repo 'origin'
15:34:57 hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs-private/node-private.git
15:34:57 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:889)
15:34:57 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
15:34:57 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
15:34:57 	at hudson.scm.SCM.checkout(SCM.java:504)
15:34:57 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
15:34:57 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
15:34:57 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:34:57 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
15:34:57 	at hudson.model.Run.execute(Run.java:1819)
15:34:57 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
15:34:57 	at hudson.model.ResourceController.execute(ResourceController.java:97)
15:34:57 	at hudson.model.Executor.run(Executor.java:429)
15:34:57 Caused by: hudson.plugins.git.GitException: Command "git fetch --no-tags --progress https://github.com/nodejs-private/node-private.git +refs/heads/*:refs/remotes/origin/* +refs/heads/master:refs/remotes/origin/_jenkins_local_branch" returned status code 128:
15:34:57 stdout: 
15:34:57 stderr: remote: Invalid username or password.
15:34:57 fatal: Authentication failed for 'https://github.com/nodejs-private/node-private.git/'
15:34:57 
15:34:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2113)
15:34:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1806)
15:34:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:75)
15:34:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:423)
15:34:57 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
15:34:57 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
15:34:57 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
15:34:57 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
15:34:57 	at hudson.remoting.Request$2.run(Request.java:369)
15:34:57 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
15:34:57 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
15:34:57 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
15:34:57 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
15:34:57 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
15:34:57 	at java.lang.Thread.run(Thread.java:748)
15:34:57 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 147.75.70.237/147.75.70.237:45752
15:34:57 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
15:34:57 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
15:34:57 		at hudson.remoting.Channel.call(Channel.java:955)
15:34:57 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
15:34:57 		at sun.reflect.GeneratedMethodAccessor732.invoke(Unknown Source)
15:34:57 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:34:57 		at java.lang.reflect.Method.invoke(Method.java:498)
15:34:57 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
15:34:57 		at com.sun.proxy.$Proxy91.execute(Unknown Source)
15:34:57 		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:887)
15:34:57 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1146)
15:34:57 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1177)
15:34:57 		at hudson.scm.SCM.checkout(SCM.java:504)
15:34:57 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
15:34:57 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
15:34:57 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
15:34:57 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
15:34:57 		at hudson.model.Run.execute(Run.java:1819)
15:34:57 		at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
15:34:57 		at hudson.model.ResourceController.execute(ResourceController.java:97)
15:34:57 		at hudson.model.Executor.run(Executor.java:429)
15:34:57 ERROR: Error fetching remote repo 'origin'
15:34:57 Notifying upstream projects of job completion
15:34:57 Finished: FAILURE
Pagina generata il: 26-nov-2018 9.35.01 ESTREST APIJenkins ver. 2.138.2
```

**Comment by refack** [comment]
Fixed - https://ci.nodejs.org/job/node-stress-single-test/2112/

Job Diff: https://ci.nodejs.org/job/node-stress-single-test/jobConfigHistory/showDiffFiles?timestamp1=2018-11-22_12-35-25&timestamp2=2018-11-26_09-42-58

**Comment by mcollina** [comment]
works now.
