### ISSUE TITLE
cross-compiler-armv6-gcc-4.9.4 failing with FileAlreadyExistsException

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1626]
e.g. https://ci.nodejs.org/job/node-cross-compile/20204/nodes=cross-compiler-armv6-gcc-4.9.4/console

```
Building remotely on node-msft-cross-compiler-1 (Ubuntu cc-armv7 14.04 cross-compiler-armv7-gcc-4.8 cross-compiler-armv7-gcc-4.9 amd64-Ubuntu-14.04 amd64-Ubuntu cross-compiler-armv7-gcc-4.9.4 cross-compiler-armv6-gcc-4.8 cross-compiler-armv6-gcc-4.9 cc-armv6 cross-compiler-armv6-gcc-4.9.4 Ubuntu-14.04 amd64) in workspace /home/iojs/build/workspace/node-cross-compile
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to node-msft-cross-compiler-1
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1072)
		at hudson.FilePath.act(FilePath.java:1061)
		at hudson.FilePath.mkdirs(FilePath.java:1246)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1810)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.nio.file.FileAlreadyExistsException: /home/iojs/build/workspace
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at hudson.FilePath.mkdirs(FilePath.java:3273)
	at hudson.FilePath.access$1300(FilePath.java:213)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1254)
	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1250)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3086)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Skipped archiving because build is not successful
```

**Comment by richardlau** [comment]
May be limited to [node-msft-cross-compiler-1](https://ci.nodejs.org/computer/node-msft-cross-compiler-1/builds).

**Comment by Trott** [comment]
@rvagg @joaocgreis

**Comment by Trott** [comment]
> May be limited to node-msft-cross-compiler-1.

I took node-msft-cross-compiler-1 offline at @richardlau's suggestion and now the job is succeeding again, but someone who knows what they're doing should fix the host and bring it back online so I'm leaving this issue open...

**Comment by rvagg** [comment]
I think this is good now, will monitor before closing this issue. If anyone notices it failing in the meantime and has access, feel free to disable it again.

**Comment by richardlau** [comment]
Looks like it's working:
![image](https://user-images.githubusercontent.com/5445507/49821045-63112580-fd71-11e8-8e69-e0d9b978b1d5.png)

Thanks Rod!
