### ISSUE TITLE
incident: Jenkins unable to clear workspace (.git remnants)

### ISSUE THREAD

**Issue by refack** [nodejs/build#1682]
Seems like certain git branch names (presumably with non ASCII chars) cause Jenkins to borke.
Error shows up much later then the job finished, only when Jenkins tries to clear the workspace.
Example error:
```
12:05:22  > git rev-parse --is-inside-work-tree # timeout=10
12:05:22 ERROR: Workspace has a .git repository, but it appears to be corrupt.
12:05:22 hudson.plugins.git.GitException: Command "git rev-parse --is-inside-work-tree" returned status code 128:
12:05:22 stdout: 
12:05:22 stderr: fatal: Not a git repository (or any of the parent directories): .git
12:05:22 
12:05:22 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2318)
.
.
.
12:05:22 Cloning the remote Git repository
12:05:22 Cloning repository git@github.com:nodejs/node.git
12:05:25 ERROR: Failed to clean the workspace
12:05:25 java.io.IOException: Unable to delete '/home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
12:05:25 	at hudson.Util.deleteContentsRecursive(Util.java:259)
12:05:25 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:653)
12:05:25 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
12:05:25 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
12:05:25 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
12:05:25 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:05:25 	at hudson.remoting.Request$2.run(Request.java:369)
12:05:25 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
12:05:25 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:05:25 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:05:25 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:05:25 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
12:05:25 	at java.lang.Thread.run(Thread.java:748)
12:05:25 Caused by: java.io.IOException: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/iojs/build/workspace/node-test-commit-plinux/nodes/ppcle-ubuntu1404/.git/refs/remotes/origin/[refack redacted]r-??t[refack redacted]
12:05:25 	at hudson.Util.fileToPath(Util.java:1709)
```

I'm going to try to hunt those file down, so this posting is just FTR.

/CC @node/reliability

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-freebsd/nodes=freebsd11-x64/24041/console looks similar.

**Comment by refack** [comment]
Cleaned https://ci.nodejs.org/computer/test-digitalocean-freebsd11-x64-2/

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-linux/25444/nodes=alpine-last-latest-x64/console

**Comment by refack** [comment]
https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/25447/console
fixed, thanks
