### ISSUE TITLE
Jenkins git error: reference is not a tree

### ISSUE THREAD

**Issue by orangemocha** [nodejs/build#174]
As seen in https://ci.nodejs.org/job/node-test-commit-arm/418/nodes=pi1-raspbian-wheezy-1_of_2/console

```
Started by upstream project "node-test-commit-arm" build number 418
originally caused by:
 Started by upstream project "node-test-commit" build number 413
 originally caused by:
  Started by upstream project "node-test-pull-request" build number 223
  originally caused by:
   Started by user Fedor Indutny
[EnvInject] - Loading node environment variables.
Building remotely on iojs-nodesource-raspbian-wheezy-pi1p-2 (pi1-raspbian-wheezy pi1-raspbian-wheezy-2_of_2 pi1-raspbian-wheezy-1_of_2) in workspace /home/iojs/build/workspace/node-test-commit-arm/nodes/pi1-raspbian-wheezy-1_of_2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
Fetching upstream changes from https://github.com/nodejs/node.git
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/2404/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
Checking out Revision d4ec48c4a33d7f8480215e54b761678adbf114dc (refs/remotes/origin/_jenkins_local_branch)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d4ec48c4a33d7f8480215e54b761678adbf114dc
FATAL: Could not checkout d4ec48c4a33d7f8480215e54b761678adbf114dc
hudson.plugins.git.GitException: Could not checkout d4ec48c4a33d7f8480215e54b761678adbf114dc
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1907)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to iojs-nodesource-raspbian-wheezy-pi1p-2(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1413)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
	at hudson.remoting.Channel.call(Channel.java:778)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:145)
	at sun.reflect.GeneratedMethodAccessor527.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:131)
	at com.sun.proxy.$Proxy49.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1060)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1277)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.plugins.git.GitException: Command "git checkout -f d4ec48c4a33d7f8480215e54b761678adbf114dc" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: d4ec48c4a33d7f8480215e54b761678adbf114dc

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:62)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1899)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:152)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:145)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:325)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:69)
	at java.lang.Thread.run(Thread.java:745)
Publish TAP Results is waiting for a checkpoint on node-test-commit-arm » pi1-raspbian-wheezy-1_of_2 #417
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: test.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/node-test-commit-arm/configurations/axis-nodes/pi1-raspbian-wheezy-1_of_2/builds/418/tap-master-files/test.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-arm/configurations/axis-nodes/pi1-raspbian-wheezy-1_of_2/builds/418/tap-master-files/test.tap].
TAP Reports Processing: FINISH
Checking ^not ok
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by orangemocha** [comment]
Hypothesizing that this PR was updated around the time the job started.

**Comment by orangemocha** [comment]
cc @nodejs/jenkins-admins

**Comment by orangemocha** [comment]
Hypothesis not validated, given https://github.com/nodejs/node/pull/2404#issuecomment-136723262

**Comment by jbergstroem** [comment]
Haven't seen this since. @orangemocha reopen if you have.
