### ISSUE TITLE
 test-linuxonecc-rhel72-s390x-3 running out of disk space

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#1749]
We just added this machine back in after adding gcc 6 and seems to be running out of space.

That is the cause of a number of recent linuxone failures.  Taking offline while we figure out what is going on.

@sam-github

**Comment by refack** [comment]
Temporary fix `yum clean all`.
AFAICT the most significant difference is this machine has some docker images on the smaller harddisk (`/var/lib/docker`). Probably should also be symlinked to `/data/`

**Comment by mhdawson** [comment]
@refack that would make sense.  In addition I'm wondering if the /user/iojs is properly linked as we should be using the larger disk to build.  That could be a result of the effort to get the ansible playbook working again.

**Comment by refack** [comment]
> if the /user/iojs is properly linked as we should be using the larger disk to build.

It is, first thing I checked.
![image](https://user-images.githubusercontent.com/96947/55483251-3882fb00-55f4-11e9-908e-f20f46c34979.png)

**Comment by mhdawson** [comment]
It's strange that we'd still need space on the smaller disk for the builds

**Comment by refack** [comment]
It got to 100%, probably didn't even have space for logs in `/var` ¯\\_(ツ)_/¯, but yeah probably should figure out what it was exactly.

**Comment by mhdawson** [comment]
I've asked Sam to look at the docker side, we do want to experiment with using it more but looks like we need to move it to the larger disk

**Comment by sam-github** [comment]
I need access to the other s390 machines so I can compare and see what is different about this one, cf https://github.com/nodejs/build/issues/1721

**Comment by sam-github** [comment]
Once I have access to the other s390s, I'll see if the docker images are specific to this once machine. If so, they are likely from experiments by @miladfarca and can perhaps be deleted. Actually, probably all docker can be deleted, I don't think we use it.

**Comment by sam-github** [comment]
System provisioning is about the same, it seems its the docker that has put things over the edge:

```

[root@test-linuxonecc-rhel72-s390x-3 /]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES                                           
d94d2140f4ca        rhel-devtoolset-6   "bash entryPoint.s..."   About an hour ago   Up About an hour                        affectionate_carson                             
[root@test-linuxonecc-rhel72-s390x-3 /]# !du
du -hs /var/lib/docker/
2.4G    /var/lib/docker/
```


```
[root@test-linuxonecc-rhel72-s390x-1 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasda2     5.8G  4.4G  1.2G  80% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G  401M  3.5G  11% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/dasdb1      99G   18G   77G  19% /data
/dev/dasda1     372M  127M  218M  37% /boot
tmpfs           786M     0  786M   0% /run/user/0

[root@test-linuxonecc-rhel72-s390x-3 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasda2     5.8G  5.0G  505M  91% /
devtmpfs        7.8G     0  7.8G   0% /dev
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           7.8G  8.6M  7.8G   1% /run
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/dasdb1      99G  9.7G   84G  11% /data
/dev/dasda1     372M  140M  204M  41% /boot
tmpfs           1.6G     0  1.6G   0% /run/user/0
overlay          99G  9.7G   84G  11% /data/docker/overlay2/d3e110313a843da24bb6ea6d45e006349156200a47bbc017e054be413bd280ce/merged
shm              64M     0   64M   0% /data/docker/containers/d94d2140f4ca8e22f9c0a1cb2af4621186a10e9e8ef3b8646fca081679af0612/shm
```

**Comment by miladfarca** [comment]
Sorry just saw this ticket, we are running Docker tests on this machine, I have changed the docker image DIR from `/var/lib/docker` to `/dev/docker` and `/var/lib/docker` can be cleared if needed.

**Comment by sam-github** [comment]
Checked with @miladfarca, he has moved his docker images to `/dev`, and I did a `rm -rf /var/lib/docker/*`.

Now:
```
[root@test-linuxonecc-rhel72-s390x-3 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/dasda2     5.8G  2.7G  2.9G  48% /
```

Should be good to re-enable this in the CI. @refack @mhdawson

**Comment by mhdawson** [comment]
ok re-enabled.  Will leave this open for today and if not more problems will close tomorrow.

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-linuxone/12126/nodes=rhel72-s390x/console

```console
12:32:57 Cloning repository git@github.com:nodejs/node.git
12:32:57  > git init /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x # timeout=10
12:32:57 ERROR: Error cloning remote repo 'origin'
12:32:57 hudson.plugins.git.GitException: Could not init /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:882)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:662)
12:32:57 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
12:32:57 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:154)
12:32:57 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
12:32:57 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:32:57 	at hudson.remoting.Request$2.run(Request.java:369)
12:32:57 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
12:32:57 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:32:57 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:32:57 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:32:57 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
12:32:57 	at java.lang.Thread.run(Thread.java:748)
12:32:57 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 148.100.110.150/148.100.110.150:42478
12:32:57 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
12:32:57 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
12:32:57 		at hudson.remoting.Channel.call(Channel.java:955)
12:32:57 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
12:32:57 		at sun.reflect.GeneratedMethodAccessor638.invoke(Unknown Source)
12:32:57 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:32:57 		at java.lang.reflect.Method.invoke(Method.java:498)
12:32:57 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
12:32:57 		at com.sun.proxy.$Proxy102.execute(Unknown Source)
12:32:57 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1135)
12:32:57 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1175)
12:32:57 		at hudson.scm.SCM.checkout(SCM.java:504)
12:32:57 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
12:32:57 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
12:32:57 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:32:57 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
12:32:57 		at hudson.model.Run.execute(Run.java:1810)
12:32:57 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:32:57 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:32:57 		at hudson.model.Executor.run(Executor.java:429)
12:32:57 Caused by: hudson.plugins.git.GitException: Error performing git command: git init /data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2325)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2248)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2244)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1777)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:880)
12:32:57 	... 12 more
12:32:57 Caused by: java.io.IOException: Cannot run program "git" (in directory "/data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x"): error=2, No such file or directory
12:32:57 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
12:32:57 	at hudson.Proc$LocalProc.<init>(Proc.java:249)
12:32:57 	at hudson.Proc$LocalProc.<init>(Proc.java:218)
12:32:57 	at hudson.Launcher$LocalLauncher.launch(Launcher.java:936)
12:32:57 	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
12:32:57 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2311)
12:32:57 	... 16 more
12:32:57 Caused by: java.io.IOException: error=2, No such file or directory
12:32:57 	at java.lang.UNIXProcess.forkAndExec(Native Method)
12:32:57 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
12:32:57 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
12:32:57 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
12:32:57 	... 21 more
12:32:57 ERROR: Error cloning remote repo 'origin'
12:32:57 Performing Post build task...
12:32:57 Match found for : : True
12:32:57 Logical operation result is TRUE
12:32:57 Running script  : #/bin/bash
12:32:57 
12:32:57 set -x
12:32:57 mkdir out/junit
12:32:57 tap2junit -i test.tap -o out/junit/test.xml
12:32:57 tap2junit -i cctest.tap -o out/junit/cctest.xml
12:32:58 [rhel72-s390x] $ /bin/sh -xe /tmp/jenkins14971713960539597.sh
12:32:58 FATAL: command execution failed
12:32:58 java.io.IOException: error=2, No such file or directory
12:32:58 	at java.lang.UNIXProcess.forkAndExec(Native Method)
12:32:58 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
12:32:58 	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
12:32:58 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
12:32:58 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 148.100.110.150/148.100.110.150:42478
12:32:58 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
12:32:58 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
12:32:58 		at hudson.remoting.Channel.call(Channel.java:955)
12:32:58 		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1059)
12:32:58 		at hudson.Launcher$ProcStarter.start(Launcher.java:455)
12:32:58 		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
12:32:58 		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
12:32:58 		at hudson.plugins.postbuildtask.PostbuildTask.perform(PostbuildTask.java:123)
12:32:58 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:32:58 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
12:32:58 		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
12:32:58 		at hudson.model.Build$BuildExecution.post2(Build.java:186)
12:32:58 		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
12:32:58 		at hudson.model.Run.execute(Run.java:1835)
12:32:58 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:32:58 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:32:58 		at hudson.model.Executor.run(Executor.java:429)
12:32:58 Caused: java.io.IOException: Cannot run program "/bin/sh" (in directory "/data/iojs/build/workspace/node-test-commit-linuxone/nodes/rhel72-s390x"): error=2, No such file or directory
12:32:58 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
12:32:58 	at hudson.Proc$LocalProc.<init>(Proc.java:249)
12:32:58 	at hudson.Proc$LocalProc.<init>(Proc.java:218)
12:32:58 	at hudson.Launcher$LocalLauncher.launch(Launcher.java:936)
12:32:58 	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
12:32:58 	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1313)
12:32:58 	at hudson.Launcher$RemoteLaunchCallable.call(Launcher.java:1266)
12:32:58 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
12:32:58 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:32:58 	at hudson.remoting.Request$2.run(Request.java:369)
12:32:58 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
12:32:58 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:32:58 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:32:58 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:32:58 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
12:32:58 	at java.lang.Thread.run(Thread.java:748)
12:32:58 POST BUILD TASK : FAILURE
```

**Comment by refack** [comment]
🤔 
```Console
[root@test-linuxonecc-rhel72-s390x-3 iojs]# ls -la
-bash: /usr/bin/ls: /lib/ld64.so.1: bad ELF interpreter: No such file or directory
^D
logout
Connection to 148.100.110.150 closed.
refael@refaelux:~$ ssh test-linuxonecc-rhel72-s390x-3
root@148.100.110.150's password:
^C
refael@refaelux:~$ ssh test-linuxonecc-rhel72-s390x-3
root@148.100.110.150's password:

refael@refaelux:~$
```

**Comment by sam-github** [comment]
We're having trouble with it, too. It looks like marist might be running portscan detection, because if I ssh into multiple s390x machines in sucession, I start getting ECONNRESET for all of them. The auth problem on -3 just started in the last 10-20 minutes. I have it, as does @miladfarca. We'll restart and contact the provider.

**Comment by sam-github** [comment]
> /lib/ld64.so.1: bad ELF interpreter

That is bizarre. It happend at "about" the same time that I tried to copy my personal ID to -`, using `ssh-copy-id`, I'd been using the machines root RSA ID file before that to get in, but since my public ID was authorized on the others, I thought to use the same ID for -3. Its possible `ssh-copy-id` went awry.

It looks like we will have to have the machine rebuilt from scratch, the root user didn't have a password, just ssh access, so no console access is possible. Oh, well. Gives me a chance to do an end-to-end ansible and see if it works.

**Comment by mhdawson** [comment]
Turns out it was finger problems and we deleted the  root drive.  Machine has been re-imaged, setup with ansible again, closing.
