### ISSUE TITLE
trying to send test configuration email but Failed to send out e-mail (java.net.ConnectException: Connection refused: connect)

### ISSUE THREAD

**Issue by 9908928306555p** [nodejs/build#1805]
Hello Guys, 

In Jenkins i am using
 email notification smtp server : smtp.gmail.com
username and password of my gmail 
smtp port 465 and also i have installed email extension and email extension template but its throwing me error.

Failed to send out e-mail

java.net.ConnectException: Connection refused: connect

	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)

	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)

	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

	at java.net.PlainSocketImpl.connect(Unknown Source)

	at java.net.SocksSocketImpl.connect(Unknown Source)

	at java.net.Socket.connect(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)

	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)

	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:205)

	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)

Caused: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465;
  nested exception is:
	java.net.ConnectException: Connection refused: connect

	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)

	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)

	at javax.mail.Service.connect(Service.java:317)

	at javax.mail.Service.connect(Service.java:176)

	at javax.mail.Service.connect(Service.java:125)

	at javax.mail.Transport.send0(Transport.java:194)

	at javax.mail.Transport.send(Transport.java:124)

	at hudson.tasks.Mailer$DescriptorImpl.doSendTestMail(Mailer.java:591)

	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)

	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)

	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)

	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:77)

	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)

	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)

	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)

	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:537)

	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)

	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:282)

	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)

	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:739)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:870)

	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:668)

	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)

	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)

	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)

	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)

	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)

	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)

	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)

	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)

	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)

	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)

	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

	at org.eclipse.jetty.server.Server.handle(Server.java:503)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)

	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)

	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)

	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)

	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)

	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)

	at java.lang.Thread.run(Unknown Source)

Please assist me. Thanks.

**Comment by sam-github** [comment]
I'm sorry, you appear to have questions about Jenkins, not about the Node.js build CI. We can't help with that.

If I mistook the nature of your question, please provide more information.
