### ISSUE TITLE
test-macstadium-macos10.11-x64-2

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#1837]
Recent https://ci.nodejs.org/job/node-test-commit-osx/ builds on https://ci.nodejs.org/computer/test-macstadium-macos10.11-x64-2/ are failing,
e.g. https://ci.nodejs.org/job/node-test-commit-osx/27447/nodes=osx1011/
```console
12:22:32 Building remotely on test-macstadium-macos10.11-x64-2 (osx1011 x86_64 x86_64-mac x86_64-mac-10.11.1 10.11.1 mac-10.11.1 mac) in workspace /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1011
12:22:32 FATAL: java.nio.channels.ClosedChannelException
12:22:32 java.nio.channels.ClosedChannelException
12:22:32 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 207.254.58.162/207.254.58.162:61948
12:22:32 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
12:22:32 		at hudson.remoting.Request.call(Request.java:202)
12:22:32 		at hudson.remoting.Channel.call(Channel.java:956)
12:22:32 		at hudson.FilePath.act(FilePath.java:1069)
12:22:32 		at hudson.FilePath.act(FilePath.java:1058)
12:22:32 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:120)
12:22:32 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:832)
12:22:32 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:823)
12:22:32 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1169)
12:22:32 		at hudson.scm.SCM.checkout(SCM.java:504)
12:22:32 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
12:22:32 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
12:22:32 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:22:32 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
12:22:32 		at hudson.model.Run.execute(Run.java:1816)
12:22:32 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:22:32 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:22:32 		at hudson.model.Executor.run(Executor.java:429)
12:22:32 Caused: hudson.remoting.RequestAbortedException
12:22:32 	at hudson.remoting.Request.abort(Request.java:340)
12:22:32 	at hudson.remoting.Channel.terminate(Channel.java:1040)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
12:22:32 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
12:22:32 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
12:22:32 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
12:22:32 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
12:22:32 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
12:22:32 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
12:22:32 	at hudson.remoting.Channel.close(Channel.java:1452)
12:22:32 	at hudson.remoting.Channel.close(Channel.java:1405)
12:22:32 	at jenkins.slaves.DefaultJnlpSlaveReceiver.afterChannel(DefaultJnlpSlaveReceiver.java:173)
12:22:32 	at org.jenkinsci.remoting.engine.JnlpConnectionState$4.invoke(JnlpConnectionState.java:421)
12:22:32 	at org.jenkinsci.remoting.engine.JnlpConnectionState.fire(JnlpConnectionState.java:312)
12:22:32 	at org.jenkinsci.remoting.engine.JnlpConnectionState.fireAfterChannel(JnlpConnectionState.java:418)
12:22:32 	at org.jenkinsci.remoting.engine.JnlpProtocol4Handler$Handler$1.run(JnlpProtocol4Handler.java:334)
12:22:32 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
12:22:32 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
12:22:32 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:22:32 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:22:32 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by refack** [comment]
The Jenkins agent was blinking in and out. Quick Google search hinted at a possible JDK12 incompatibility, so I downloaded OpenJDK 11.0.2 and set the agent to use it. Seems stable now.
https://ci.nodejs.org/job/node-test-commit-osx/27453/nodes=osx1011/

(Leaving this open for follow up)
