### ISSUE TITLE
"Error: Command 'download_from_google_storage" on node-test-commit-v8-linux

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2135]
I'm constantly getting this error when trying to run V8 tests on a PR:

```
09:18:35 Failed to fetch file gs://chromium-clang-format/942fc8b1789144b8071d3fc03ff0fcbe1cf81ac8 for v8/buildtools/linux64/clang-format. [Err: gsutil requires python 2.6 or 2.7.
09:18:35 ]
09:18:35 0> Failed to fetch file gs://chromium-clang-format/942fc8b1789144b8071d3fc03ff0fcbe1cf81ac8 for v8/buildtools/linux64/clang-format, skipping. [Err: gsutil requires python 2.6 or 2.7.
09:18:35 ]
09:18:35 Downloading 1 files took 4.291850 second(s)
09:18:35 Warning: gclient doesn't yet support Python 3 and may not work correctly.
09:18:35 Error: Command 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in .
09:18:35 Checking out depot_tools.
09:18:35 Using depot tools in /home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark-ubuntu1604-intel-64/v8test/v8test/deps/v8/_depot_tools
09:18:35 Initializing temporary git repository in v8.
09:18:35 Fetching dependencies.
09:18:35 Uninitializing temporary git repository
09:18:35 >> Cleaning up /home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark-ubuntu1604-intel-64/v8test/v8test/deps/v8/.git
09:18:35 Traceback (most recent call last):
09:18:35   File "tools/node/fetch_deps.py", line 101, in <module>
09:18:35     FetchDeps(sys.argv[1])
09:18:35   File "tools/node/fetch_deps.py", line 85, in FetchDeps
09:18:35     env=env)
09:18:35   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
09:18:35     raise CalledProcessError(retcode, cmd)
09:18:35 subprocess.CalledProcessError: Command '['/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark-ubuntu1604-intel-64/v8test/v8test/out/tools/bin/python', '/home/iojs/build/workspace/node-test-commit-v8-linux/nodes/benchmark-ubuntu1604-intel-64/v8test/v8test/deps/v8/_depot_tools/gclient.py', 'sync', '--spec', "solutions = [{'deps_file': 'DEPS', 'custom_deps': {'v8/test/mozilla/data': None, 'v8/test/test262/data': None, 'v8/third_party/qemu-linux-x64': None, 'v8/third_party/googletest/src': None, 'v8/third_party/fuchsia-sdk': None, 'v8/base/trace_event/common': None, 'v8/third_party/android_sdk': None, 'v8/third_party/instrumented_libraries': None, 'v8/tools/swarming_client': None, 'v8/third_party/catapult': None, 'v8/third_party/colorama/src': None, 'v8/tools/luci-go': None, 'v8/testing/gmock': None, 'v8/third_party/android_ndk': None, 'v8/test/benchmarks/data': None, 'v8/test/test262/harness': None}, 'url': 'https://chromium.googlesource.com/v8/v8.git', 'managed': False, 'name': 'v8'}]"]' returned non-zero exit status 2
09:18:35 Makefile:292: recipe for target 'v8' failed
09:18:35 make: *** [v8] Error 1
09:18:36 Build step 'Execute shell' marked build as failure
09:18:38 All downstream projects complete!
09:18:39 Sending e-mails to: michael_dawson@ca.ibm.com vieuxtech@gmail.com info@bnoordhuis.nl refack@gmail.com
09:18:40 Recording test results
09:18:41 ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

(https://ci.nodejs.org/job/node-test-commit-v8-linux/2801/nodes=benchmark-ubuntu1604-intel-64,v8test=v8test/console)

Is this expected due to changes on Python in our servers?

On a side note: for this particular test, we don't need depot tools, so we should probably skip it?

**Comment by richardlau** [comment]
> 
> Is this expected due to changes on Python in our servers?
> 

Yes, see https://github.com/nodejs/node/issues/30152 (and https://github.com/nodejs/node/issues/24512).

> On a side note: for this particular test, we don't need depot tools, so we should probably skip it?

The job runs the `test-v8` Makefile target:
https://github.com/nodejs/node/blob/e47a1eb0d32713854379ee1190d28e87657c52a7/Makefile#L663
which depends on the `v8` target:
https://github.com/nodejs/node/blob/e47a1eb0d32713854379ee1190d28e87657c52a7/Makefile#L291-L292
which uses https://github.com/nodejs/node/blob/master/tools/make-v8.sh which is the thing [running `fetch_deps.py`](https://github.com/nodejs/node/blob/master/tools/make-v8.sh#L7). Are you saying it's possible to build V8 without depot tools?

**Comment by mmarchini** [comment]
True, I misread the output here, I though this particular subjob would only run `test-v8-updates`

**Comment by mmarchini** [comment]
I think this was fixed? Reopen if not
