### ISSUE TITLE
Connection issues on node-test-binary-arm-12

### ISSUE THREAD

**Issue by lundibundi** [nodejs/build#2136]
Lots of CI failures due to node-test-binary-arm-12 being unable to connect and publish the results for some reason I assume.

<details><summary>Relevant errors</summary>
<p>

```cmd
08:23:58 FATAL: Remote call on JNLP4-connect connection from 203.217.18.114/203.217.18.114:50950 failed
08:23:58 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 203.217.18.114/203.217.18.114:50950
08:23:58 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
08:23:58 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
08:23:58 		at hudson.remoting.Channel.call(Channel.java:955)
08:23:58 		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1086)
08:23:58 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:510)
08:23:58 		at hudson.model.Run.execute(Run.java:1853)
08:23:58 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
08:23:58 		at hudson.model.ResourceController.execute(ResourceController.java:97)
08:23:58 		at hudson.model.Executor.run(Executor.java:427)
08:23:58 java.lang.NoClassDefFoundError: Could not initialize class hudson.slaves.SlaveComputer
08:23:58 	at hudson.util.ProcessTree.get(ProcessTree.java:432)
08:23:58 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1103)
08:23:58 	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1094)
08:23:58 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
08:23:58 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
08:23:58 	at hudson.remoting.Request$2.run(Request.java:369)
08:23:58 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
08:23:58 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08:23:58 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:23:58 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:23:58 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
08:23:58 	at java.lang.Thread.run(Thread.java:748)
08:23:58 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 203.217.18.114/203.217.18.114:50950 failed
08:23:58 	at hudson.remoting.Channel.call(Channel.java:961)
08:23:58 	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1086)
08:23:58 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:510)
08:23:58 	at hudson.model.Run.execute(Run.java:1853)
08:23:58 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
08:23:58 	at hudson.model.ResourceController.execute(ResourceController.java:97)
08:23:58 	at hudson.model.Executor.run(Executor.java:427)
08:23:58 [Text Finder] Looking for pattern '^not ok' in the files at '*.tap'
08:23:58 Performing Post build task...
08:23:58 Match found for : : True
08:23:58 Logical operation result is TRUE
08:23:58 Running script  : #/bin/bash -x +e
08:23:58 
08:23:58 mkdir out/junit || true
08:23:58 tap2junit -i test.tap -o out/junit/test.xml || true
08:23:58 tap2junit -i cctest.tap -o out/junit/cctest.xml || true
08:23:59 [node-test-binary-arm] $ /bin/sh -xe /tmp/jenkins3761702170793012584.sh
08:23:59 + mkdir out/junit
08:23:59 + tap2junit -i test.tap -o out/junit/test.xml
08:24:01 + tap2junit -i cctest.tap -o out/junit/cctest.xml
08:24:02 usage: tap2junit [-h] --input INPUT --output OUTPUT
08:24:02 tap2junit: error: argument --input/-i: can't open 'cctest.tap': [Errno 2] No such file or directory: 'cctest.tap'
08:24:02 + true
08:24:03 POST BUILD TASK : SUCCESS
08:24:03 END OF POST BUILD TASK : 0
08:24:03 Recording test results
08:24:03 ERROR: Step ‘Publish JUnit test result report’ aborted due to exception: 
08:24:03 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 203.217.18.114/203.217.18.114:50950
08:24:03 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
08:24:03 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
08:24:03 		at hudson.remoting.Channel.call(Channel.java:955)
08:24:03 		at hudson.FilePath.act(FilePath.java:1069)
08:24:03 		at hudson.FilePath.act(FilePath.java:1058)
08:24:03 		at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
08:24:03 		at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
08:24:03 		at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
08:24:03 		at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:154)
08:24:03 		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
08:24:03 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
08:24:03 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
08:24:03 		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
08:24:03 		at hudson.model.Build$BuildExecution.post2(Build.java:186)
08:24:03 		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
08:24:03 		at hudson.model.Run.execute(Run.java:1878)
08:24:03 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
08:24:03 		at hudson.model.ResourceController.execute(ResourceController.java:97)
08:24:03 		at hudson.model.Executor.run(Executor.java:427)
08:24:03 java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
08:24:03 	at hudson.ExtensionList.lookup(ExtensionList.java:433)
08:24:03 	at hudson.tasks.junit.TestNameTransformer.all(TestNameTransformer.java:40)
08:24:03 	at hudson.tasks.junit.TestNameTransformer.getTransformedName(TestNameTransformer.java:33)
08:24:03 	at hudson.tasks.junit.CaseResult.getTransformedTestName(CaseResult.java:273)
08:24:03 	at hudson.tasks.junit.SuiteResult.casesByName(SuiteResult.java:134)
08:24:03 	at hudson.tasks.junit.SuiteResult.addCase(SuiteResult.java:297)
08:24:03 	at hudson.tasks.junit.SuiteResult.<init>(SuiteResult.java:270)
08:24:03 	at hudson.tasks.junit.SuiteResult.parseSuite(SuiteResult.java:209)
08:24:03 	at hudson.tasks.junit.SuiteResult.parseSuite(SuiteResult.java:204)
08:24:03 	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:181)
08:24:03 	at hudson.tasks.junit.TestResult.parse(TestResult.java:348)
08:24:03 	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:281)
08:24:03 	at hudson.tasks.junit.TestResult.parse(TestResult.java:206)
08:24:03 	at hudson.tasks.junit.TestResult.parse(TestResult.java:178)
08:24:03 	at hudson.tasks.junit.TestResult.<init>(TestResult.java:143)
08:24:03 	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:146)
08:24:03 	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:118)
08:24:03 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
08:24:03 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
08:24:03 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
08:24:03 	at hudson.remoting.Request$2.run(Request.java:369)
08:24:03 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
08:24:03 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08:24:03 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:24:03 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:24:03 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
08:24:03 	at java.lang.Thread.run(Thread.java:748)
08:24:03 Caused: java.io.IOException: Remote call on JNLP4-connect connection from 203.217.18.114/203.217.18.114:50950 failed
08:24:03 	at hudson.remoting.Channel.call(Channel.java:961)
08:24:03 	at hudson.FilePath.act(FilePath.java:1069)
08:24:03 	at hudson.FilePath.act(FilePath.java:1058)
08:24:03 	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:114)
08:24:03 	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:137)
08:24:03 	at hudson.tasks.junit.JUnitResultArchiver.parseAndAttach(JUnitResultArchiver.java:167)
08:24:03 	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:154)
08:24:03 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
08:24:03 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
08:24:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
08:24:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
08:24:03 	at hudson.model.Build$BuildExecution.post2(Build.java:186)
08:24:03 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
08:24:03 	at hudson.model.Run.execute(Run.java:1878)
08:24:03 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
08:24:03 	at hudson.model.ResourceController.execute(ResourceController.java:97)
08:24:03 	at hudson.model.Executor.run(Executor.java:427)
```

</p>
</details>

Some of the affected builds:
https://ci.nodejs.org/job/node-test-pull-request/28495/
https://ci.nodejs.org/job/node-test-pull-request/28493/
https://ci.nodejs.org/job/node-test-pull-request/28490/
https://ci.nodejs.org/job/node-test-pull-request/28489/
https://ci.nodejs.org/job/node-test-pull-request/28487/

/cc @nodejs/build

**Comment by lundibundi** [comment]
Oh well, it looks like everything is back online. :smile:

**Comment by AshCripps** [comment]
Reopening, the jobs are back to the normal because the affected machines were marked offline. Still needs investigating

**Comment by Trott** [comment]
@rvagg

**Comment by rvagg** [comment]
I've taken node-test-commit-arm-fanned offline for now, too much of a cluster of problems. I'll do some maintenance, update the systems, clean out tmp files and caches and reboot them all to see if we can get back to a better state. I'll take note of the offline ones in my maintenance doc to try and identify the permafail ones that probably should be retired or reprovisioned.

**Comment by rvagg** [comment]
done some cleaning, put the job back online again and am running some test builds
