### ISSUE TITLE
network differences resulting in test failures

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2165]
Network settings for test-rackspace-ubuntu1604-x64-1 and test-rackspace-ubuntu1604-x64-2 appear to be different, or at least I'm inferring that from the fact that the nightly internet test runs fail on test-rackspace-ubuntu1604-x64-2 but succeed on test-rackspace-ubuntu1604-x64-1.

Here's what a failure looks like:

https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/12019/console

```console
06:06:21 not ok 7 internet/test-dgram-multicast-ssmv6-multi-process
06:06:21   ---
06:06:21   duration_ms: 5.223
06:06:21   severity: fail
06:06:21   exitcode: 1
06:06:21   stack: |-
06:06:21     [PARENT] sent "First message to send" to ff3e::1234:15000
06:06:21     [PARENT] sent "Second message to send" to ff3e::1234:15000
06:06:21     [PARENT] sent "Third message to send" to ff3e::1234:15000
06:06:21     [PARENT] sent "Fourth message to send" to ff3e::1234:15000
06:06:21     [PARENT] sendSocket closed
06:06:21     [PARENT] Responses were not received within 5000 ms.
06:06:21     [PARENT] Fail
06:06:21     assert.js:142
06:06:21       throw err;
06:06:21       ^
06:06:21     
06:06:21     AssertionError [ERR_ASSERTION]: Failed
06:06:21         at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-custom-suites-freestyle/test/internet/test-dgram-multicast-ssmv6-multi-process.js:140:12)
06:06:21         at listOnTimeout (internal/timers.js:549:17)
06:06:21         at processTimers (internal/timers.js:492:7) {
06:06:21       generatedMessage: true,
06:06:21       code: 'ERR_ASSERTION',
06:06:21       actual: undefined,
06:06:21       expected: undefined,
06:06:21       operator: 'fail'
06:06:21     }
06:06:21   ...
```

**Comment by rvagg** [comment]
The difference in /etc/hosts is that -2 has its ipv6, ipv4 and intranet ip addresses listed as resolving to its own hostname whereas -1 doesn't. I've manually added in the entries for -1. 🤞

**Comment by Trott** [comment]
I'm going to optimistically close this. I usually watch node-daily-master closely enough that if this didn't fix it, I'll notice and re-open. Thanks, @rvagg!

**Comment by sam-github** [comment]
Happened again? This is on test-rackspace-ubuntu1604-x64-2

- https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/13516/

```
Error Message
[PARENT] sent "First message to send" to ff3e::1234:15000
[PARENT] sent "Second message to send" to ff3e::1234:15000
[PARENT] sent "Third message to send" to ff3e::1234:15000
[PARENT] sent "Fourth message to send" to ff3e::1234:15000
[PARENT] sendSocket closed
[PARENT] Responses were not received within 5000 ms.
[PARENT] Fail
assert.js:142
  throw err;
  ^

AssertionError [ERR_ASSERTION]: Failed
    at Timeout._onTimeout (/home/iojs/build/workspace/node-test-commit-custom-suites-freestyle/test/internet/test-dgram-multicast-ssmv6-multi-process.js:140:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: 'fail'
}
```

**Comment by mhdawson** [comment]
Going to close this since it looks like its not recreated again for a long time.
