### ISSUE TITLE
[Incident] All nodes of label ‘jenkins-workspace’ are offline

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2211]
Is there any maintenance going on our Jenkins right now? The last three PR jobs are `pending—All nodes of label ‘jenkins-workspace’ are offline`

![img-2020-03-09-132342](https://user-images.githubusercontent.com/4048656/76254181-416b4c00-6209-11ea-9569-df0da6169f95.png)

cc @nodejs/build @nodejs/jenkins-admins

**Comment by mmarchini** [comment]
`test-packetnet-ubuntu1604-x64-` machines are offline on Jenkins (Connection was broken)

![img-2020-03-09-132811](https://user-images.githubusercontent.com/4048656/76254523-d8d09f00-6209-11ea-94cc-56953afaa9e7.png)

```
java.nio.channels.ClosedChannelException
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
	at hudson.remoting.Channel.close(Channel.java:1450)
	at hudson.remoting.Channel.close(Channel.java:1403)
	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:843)
	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:108)
	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:734)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

ssh is still working, so the machines are up.

**Comment by mmarchini** [comment]
```
root@test-packetnet-ubuntu1604-x64-1:~# service jenkins status
● jenkins.service - Jenkins Slave
   Loaded: loaded (/lib/systemd/system/jenkins.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-02-06 14:23:25 UTC; 1 months 1 days ago
 Main PID: 10899 (java)
   CGroup: /system.slice/jenkins.service
           └─10899 /usr/bin/java -Xmx128m -jar /home/iojs/slave.jar -jnlpUrl https://ci.nodejs.org/computer/test-packetnet-ubuntu1604-x64-1/slave-agent.jnlp -secret f680a036f9aa98c1cdfb15b8cd0e56c17ca0da8d9f8a68c796f2a8fc0c9e3335

Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at hudson.remoting.UserRequest.perform(UserRequest.java:212)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at hudson.remoting.UserRequest.perform(UserRequest.java:54)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at hudson.remoting.Request$2.run(Request.java:369)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]:         at java.lang.Thread.run(Thread.java:748)
Mar 04 16:00:07 test-packetnet-ubuntu1604-x64-1 java[10899]: Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by mmarchini** [comment]
Restored both workers by restarting jenkins with `service jenkins restart`.

Looks like systemd config for jenkins is misconfigured? Since the daemon didn't restart after the OOM.

**Comment by mmarchini** [comment]
I'll close this issue since CI is working now, but we might want to look into making sure Jenkins restarts if the process crashes.
