### ISSUE TITLE
`test-softlayer-debian9-x64-1` filesystem is read-only, leading to failing tests

### ISSUE THREAD

**Issue by mmarchini** [nodejs/build#2230]
```
09:57:53  > git config remote.origin.url git@github.com:nodejs/node.git # timeout=10
09:57:53 ERROR: Error fetching remote repo 'origin'
09:57:53 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
09:57:53 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
09:57:53 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
09:57:53 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
09:57:53 	at hudson.scm.SCM.checkout(SCM.java:505)
09:57:53 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1205)
09:57:53 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
09:57:53 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:57:53 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
09:57:53 	at hudson.model.Run.execute(Run.java:1853)
09:57:53 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
09:57:53 	at hudson.model.ResourceController.execute(ResourceController.java:97)
09:57:53 	at hudson.model.Executor.run(Executor.java:427)
09:57:53 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url git@github.com:nodejs/node.git" returned status code 255:
09:57:53 stdout: 
09:57:53 stderr: error: could not lock config file .git/config: Read-only file system
09:57:53 
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2360)
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2356)
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1916)
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1928)
09:57:53 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.setRemoteUrl(CliGitAPIImpl.java:1542)
09:57:53 	at hudson.plugins.git.GitAPI.setRemoteUrl(GitAPI.java:160)
09:57:53 	at sun.reflect.GeneratedMethodAccessor434.invoke(Unknown Source)
09:57:53 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:57:53 	at java.lang.reflect.Method.invoke(Method.java:498)
09:57:53 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
09:57:53 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
09:57:53 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
09:57:53 	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
09:57:53 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
09:57:53 	at hudson.remoting.Request$2.run(Request.java:369)
09:57:53 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
09:57:53 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09:57:53 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
09:57:53 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
09:57:53 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
09:57:53 	at java.lang.Thread.run(Thread.java:748)
09:57:53 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 5b.96.3ca9.ip4.static.sl-reverse.com/169.60.150.91:39058
09:57:53 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
09:57:53 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
09:57:53 		at hudson.remoting.Channel.call(Channel.java:955)
09:57:53 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
09:57:53 		at com.sun.proxy.$Proxy91.setRemoteUrl(Unknown Source)
09:57:53 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.setRemoteUrl(RemoteGitImpl.java:299)
09:57:53 		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:897)
09:57:53 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
09:57:53 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
09:57:53 		at hudson.scm.SCM.checkout(SCM.java:505)
09:57:53 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1205)
09:57:53 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
09:57:53 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
09:57:53 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
09:57:53 		at hudson.model.Run.execute(Run.java:1853)
09:57:53 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
09:57:53 		at hudson.model.ResourceController.execute(ResourceController.java:97)
09:57:53 		at hudson.model.Executor.run(Executor.java:427)
09:57:53 ERROR: Error fetching remote repo 'origin'
```

**Comment by mmarchini** [comment]
I tried a `e2fsck -y /dev/xvda2` as per https://github.com/nodejs/build/issues/876, but the problem persisted, so I rebooted the instance.

**Comment by rvagg** [comment]
reinstalled OS from scratch and re-ran ansible on it
building now: https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian9-64/33558/
