### ISSUE TITLE
https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-1/ is down, investigating

### ISSUE THREAD

**Issue by sam-github** [nodejs/build#2266]
Its looping with
```
Apr 06 20:51:30 test-osuosl-centos7-ppc64--le-1 java[21827]: Failed to obtain https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-1/slave-agent.jnlp?encrypt=true
Apr 06 20:51:30 test-osuosl-centos7-ppc64--le-1 java[21827]: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
Apr 06 20:51:30 test-osuosl-centos7-ppc64--le-1 java[21827]: at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:701)
Apr 06 20:51:30 test-osuosl-centos7-ppc64--le-1 java[21827]: at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:567)
```

**Comment by sam-github** [comment]
Hm. Reloaded the unit file and waited a while, and it started connecting again.
