### ISSUE TITLE
 release-nearform-macos10.15-x64-1 permission denied

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/build#2369]
https://ci-release.nodejs.org/job/iojs+release/nodes=osx1015-release-tar/6142/console

```
12:08:28 ERROR: Error fetching remote repo 'origin'
12:08:28 hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node.git
12:08:28 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
12:08:28 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
12:08:28 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
12:08:28 	at hudson.scm.SCM.checkout(SCM.java:505)
12:08:28 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
12:08:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
12:08:28 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:08:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
12:08:28 	at hudson.model.Run.execute(Run.java:1856)
12:08:28 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:08:28 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:08:28 	at hudson.model.Executor.run(Executor.java:428)
12:08:28 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/nodejs/node.git" returned status code 255:
12:08:28 stdout: 
12:08:28 stderr: error: could not lock config file .git/config: Permission denied
12:08:28 
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2360)
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2356)
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1916)
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1928)
12:08:28 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.setRemoteUrl(CliGitAPIImpl.java:1542)
12:08:28 	at hudson.plugins.git.GitAPI.setRemoteUrl(GitAPI.java:160)
12:08:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:08:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:08:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:08:28 	at java.lang.reflect.Method.invoke(Method.java:498)
12:08:28 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:929)
12:08:28 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:903)
12:08:28 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:855)
12:08:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
12:08:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
12:08:28 	at hudson.remoting.Request$2.run(Request.java:369)
12:08:28 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
12:08:28 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:08:28 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
12:08:28 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
12:08:28 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:97)
12:08:28 	at java.lang.Thread.run(Thread.java:748)
12:08:28 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ip-83-147-191-69.broadband.digiweb.ie/83.147.191.69:53618
12:08:28 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
12:08:28 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
12:08:28 		at hudson.remoting.Channel.call(Channel.java:998)
12:08:28 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
12:08:28 		at com.sun.proxy.$Proxy85.setRemoteUrl(Unknown Source)
12:08:28 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.setRemoteUrl(RemoteGitImpl.java:299)
12:08:28 		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:897)
12:08:28 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
12:08:28 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
12:08:28 		at hudson.scm.SCM.checkout(SCM.java:505)
12:08:28 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
12:08:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
12:08:28 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
12:08:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
12:08:28 		at hudson.model.Run.execute(Run.java:1856)
12:08:28 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
12:08:28 		at hudson.model.ResourceController.execute(ResourceController.java:97)
12:08:28 		at hudson.model.Executor.run(Executor.java:428)
12:08:28 ERROR: Error fetching remote repo 'origin'
```

**Comment by AshCripps** [comment]
This arised after I restarted the agent which had been down since 9 jun! do we install monit on macs as part of ansible for auto restart of the agents?

**Comment by rvagg** [comment]
I don't think monit is the right solution for macos. I used to install a launcher profile on macos to let the system handle restarts but I don't see any evidence of that in Ansible now (this was pre-ansible for macos when I managed it all manually). There's an XML config you load into the system that auto-starts it on boot but will also auto-restart it when it dies if you set the right property in it.

**Comment by AshCripps** [comment]
Something definitey go awry in the ansible scripts that machine doesnt have jenkins in launchctl, it used a start.sh which calls java directly:

```sh
java -Xmx128m \
    -jar /Users/iojs/slave.jar -secret REDACTED \
    -jnlpUrl https://ci-release.nodejs.org/computer/release-nearform-macos10.15-x64-1/slave-agent.jnlp
```

**Comment by AshCripps** [comment]
ive cleared up the workspace on the machine to remove the locked files

**Comment by AshCripps** [comment]
hmmm, when I closed my terminal session it broke the connection for the agent again something is really not right with the setup. For now I will run it through the VM itself on the host and hope that connection stays up

**Comment by AshCripps** [comment]
Turns out I forgot to plug my brain in when starting the agent, started it as the wrong user its now working
