### ISSUE TITLE
Read-only filesystem on test-softlayer-debian9-x64-1

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2374]
Build failed on test-softlayer-debian9-x64-1 due to `Read-only file system`.
https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian9-64/35914/console

```
16:39:01  > git config remote.origin.url git@github.com:nodejs/node.git # timeout=10
16:39:01 ERROR: Error fetching remote repo 'origin'
16:39:01 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
16:39:01 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:909)
16:39:01 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
16:39:01 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
16:39:01 	at hudson.scm.SCM.checkout(SCM.java:505)
16:39:01 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
16:39:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
16:39:01 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
16:39:01 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
16:39:01 	at hudson.model.Run.execute(Run.java:1856)
16:39:01 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
16:39:01 	at hudson.model.ResourceController.execute(ResourceController.java:97)
16:39:01 	at hudson.model.Executor.run(Executor.java:428)
16:39:01 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url git@github.com:nodejs/node.git" returned status code 255:
16:39:01 stdout: 
16:39:01 stderr: error: could not lock config file .git/config: Read-only file system
16:39:01 
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2360)
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2356)
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1916)
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1928)
16:39:01 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.setRemoteUrl(CliGitAPIImpl.java:1542)
16:39:01 	at hudson.plugins.git.GitAPI.setRemoteUrl(GitAPI.java:160)
16:39:01 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:39:01 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:39:01 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:39:01 	at java.lang.reflect.Method.invoke(Method.java:498)
16:39:01 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:931)
16:39:01 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:905)
16:39:01 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:857)
16:39:01 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
16:39:01 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
16:39:01 	at hudson.remoting.Request$2.run(Request.java:369)
16:39:01 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
16:39:01 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:39:01 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:39:01 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:39:01 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
16:39:01 	at java.lang.Thread.run(Thread.java:748)
16:39:01 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 5b.96.3ca9.ip4.static.sl-reverse.com/169.60.150.91:46912
16:39:01 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1788)
16:39:01 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
16:39:01 		at hudson.remoting.Channel.call(Channel.java:998)
16:39:01 		at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
16:39:01 		at com.sun.proxy.$Proxy94.setRemoteUrl(Unknown Source)
16:39:01 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl.setRemoteUrl(RemoteGitImpl.java:299)
16:39:01 		at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:897)
16:39:01 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1131)
16:39:01 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
16:39:01 		at hudson.scm.SCM.checkout(SCM.java:505)
16:39:01 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1206)
16:39:01 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
16:39:01 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
16:39:01 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
16:39:01 		at hudson.model.Run.execute(Run.java:1856)
16:39:01 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
16:39:01 		at hudson.model.ResourceController.execute(ResourceController.java:97)
16:39:01 		at hudson.model.Executor.run(Executor.java:428)
```

**Comment by AshCripps** [comment]
https://github.com/nodejs/build/issues/2360 this was only rebuilt recently

**Comment by richardlau** [comment]
I've marked test-softlayer-debian9-x64-1 offline in Jenkins for now.

**Comment by rvagg** [comment]
ouch, I guess it needs to be discarded and reprovisioned, I'll try and get to that soon

**Comment by rvagg** [comment]
Reprovisioned with entirely new machine, it's back in the pool now.

@mhdawson can you cancel/delete the old one please (I don't have access for that)? https://cloud.ibm.com/gen1/infrastructure/virtual-server/50051947/details#main - or in the list of machines, it's the one named test-softlayer-debian9-x64-1 that's currently powered off.

**Comment by mhdawson** [comment]
Done
