### ISSUE TITLE
macos failing to build in CI

### ISSUE THREAD

**Issue by Trott** [nodejs/build#2392]
Keep getting the same Java exception but at different points in the build.

<details>

```
18:36:02 FATAL: command execution failed
18:36:02 java.nio.channels.ClosedChannelException
18:36:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
18:36:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
18:36:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
18:36:02 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
18:36:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
18:36:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
18:36:02 	at hudson.remoting.Channel.close(Channel.java:1493)
18:36:02 	at hudson.remoting.Channel.close(Channel.java:1446)
18:36:02 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:872)
18:36:02 	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:113)
18:36:02 	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:763)
18:36:02 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
18:36:02 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
18:36:02 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:36:02 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:36:02 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:36:02 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:36:02 	at java.lang.Thread.run(Thread.java:748)
18:36:02 Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from 199.7.167.100/199.7.167.100:7629' is disconnected.
18:36:02 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:216)
18:36:02 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
18:36:02 	at com.sun.proxy.$Proxy96.isAlive(Unknown Source)
18:36:02 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1147)
18:36:02 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1139)
18:36:02 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
18:36:02 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
18:36:02 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
18:36:02 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
18:36:02 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
18:36:02 	at hudson.model.Build$BuildExecution.build(Build.java:206)
18:36:02 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
18:36:02 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
18:36:02 	at hudson.model.Run.execute(Run.java:1880)
18:36:02 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
18:36:02 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:36:02 	at hudson.model.Executor.run(Executor.java:428)
18:36:02 FATAL: Unable to delete script file /var/folders/kn/6gbh6l053wl4qw5s1b1nrm5r0000gp/T/jenkins3650138163132629910.sh
18:36:02 java.nio.channels.ClosedChannelException
18:36:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
18:36:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
18:36:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:816)
18:36:02 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
18:36:02 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:784)
18:36:02 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
18:36:02 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
18:36:02 	at hudson.remoting.Channel.close(Channel.java:1493)
18:36:02 	at hudson.remoting.Channel.close(Channel.java:1446)
18:36:02 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:872)
18:36:02 	at hudson.slaves.SlaveComputer.access$100(SlaveComputer.java:113)
18:36:02 	at hudson.slaves.SlaveComputer$2.run(SlaveComputer.java:763)
18:36:02 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
18:36:02 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
18:36:02 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
18:36:02 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
18:36:02 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:36:02 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:36:02 	at java.lang.Thread.run(Thread.java:748)
18:36:02 Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@750f169f:JNLP4-connect connection from 199.7.167.100/199.7.167.100:7629": Remote call on JNLP4-connect connection from 199.7.167.100/199.7.167.100:7629 failed. The channel is closing down or has closed down
18:36:02 	at hudson.remoting.Channel.call(Channel.java:991)
18:36:02 	at hudson.FilePath.act(FilePath.java:1069)
18:36:02 	at hudson.FilePath.act(FilePath.java:1058)
18:36:02 	at hudson.FilePath.delete(FilePath.java:1543)
18:36:02 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:123)
18:36:02 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
18:36:02 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
18:36:02 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
18:36:02 	at hudson.model.Build$BuildExecution.build(Build.java:206)
18:36:02 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
18:36:02 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
18:36:02 	at hudson.model.Run.execute(Run.java:1880)
18:36:02 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
18:36:02 	at hudson.model.ResourceController.execute(ResourceController.java:97)
18:36:02 	at hudson.model.Executor.run(Executor.java:428)
```

</details>

Examples:

https://ci.nodejs.org/job/node-test-commit-osx/35425/
https://ci.nodejs.org/job/node-test-commit-osx/35424/
https://ci.nodejs.org/job/node-test-commit-osx/35423/
https://ci.nodejs.org/job/node-test-commit-osx/35422/
https://ci.nodejs.org/job/node-test-commit-osx/35421/

**Comment by Trott** [comment]
And now they're working again. 
¯\\_(ツ)_/¯
