### ISSUE TITLE
junit encoding configuration incorrect?

### ISSUE THREAD

**Issue by vtjnash** [nodejs/build#2404]
It appears that tap2junit is trying to treat the utf-8 log file as ascii:

https://ci.nodejs.org/job/node-test-commit-freebsd/34807/nodes=freebsd11-x64/consoleText (can someone save that log file, so it doesn't get lost to time)

Failure backtrace:
```
+ tap2junit -i test.tap -o out/junit/test.xml
Traceback (most recent call last):
  File "/usr/local/bin/tap2junit", line 11, in <module>
    load_entry_point('tap2junit==0.1.5', 'console_scripts', 'tap2junit')()
  File "/usr/local/lib/python2.7/site-packages/tap2junit/__main__.py", line 51, in main
    convert(args.input, args.output)
  File "/usr/local/lib/python2.7/site-packages/tap2junit/__main__.py", line 43, in convert
    TestSuite.to_file(out_file, [result], prettyprint=True, encoding='utf-8')
  File "/usr/local/lib/python2.7/site-packages/junit_xml/__init__.py", line 291, in to_file
    file_descriptor.write(xml_string)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc1' in position 183206: ordinal not in range(128)
POST BUILD TASK : FAILURE
END OF POST BUILD TASK : 0
```

probably caused by the presence of this test failure?
```
not ok 2370 parallel/test-tls-peer-certificate-encoding
  ---
  duration_ms: 120.98
  severity: fail
  exitcode: -15
  stack: |-
    timeout
    {
      subject: [Object: null prototype] {
        C: 'HU',
        L: 'Budapest',
        O: 'Tresorit',
        CN: 'Ádám Lippai',
        emailAddress: 'adam.lippai@tresorit.com'
      },
      issuer: [Object: null prototype] {
        C: 'US',
        ST: 'CA',
        L: 'SF',
        O: 'Joyent',
        OU: 'Node.js',
        CN: 'ca2',
        emailAddress: 'ry@tinyclouds.org'
      },
      modulus: 'A4B2984A4A46C4E1A09AEBCAF6A3B8F6C566F16D63FE6E3006C165984309DA710EA9E6D96168DD7479B0C098F55A90BA3CC713C45CCA96171094D805A0D16B5DE9382A210B4830D5D0CFA7227F951FC68DE586EB3E74B86C7E5CFEC93A450F9BD112F9F4910F5C7BE8D58D5CE1F1B2B9A9FA5A365688A9073AE16A492907BEF1',
      bits: 1024,
      exponent: '0x10001',
      pubkey: <Buffer 30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 a4 b2 98 4a 4a 46 c4 e1 a0 9a eb ca f6 a3 b8 f6 c5 66 f1 6d 63 ... 112 more bytes>,
      valid_from: 'Nov 16 18:42:21 2018 GMT',
      valid_to: 'Aug 30 18:42:21 2292 GMT',
      fingerprint: '68:5C:18:C2:40:8E:37:54:D0:1F:E1:9A:C2:A1:91:41:0A:E2:BC:B2',
      fingerprint256: '8D:20:0E:7E:88:6D:6D:AC:90:63:50:DC:6C:BB:FA:32:CA:13:E7:06:59:E1:AC:72:AC:F9:87:79:42:7D:CD:C2',
      ext_key_usage: [ '1.3.6.1.5.5.7.3.2' ],
      serialNumber: '91F006636069F29D',
      raw: <Buffer 30 82 02 85 30 82 01 ee a0 03 02 01 02 02 09 00 91 f0 06 63 60 69 f2 9d 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 7a 31 0b 30 09 06 03 55 04 06 ... 599 more bytes>
    }
  ...
```

**Comment by richardlau** [comment]
tap2junit source is https://github.com/nodejs/tap2junit

**Comment by vtjnash** [comment]
Bad bot. Moved to https://github.com/nodejs/tap2junit/issues/28

**Comment by vtjnash** [comment]
>> /usr/local/lib/python2.7
>
> Why are you running on Python 2 which has been dead for more than 500 daze?
python3 tap2junit -i test.tap -o out/junit/test.xml

Also, seems like stalebot is broken. Bad bot.

**Comment by richardlau** [comment]
I checked the two freebsd 11 hosts and they should be using Python 3.8 for tap2junit:
```
$ head `which tap2junit`
#!/usr/local/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from tap2junit.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
$
```
This probably changed from Python 2 when we did the big push to get Python 3 installed on all the CI hosts for Node.js 16. I don't know without further investigation whether changing the version of Python used to run tap2junit alone is enough to avoid the encoding issue.

**Comment by vtjnash** [comment]
It looks like a few bots are still running Python2: https://ci.nodejs.org/job/node-test-commit-linux/42049/nodes=debian10-x64/. The other bots which failed the same test didn't crash, so the switch to Python 3 seems to fix this.
