### ISSUE TITLE
mismatched version of python-junit-xml and tap2junit?

### ISSUE THREAD

**Issue by vtjnash** [nodejs/build#2405]
This error is nonsensical to me, unless the version of python-junit-xml being used is pretty old (pre-Oct, 2016), but I'm just reporting what I saw on CI run https://ci.nodejs.org/job/node-test-commit-linux/36408/nodes=centos7-64-gcc8/consoleText
```
+ tap2junit -i test.tap -o out/junit/test.xml
Traceback (most recent call last):
  File "/usr/bin/tap2junit", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/tap2junit/__main__.py", line 51, in main
    convert(args.input, args.output)
  File "/usr/lib/python2.7/site-packages/tap2junit/__main__.py", line 42, in convert
    result = parse(input_file, data)
  File "/usr/lib/python2.7/site-packages/tap2junit/__main__.py", line 35, in parse
    junit_tests = [map_yaml_to_junit(t) for t in tap_parser.tests]
  File "/usr/lib/python2.7/site-packages/tap2junit/__main__.py", line 27, in map_yaml_to_junit
    t.add_failure_info(error_message, err_output, err_code)
TypeError: add_failure_info() takes at most 3 arguments (4 given)
POST BUILD TASK : FAILURE
```

**Comment by vtjnash** [comment]
bad bot

**Comment by vtjnash** [comment]
Your bot is very naughty and closing active issues.

**Comment by targos** [comment]
@nodejs/build A comment was made but the bot still closed the issue.

**Comment by phillipj** [comment]
Isn't that the expected behaviour, seeing the bot is configured to _close_ issues after having labelled it with `stale` and no activity happens for 30 days? https://github.com/nodejs/build/blob/1a77fd78ddd10cea455100f6e0920cf49507d609/.github/workflows/stale.yml#L17

..that's at least how I interpret that configuration and the stale action' v1 source code: [actions/stale `./src/main.ts`](https://github.com/actions/stale/blob/0649bd81195b7ac109fbf9dde113af7e58a78b8e/src/main.ts#L81-L83)

**Comment by AshCripps** [comment]
so looking into it the feature to unstale upon updating wasnt added untill around v3 https://github.com/actions/stale/pull/58 and we run v1 - will open a PR to update the action

**Comment by AshCripps** [comment]
PR here: https://github.com/nodejs/build/pull/2699

**Comment by vtjnash** [comment]
I'm told (https://github.com/nodejs/build/issues/2404) that the bots are not supposed to be using Python 2.7 anymore, so this issue may only be a configuration issue on a small number of remaining bots.

**Comment by cclauss** [comment]
Is there a todo on this issue or can it be closed?
* https://github.com/nodejs/tap2junit/releases
