### ISSUE TITLE
latest-linker broken?

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2432]
I ran into the following problem when releasing Node.js `v14.10.1`:

```
bash-4.2$ ./tools/release.sh 
# Selecting GPG key ...
<redacted>

# Checking for releases ...
Found the following releases / builds ready to promote:

 * v14.10.1: aix-ppc64 headers linux-arm64 linux-armv7l linux-ppc64le linux-s390x linux-x64 osx-x64-pkg osx-x64-tar src win-x64-7z win-x64-msi win-x64-zip win-x86-7z win-x86-msi win-x86-zip

Promote v14.10.1 files (aix-ppc64 headers linux-arm64 linux-armv7l linux-ppc64le linux-s390x linux-x64 osx-x64-pkg osx-x64-tar src win-x64-7z win-x64-msi win-x64-zip win-x86-7z win-x86-msi win-x86-zip)? [y/n] y

# Promoting v14.10.1...
... Checking assets
... Expecting a total of 37 assets for v14.x
... 37 assets waiting in staging
... 0 assets already promoted
 ✓  Complete set of expected assets in place for v14.x
Are you sure you want to promote the v14.10.1 assets? [y/n] y
Promoting v14.10.1/docs...
Promoting v14.10.1/node-v14.10.1-aix-ppc64.tar.gz...
Promoting v14.10.1/node-v14.10.1-darwin-x64.tar.gz...
Promoting v14.10.1/node-v14.10.1-darwin-x64.tar.xz...
Promoting v14.10.1/node-v14.10.1-headers.tar.gz...
Promoting v14.10.1/node-v14.10.1-headers.tar.xz...
Promoting v14.10.1/node-v14.10.1-linux-arm64.tar.gz...
Promoting v14.10.1/node-v14.10.1-linux-arm64.tar.xz...
Promoting v14.10.1/node-v14.10.1-linux-armv7l.tar.gz...
Promoting v14.10.1/node-v14.10.1-linux-armv7l.tar.xz...
Promoting v14.10.1/node-v14.10.1-linux-ppc64le.tar.gz...
Promoting v14.10.1/node-v14.10.1-linux-ppc64le.tar.xz...
Promoting v14.10.1/node-v14.10.1-linux-s390x.tar.gz...
Promoting v14.10.1/node-v14.10.1-linux-s390x.tar.xz...
Promoting v14.10.1/node-v14.10.1-linux-x64.tar.gz...
Promoting v14.10.1/node-v14.10.1-linux-x64.tar.xz...
Promoting v14.10.1/node-v14.10.1.pkg...
Promoting v14.10.1/node-v14.10.1.tar.gz...
Promoting v14.10.1/node-v14.10.1.tar.xz...
Promoting v14.10.1/node-v14.10.1-win-x64.7z...
Promoting v14.10.1/node-v14.10.1-win-x64.zip...
Promoting v14.10.1/node-v14.10.1-win-x86.7z...
Promoting v14.10.1/node-v14.10.1-win-x86.zip...
Promoting v14.10.1/node-v14.10.1-x64.msi...
Promoting v14.10.1/node-v14.10.1-x86.msi...
Promoting v14.10.1/win-x64...
Promoting v14.10.1/win-x86...
/usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:76
    throw new Error('Could not find latest.tar.gz')
    ^

Error: Could not find latest.tar.gz
    at afterMap (/usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:76:11)
    at handler (/usr/lib/node_modules/nodejs-latest-linker/node_modules/map-async/index.js:36:29)
    at /usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:35:44
    at FSReqCallback.oncomplete (fs.js:169:5)
bash-4.2$
```

This could be related to the new version of https://github.com/nodejs/nodejs-latest-linker which came out yesterday and contains https://github.com/nodejs/nodejs-latest-linker/pull/4. If I ssh onto the server it looks like the symlinks still point to `v14.10.0`:
```
$ ls -al
total 502372
drwxr-xr-x 529 dist dist    20480 Sep 10 14:56 .
drwxrwxr-x  12 root root     4096 Apr 23  2018 ..
-rw-rw-r--   1 dist dist   181292 Sep 10 15:05 index.json
-rw-rw-r--   1 dist dist   111155 Sep 10 15:05 index.tab
lrwxrwxrwx   1 dist dist       34 Sep  8 15:43 latest -> /home/dist/nodejs/release/v14.10.0
..
lrwxrwxrwx   1 dist dist       34 Sep  8 15:43 latest-v14.x -> /home/dist/nodejs/release/v14.10.0
```

**Comment by richardlau** [comment]
Read through scripts in https://github.com/nodejs/build/tree/master/ansible/www-standalone/tools/promote and manually ran the linker but got the same failure:

```
$ nodejs-latest-linker /home/dist/nodejs/release/ /home/dist/nodejs/docs/
/usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:76
    throw new Error('Could not find latest.tar.gz')
    ^

Error: Could not find latest.tar.gz
    at afterMap (/usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:76:11)
    at handler (/usr/lib/node_modules/nodejs-latest-linker/node_modules/map-async/index.js:36:29)
    at /usr/lib/node_modules/nodejs-latest-linker/latest-linker.js:35:44
    at FSReqCallback.oncomplete (fs.js:169:5)
```

**Comment by richardlau** [comment]
FWIW The PR for the release was https://github.com/nodejs/node/pull/35137 and the release build done in https://ci-release.nodejs.org/job/iojs+release/6304/ (everything passed so I don't believe any assets are missing).

I've considered running `npx nodejs-latest-linker@1.2.0 /home/dist/nodejs/release/ /home/dist/nodejs/docs/` to run the previous version of the tool but am erring on the side of caution here and have not.

**Comment by richardlau** [comment]
https://github.com/nodejs/nodejs-latest-linker/pull/6 should fix `nodejs-latest-linker`.

**Comment by rvagg** [comment]
thanks for the fix, have deployed and re-run it:

```
lrwxrwxrwx   1 dist dist       34 Sep 11 01:42 latest-v14.x -> /home/dist/nodejs/release/v14.10.1
lrwxrwxrwx   1 dist dist       53 Sep 11 01:42 node-latest.tar.gz -> /home/dist/nodejs/release/latest/node-v14.10.1.tar.gz
lrwxrwxrwx   1 dist dist       34 Sep 11 01:42 latest -> /home/dist/nodejs/release/v14.10.1
```

**Comment by rvagg** [comment]
have queued a cdn purge, https://nodejs.org/dist/latest-v14.x/docs/api/ still has 14.10.0 but should switch to 14.10.1 soon, will monitor
