### ISSUE TITLE
OSUOSL ppcle hosts down

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2489]
Reported by @Trott via Slack/IRC.

> trott  12:13 PM
It looks like the OSU OSL machines aren't working, so we have no plinux hosts. See https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-2/ and https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-1/. Or here's a screenshot:
![image](https://user-images.githubusercontent.com/5445507/100551162-eab21080-3276-11eb-997f-16ba16e58d7e.png)
12:14 
As a result, we have a backlog of 13 running plinux jobs right now, the oldest of which has been waiting 1 day and 4 hours for a host....
12:14 
https://ci.nodejs.org/job/node-test-commit-plinux/36253/

**Comment by richardlau** [comment]
I've restarted the agents on both of the test machines. 

FWIW from the logs it looks like some sort of network issue on 27 November. 
```
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: Failed to obtain https://ci.nodejs.org/computer/test-osuosl-centos7-ppc64_le-2/slave-agent.jnlp?encrypt=true
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: java.net.ConnectException: Connection timed out (Connection timed out)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.PlainSocketImpl.socketConnect(Native Method)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at java.net.Socket.connect(Socket.java:607)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:681)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:513)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at hudson.remoting.Launcher.run(Launcher.java:347)
Nov 27 21:40:30 test-osuosl-centos7-ppc64--le-2 java[18294]: at hudson.remoting.Launcher.main(Launcher.java:298)
```

The agent restart appears to have connected successfully.
