### ISSUE TITLE
Official Windows arm64 binaries

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/build#2540]
@nodejs/releasers It's tier2 build now. Maybe make it in the official release process ?

_Originally posted by @gengjiawen in https://github.com/nodejs/node/issues/36658#issuecomment-767246793_

**Comment by rvagg** [comment]
it does say "Tier 2 (compiling) / Experimental (running)", it's got two different tiers for good reason

**Comment by gengjiawen** [comment]
> it does say "Tier 2 (compiling) / Experimental (running)", it's got two different tiers for good reason

Make it more available will get it more tested. Some of our user just want to use it. Building it from source will be a heavy task for most Node.js users. I think this will bring more value to the community in the long term.

**Comment by joaocgreis** [comment]
Ref https://github.com/nodejs/build/issues/2450 and https://github.com/nodejs/node/issues/25998

There are some releases in https://unofficial-builds.nodejs.org/ . Since it's Windows and can't be built from the docker system that builds for other platforms, I have to manually trigger and publish the builds, so not all versions are available.

To be able to bring Windows ARM64 fully into tier 2, we'll need a better solution for testing. We're essentially waiting for Windows ARM64 machines to become available in Azure.

**Comment by pb5050** [comment]
@joaocgreis  @gengjiawen  you guys should reach out to Microsoft engineers ive seen  where people have on occasion and the engineers actually chiming in  randomly on git hub, and the outcome 80% was very favorable and seemed like it was a good idea they did.

**Comment by atishay** [comment]
@joaocgreis Is it possible to get node 16 unofficial binaries on Windows ARM64. It seems Azure arm64 is still further away.

**Comment by jasnell** [comment]
While we are waiting on Azure to provide Windows arm64 images, if the project/foundation is willing to provide the Windows Arm64 hardware, we (Nearform) would be willing to host them alongside the mac minis we currently host so that we can at least have them always available. /cc @mcollina

**Comment by mhdawson** [comment]
@jasnell do you have cost estimates/configs for the hardware.

@joaocgreis I assume if these were added you'd an eye on them, reconnecting jenkins agents, compiler upgrades etc. like you do for other windows systems ?

**Comment by joaocgreis** [comment]
@atishay working on the releases, they should be done shortly. Will post on https://github.com/nodejs/build/issues/2450 when done.

@mhdawson yes I can keep them functional.

We cross-compile for ARM64 from our current workers, so for compilation we have good capacity. It's for running the tests that we need actual ARM64 hardware. For this to be added to node-test-commit unconditionally, running on every PR, we need: 1) enough machines to handle all the work, I'd say at least 4 workers; 2) reliability, to avoid blocking the CI job. Azure would be the perfect solution for this, but Nearform might also work.

**Comment by jasnell** [comment]
Quick update on this... I am talking to a representative from Arm who may be providing us with a loaner Surface Pro X device to host at the nearform HQ alongside the mac minis we currently have. We're getting a follow up call set up for next week to discuss details. Once I settle on this I'll be looking to see if we can get at least one additional machine so we have two there to work with. I know we ultimately will need a few more than that.

**Comment by jasnell** [comment]
@mhdawson ... to answer your question on cost estimate/configs ... a Surface Pro X is likely the best choice. There are other arm64 options out there but the pro x is pretty much rock solid.

![image](https://user-images.githubusercontent.com/439929/118868536-267a7a00-b899-11eb-9a29-a37649cb05f5.png)

**Comment by pb5050** [comment]
they have a cheaper one but yes it is rock solid i love my SPX :D

**Comment by pb5050** [comment]
btw is nodejs 15.8 the last unofficial build? you guys have out rn? 

working flawlessly but i was jw if  (un official builds of the newer ones are out )

**Comment by mhdawson** [comment]
@jasnell from email sounds like you are lining up donations so we don't need to ask Foundation to buy machines at this point right ?

**Comment by jasnell** [comment]
@mhdawson ... It looks like we can get at least one machine from donation (thanks to Arm) but I don't know if we'll be able to get more than that.

**Comment by mhdawson** [comment]
@jasnell let me know when that is settled and then we can go from there. @nodejs/build any comments/concerns about asking the Foundation to fund 1 machine at $2000 US if that is necessary?

**Comment by jasnell** [comment]
> @jasnell let me know when that is settled and then we can go from there.

Will do for sure!

**Comment by jasnell** [comment]
Status update... great conversation with the folks at Arm. What it looks like right now is that we (nearform) should be able to get a surface pro x device on loan from Arm for a period of about one year. Hopefully by then the developer kits and/or Azure support will be available. A single Pro X SQ1 isn't going to be super powerful -- we definitely won't want to build every PR on it -- but it should suffice for running tests. The Node.js test suite takes about 45 minutes to run on my personal Surface Pro X device. We have some legal paperwork to go through before we get the device so it may take at least a few weeks before we can get things set up. I will post updates here as we go.

*Ideally* we would have more than one device available. If the foundation can provide a second device, we are also willing to host that alongside the loaned one from Arm.

**Comment by mhdawson** [comment]
@jasnell so just to confirm you'd like us to ask if the Foundation can fund a second machine ?

**Comment by jasnell** [comment]
Yes, but we might want to wait. A new low cost arm64 developer kit was announced yesterday during msft build that is supposed to be available later this summer.

**Comment by mhdawson** [comment]
@jasnell ok, just let me know if/when you want to make a request.

**Comment by pb5050** [comment]
Just a question  couldnt you install a WOA on a raspberry pie  and use that  for test?

**Comment by dennisameling** [comment]
@mbodomi an unofficial build of 16.2.0 is available for Windows arm64: https://unofficial-builds.nodejs.org/download/release/v16.2.0/

**Comment by james-emerton** [comment]
I'm not familiar with the requirements of build machines for this project, but might it be an option to run the builds inside a VM on an M1 Mac Mini? Macstadium has this hardware available now and I see you're already working with them.

**Comment by rvagg** [comment]
That's not as whacky a suggestion as it might seem since Parallels just announced version 17 that'll run Windows ARM on an M1 https://arstechnica.com/gadgets/2021/08/parallels-desktop-17-is-here-and-ready-to-run-windows-11-on-m1-macs/
But we'd need to do that on our own hardware, probably not something we could stretch MacStadium to do via Orka, and it would take some experimentation.

However, it's probably going to end up being easier to get proper arm64 hardware for Windows as per discussions above, even if that just means parking laptops somewhere and only shipping binaries to unofficial-builds for now but with regularity.

**Comment by jasnell** [comment]
Btw, just as an update... NearForm should be receiving a loaner surface pro x device from Arm that will be set up for the node.js CI. @mcollina will be taking over the oversight of that now that I'm not there anymore. That will at least get us started. We should try to get ahold of a few of the developer kits soon.

**Comment by dennisameling** [comment]
Looks like the Snapdragon development kit is finally available in the Microsoft store for $219: https://www.microsoft.com/en-US/d/ecs-liva-mini-box-qc710-desktop/8z247h1h3skp

Would be great to have official Windows on ARM builds soon as this is also blocking things like a native GitHub Actions runner: for arm64 https://github.com/actions/runner/pull/785

**Comment by ntindle** [comment]
Is this build something you need resources or runners for? If the machine is $250 I may be able to help out.

**Comment by Fossil01** [comment]
Can't this be handled in a CI/CD pipeline? Or a simple ARM virtual machine from AWS for example.

**Comment by mcollina** [comment]
@jasnell nothing arrived yet.

**Comment by jasnell** [comment]
Hmm. Ok, I'll reach out later today to see where we're at on getting the loaned device.

**Comment by dennisameling** [comment]
Hi @jasnell, Happy New Year! May I ask if there's an update on this already? Thanks in advance! 🙏🏼

**Comment by mcollina** [comment]
We have received the two machines from Arm. Who can I loop in an email thread to configure them up?

**Comment by mhdawson** [comment]
@mcollina I'm not sure we already have a challenge in terms of finding people to support the Windows machines. Unless @joaocgreis is willing to take this on I'm not sure what we should do.

**Comment by mhdawson** [comment]
@mcollina, reading above looks like @joaocgreis already said he would take it on, so he's the one to loop in.

**Comment by mcollina** [comment]
I sent a private email to @joaocgreis to coordinate.

**Comment by tidy-dev** [comment]
👋 @joaocgreis Hi! Thank you for manually keeping up with these arm64 builds. It is much appreciated! I am working on the GitHub Desktop team and we are upgrading to [Electron version 16](https://www.electronjs.org/releases/stable?version=16&page=2). It uses node v16.9.1 Was wondering if it would possible to get an arm64 build for that version? 🙏

**Comment by joaocgreis** [comment]
Added the new ARM64 machines to CI. To use them, just run the Windows CI job https://ci.nodejs.org/job/node-test-commit-windows-fanned/ with the checkbox RUN_ARM64_TESTS enabled.

I noticed we might have an issue with test.parallel/test-module-readonly, it's failing in every run: https://ci.nodejs.org/view/All/job/node-test-commit-windows-fanned/46871/

@tidy-dev I released 16.9.1 in https://unofficial-builds.nodejs.org/download/release/v16.9.1/, but wasn't able to test it in CI because of a python issue, so please make sure it runs before using it for anything too official.

**Comment by sergiou87** [comment]
Hi @joaocgreis ! 👋  Another member of the GitHub Desktop team here 😄  we might need to downgrade to Electron 15 now due to a Chromium bug in Electron 16, which means we would require node v16.5.0. Is there any chance to get an arm64 build for node 16.5.0?

Thank you for all your hard work 🙇‍♂️ 🙇‍♂️ 🙇‍♂️

**Comment by tidy-dev** [comment]
@joaocgreis We have actually decided to move to Electron 17 due to a Chromium bug.. This would mean node v16.13.0. Any chance you could do v16.13.0 and v16.5.0 (so we could have the option to fallback to Electron 15)?

**Comment by joaocgreis** [comment]
@sergiou87 @tidy-dev Hi! Published both versions. CI for 16.13.0 running in https://ci.nodejs.org/job/node-test-commit-windows-fanned/47132/ , but I wasn't able to run for 16.5.0 because of the Python issue.

**Comment by dennisameling** [comment]
@joaocgreis is there anything we (the community) can do to help you start releasing official arm64 builds, now that the CI runners are in place? Things like the GitHub Actions runner depend on NodeJS and I'd like to use the [momentum they're having with Apple Silicon](https://github.com/actions/runner/issues/805#issuecomment-1041968059) to also introduce Windows arm64 support 😊 thanks!

**Comment by nsait-linaro** [comment]
Great to see progress on windows/arm64. I have the same question as @dennisameling. What else is missing for official releases?

**Comment by mhdawson** [comment]
@nsait-linaro, in terms of official releases, the project does not have enough Windows collaborators helping to investigate/resolve windows related issues, maintain windows machines for CI (and that is just for the existing variations that are in the CI). From my perspective the biggest thing you can do to help enable additional configurations would be getting involved and helping to resolve that.

**Comment by nsait-linaro** [comment]
Thanks, @mhdawson. Yes, we are happy to collaborate on this.

I wanted to run the CI with `RUN_ARM64_TESTS` to see the status but I don't think I have the permissions on Jenkins to do that. Can someone help with triggering a build with the HEAD?

**Comment by mhdawson** [comment]
@nsait-linaro if you are willing to be involved in an ongoing manner to investigate problems and help in general with Windows I'll ask if we can get you the ok to be able to launch the CI.

**Comment by nsait-linaro** [comment]
@mhdawson Yes, we are happy to get involved.

**Comment by mhdawson** [comment]
I think a few things would make sense

1) We could add you/others who want to get more involved to platform-windows and platform-windows-arm so that you get mentions on windows related issues. Could you send me a list of github id's ?
2) I can propose that we get you access to be able to launch some CI jobs. Are there specific ones that you need at this point?  If you just need to be able to run windows on arm to start we could possibly give you access to a job that does just that
3) There are 90 open issues tagged windows, if you could help on some of those that would be great - https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+windows+label%3Awindows. In particular this one is blocking an upgrade to the latest V8 - https://github.com/nodejs/node/issues/42375

**Comment by hajekj** [comment]
Cross reference from https://github.com/nodejs/node/issues/25998

> I believe obtaining build agents should now be much more easier thanks to Arm-based processors coming to Azure: https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/
>
> If needed I can provide a part of my subscription to host the required VMs.
>
> If you need to get in touch with me regarding this, please reach out at: [jan.hajek@thenetw.org](mailto:jan.hajek@thenetw.org)

**Comment by nsait-linaro** [comment]
That's great @hajekj. We at Linaro also have been trying the Azure VMs and would really nice to get it deployed for node.js CI. Let us know if any help is required.

We have been trying to reproduce CI failures but unfortunately couldn't manage to do it locally. Win/arm64 CI machine also seems to be not running and cannot access old logs.

**Comment by mhdawson** [comment]
admin issue to make addition to platform-windows-arm team visible - https://github.com/nodejs/admin/issues/676.  Will add in a day or so if not objects (and I don't expect any)

**Comment by mhdawson** [comment]
Issue to talk about giving access to start the CI job - https://github.com/nodejs/build/issues/2918.

@nsait-linaro can you confirm that is the right job that I mention in the issue. I ask because I don't see a history of any runs.

**Comment by nsait-linaro** [comment]
> Issue to talk about giving access to start the CI job - #2918.
> 
> @nsait-linaro can you confirm that is the right job that I mention in the issue. I ask because I don't see a history of any runs.

Thanks, @mhdawson. I think https://ci.nodejs.org/job/node-test-commit-windows-fanned/ is the right one.

**Comment by sergiou87** [comment]
Hello! 👋 

Not sure if someone here (@joaocgreis or @nsait-linaro maybe?) can still kick builds of Node for Windows arm64, but we'd need a build of Node v16.14.2 because we're trying to [upgrade GitHub Desktop to Electron v19](https://github.com/desktop/desktop/pull/14813), please.

Thanks in advance 🙇‍♂️ 

Is there an easy way we (the GitHub Desktop team) could create those builds ourselves from that CI job?

**Comment by mhdawson** [comment]
@sergiou87 part of the problem is that for windows the projectg uses a fanned build which is much more complicated than for other platforms. Understanding that/getting it going is going to be a fair amount of work for somebody other than @joaocgreis.

The instructions to build/test on windows are in https://github.com/nodejs/node/blob/main/BUILDING.md.. Following those you should be able to set up your own CI.

We really need more support from Microsoft or somebody else who is knowleadgeble on Windows and has time to help with Windows.  @joaocgreis used to be funded to help with that but I'm not sure if that is the case anymore.

Without that you're hoping that contributors who do most of their development on linux or OSX are going to help out with windows issues.

I've tried to create a simpler test job using the stress job as an example - https://ci.nodejs.org/job/windows-arm-simple/. If by chance that works I can give access to @nsait-linaro to kick it off when needed.

I think we need to fix the fundamental issue though which is people who have time/interest to help investigate/resolve problems on windows in general (both x86 and arm) before we'd want to consider shipping any new windows binaries. The length of time this issue has been open/stalled is a clear illustration of the problem.

**Comment by mhdawson** [comment]
Looks like the arm windows machines at nearform are offline
@matteo who would be the contact to ask about this since you are no longer there ?

![image](https://user-images.githubusercontent.com/9373002/174403965-98934869-57a0-423b-bbd5-bda656cad988.png)

**Comment by nsait-linaro** [comment]
If we need a new machine or any help to setup CI, Linaro should be able to help.

We are also running a downstream CI for node.js and everything seems to be in good shape for release. See [nightly log](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/2503920989
)

We are really interested in supporting node.js for Windows Arm64. Please let us know if you need any help.

**Comment by ShogunPanda** [comment]
@mhdawson I think you meant to tag @mcollina.
Anyway, from now on, me and @RafaelGSS are the best to contact.
I'll forward to our IT support to check.

**Comment by ShogunPanda** [comment]
@mhdawson 

I've checked with Eamonn, IT Administrator @ NearForm.
The machines seems to be up and running. Can you try again?

Also, for the future, you can ping NearForm directly by emailing services@nearform.com without waiting for me or Rafael to be available.

**Comment by mhdawson** [comment]
Machines are now up, but unfortuately they don't seem to be configured to compile/build. They seem to fail because the right version of python is not available.- https://ci.nodejs.org/view/All/job/windows-arm-simple/7/nodes=win10-vs2019-arm64/console.

I think the build for the fanned build, does a cross compile which may be why they were working.

**Comment by mhdawson** [comment]
> We are really interested in supporting node.js for Windows Arm64. Please let us know if you need any help.

What I think we'd be looking for on an ongoing basis would be:

1) A  commitment to managed the arm windows machines, investigate when they are offline or having problems and resolving problems when necessary
2) A commitment to generate the artifacts processes/documentation needed to rebuild/reconfigure machines. For most of our machines we use Ansible and I think @joaocgreis may have gotten that working for windows as well.  Our goal is an easy way to go from a new machine to one that is configured as needed for the builds.
3) A commitment to track the CI and when there are windows on arm failures/flaky tests to investigate and help get them working again.

@nsait-linaro, if there are resources at linaro that can commit to this, then I can talk to the build WG about the path to getting those resources the level of access needed to do that. We do need a certain level of trust in those who have access to the CI but I'm thinking that is something we could work through.  

Since it would be effectively joining the build wg to help manage the windows on arm machines it might make sense to join the next build wg meeting - https://github.com/nodejs/build/issues/2970. If we get enough attendess we might be able to discuss there.

**Comment by sxa** [comment]
@ShogunPanda Can we get a later version of Python installed on the machines? Ideally we'd be able to get to a stage where it's possible to build Node.js on them directly, and at the moment the default Python 2.7 is not suitable for that.

**Comment by sxa** [comment]
> We are also running a downstream CI for node.js and everything seems to be in good shape for release. See [nightly log](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/2503920989)

@nsait-linaro Looks like there are a few test suite failures in there - have they been diagnosed/understood?

**Comment by nsait-linaro** [comment]
> > We are also running a downstream CI for node.js and everything seems to be in good shape for release. See [nightly log](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/2503920989)
> 
> @nsait-linaro Looks like there are a few test suite failures in there - have they been diagnosed/understood?

I think it could be due to our CI infrastructure or environment. We run the same tests on x64 and arm64 and compare the results to spot any regressions and those tests have been failing on both platforms.  @pbo-linaro manages the build system - he might know more about it.

**Comment by ShogunPanda** [comment]
@sxa No idea, I'm sorry. IT will be able to address it.

**Comment by mcollina** [comment]
NearForm is only hosting those machines. @nodejs/build is responsible for the CI jobs.

**Comment by nsait-linaro** [comment]
> > @sxa No idea, I'm sorry. IT will be able to address it.
> 
> Apologies - that was supposed to be targetted at @nsait-linaro as a question regarding their CI :-) @nsait-linaro Is your CI buliding Node natively on the aarch64 host, or cross compiling from a Windows/x64 one before testing on aarch64?

Our current setup is native compilation with VS 2019

**Comment by pbo-linaro** [comment]
Indeed, we observe some failures from time to time (even on x64). Thus, we compare list of failing tests between x64 and arm64 to detect failures specific to a given platform.

**Comment by mhdawson** [comment]
> I presume this is a new job?

Yes, I tried to quickly create a simpler job starting with what was in the stress test job

> I've hijacked your job (Commented with SXA and fixed the path so it finds Python 3.10 instead) 

Sounds good, if you can progress that's great.  I think the lack of compiler is probably because other jobs cross compile.

**Comment by sxa** [comment]
To follow up on conversations elsewhere - I've managed to get the code for Node 19 to build natively on the `-2` machine (logging in and running it manually) so the machine is definitely in a state where it can build - the only change I had to make was to put the Python310 directory in the path first otherwise the code, as you'd expect, choked on trying to use python 2.7. I couldn't replicate the inability to find the compiler that's showing in that job.

I got three test case failures on my first run with it - one in `parallel/test-fs-stat`, `parallel/test-module-readonly` and I think the other was a timeout in one of the `test-wasi` suite which I know the Linaro team have had failures in too.

Hopefully this is a good start to being able to build and test natively on the ARM64 system and get this into a good state where we can make this into a better supported platform. Thanks to the Linaro team for your hints and tips and keenness to progress this :-)

**Comment by sxa** [comment]
https://ci.nodejs.org/job/windows-arm-simple/nodes=win10-vs2019-arm64 now successfully builds on both of the WIndows/arm systems and is able to run tests (Adjusting the path in the job made it find the compiler) so our machines are adequate for natively compiling on the arm machines via jenkins.

Three test case failures showing in job 18:
```
11:22:29 not ok 480 parallel/test-child-process-stdio-overlapped
11:22:29   ---
11:22:29   duration_ms: 0.307
11:22:29   severity: fail
11:22:29   exitcode: 1
11:22:29   stack: |-
11:22:29     node:events:515
11:22:29           throw er; // Unhandled 'error' event
11:22:29           ^
11:22:29     
11:22:29     Error: spawn c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\out\Release\overlapped-checker.exe ENOENT
11:22:29         at ChildProcess._handle.onexit (node:internal/child_process:283:19)
11:22:29         at onErrorNT (node:internal/child_process:476:16)
11:22:29         at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
11:22:29     Emitted 'error' event on ChildProcess instance at:
11:22:29         at ChildProcess._handle.onexit (node:internal/child_process:289:12)
11:22:29         at onErrorNT (node:internal/child_process:476:16)
11:22:29         at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
11:22:29       errno: -4058,
11:22:29       code: 'ENOENT',
11:22:29       syscall: 'spawn c:\\workspace\\windows-arm-simple\\nodes\\win10-vs2019-arm64\\out\\Release\\overlapped-checker.exe',
11:22:29       path: 'c:\\workspace\\windows-arm-simple\\nodes\\win10-vs2019-arm64\\out\\Release\\overlapped-checker.exe',
11:22:29       spawnargs: []
11:22:29     }
11:22:29     
11:22:29     Node.js v19.0.0-pre
```
```

11:25:04 not ok 1875 parallel/test-module-readonly
11:25:04   ---
11:25:04   duration_ms: 1.564
11:25:04   severity: fail
11:25:04   exitcode: 1
11:25:04   stack: |-
11:25:04     node:assert:992
11:25:04         throw newErr;
11:25:04         ^
11:25:04     
11:25:04     AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Cannot find module '..\.tmp.1874\readOnlyMod'
11:25:04     Require stack:
11:25:04     - c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\test\parallel\test-module-readonly.js
11:25:04         at Object.<anonymous> (c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\test\parallel\test-module-readonly.js:48:8)
11:25:04         at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
11:25:04         at Module._load (node:internal/modules/cjs/loader:804:27)
11:25:04         at Module.require (node:internal/modules/cjs/loader:1022:19)
11:25:04         at require (node:internal/modules/cjs/helpers:102:18)
11:25:04         at Object.<anonymous> (c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\test\parallel\test-module-readonly.js:36:3)
11:25:04         at Module._compile (node:internal/modules/cjs/loader:1120:14)
11:25:04         at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
11:25:04         at Module.load (node:internal/modules/cjs/loader:998:32)
11:25:04         at Module._load (node:internal/modules/cjs/loader:839:12)
11:25:04         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
11:25:04       generatedMessage: false,
11:25:04       code: 'ERR_ASSERTION',
11:25:04       actual: Error: Cannot find module '..\.tmp.1874\readOnlyMod'
11:25:04       Require stack:
11:25:04       - c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\test\parallel\test-module-readonly.js
11:25:04           at Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
11:25:04           at Module._load (node:internal/modules/cjs/loader:804:27)
11:25:04           at Module.require (node:internal/modules/cjs/loader:1022:19)
11:25:04           at require (node:internal/modules/cjs/helpers:102:18)
11:25:04           at Object.<anonymous> (c:\workspace\windows-arm-simple\nodes\win10-vs2019-arm64\test\parallel\test-module-readonly.js:36:3)
11:25:04           at Module._compile (node:internal/modules/cjs/loader:1120:14)
11:25:04           at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
11:25:04           at Module.load (node:internal/modules/cjs/loader:998:32)
11:25:04           at Module._load (node:internal/modules/cjs/loader:839:12)
11:25:04           at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
11:25:04         code: 'MODULE_NOT_FOUND',
11:25:04         requireStack: [
11:25:04           'c:\\workspace\\windows-arm-simple\\nodes\\win10-vs2019-arm64\\test\\parallel\\test-module-readonly.js'
11:25:04         ]
11:25:04       },
11:25:04       expected: null,
11:25:04       operator: 'ifError'
11:25:04     }
11:25:04     
11:25:04     Node.js v19.0.0-pre
```
```

11:26:51 not ok 3099 parallel/test-worker-memory
11:26:51   ---
11:26:51   duration_ms: 11.807
11:26:51   severity: fail
11:26:51   exitcode: 3221226505
11:26:51   stack: |-
11:26:51     run() called with n=7.5 (numWorkers=8)
[multiple similar lines snipped]
1:26:51     done() called (finished=4)
11:26:51     run() called with n=0.5 (numWorkers=8)
11:26:51   ...
11:26:51 ok 3100 parallel/test-worker-message-port-inspect-during-init-hook
11:26:51   ---
11:26:51   duration_ms: 2.591
```

**Comment by nsait-linaro** [comment]
Thanks, @sxa .

`parallel/test-worker-memory`, `parallel/test-module-readonly` seems to pass on our CI [run](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/2503920989). We will run the tests again to confirm. 

`parallel/test-child-process-stdio-overlapped` seems to fail for us too. The same test seems to be failing for x64 too in our setup.

**Comment by dennisameling** [comment]
Excited to see the progress here - thanks all!

I've been experimenting with the native ARM64 VS 2022. It'll [reach GA in VS 2022 17.4](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-3-is-now-available/#next-up-visual-studio-2022-17-4), so that's pretty exciting. Should lead to a ~2x performance increase when building on native ARM64 devices. Will do a proper build time comparison once the bugs below have been resolved.

**16.x branch** (with [this commit](https://github.com/nodejs/node/commit/637af6c068d5003ffb5f96f2006a4aaa0b356693) applied)

The compilation process actually gets very far, but eventually runs into - what seems to be - a MSVC compiler bug. It's not an actual permissions issue, but I think the output is somehow corrupted causing `cl` to not be able to open the file. Tried it several times with fresh builds and the issue pops up consistently. Have reported that to MS: https://developercommunity.visualstudio.com/t/ARM64---fatal-error-C1083:-Cannot-open/10119540?port=1025&fsid=f1437298-c31b-4fd4-aed2-402da41caee0&entry=problem

<details>
  <summary>Build log</summary>

  ```
  C:\node>.\vcbuild.bat arm64 package release
  Looking for Python
  Python found in C:\Program Files\Python311-arm64\\python.exe
  Looking for Visual Studio 2022
  Found MSVS version 17.0
  configure  --with-ltcg --dest-cpu=arm64
  Node.js configure: Found Python 3.11.0...
  Warning: Missing input files:
  C:\node\tools\msvs\genfiles\node_etw_provider.h
  C:\node\tools\msvs\genfiles\node_etw_provider.rc
  INFO: configure completed successfully
  Project files generated.
  
  ....
  
   mksnapshot.cc
    snapshot-empty.cc
       Creating library ..\..\out\Release\mksnapshot.lib and object ..\..\out\Release\mksnapshot.exp
    mksnapshot.vcxproj -> ..\..\out\Release\\mksnapshot.exe
    generating: "..\..\out\Release\obj\v8_snapshot\/snapshot.cc" "..\..\out\Release\obj\v8_snapshot\/embedded.S"
    Microsoft (R) C/C++ Optimizing Compiler Version 19.34.31721 for ARM64
    Copyright (C) Microsoft Corporation.  All rights reserved.
  
    cl /c /P /Fi"..\..\out\Release\obj\v8_snapshot\embedded.S" /TC ..\..\out\Release\obj\v8_snapshot\\embedded.S
  
    embedded.S
  ..\..\out\Release\obj\v8_snapshot\\embedded.S : fatal error C1083: Cannot open compiler generated file: '..\..\out\Release\obj\v8_snapshot\embedded
  .S': Permission denied [C:\node\tools\v8_gypfiles\v8_snapshot.vcxproj]
  ```
</details>

**main branch**

Also getting quite far with this one, but it fails on `FixedArray::get` which is a [known bug](https://github.com/nodejs/node/issues/43092) with Node + VS2022 in general (also applies to x64). Have replied in that bug ticket to follow up. 

**Other notes/comments**
- Small PR to add support for the native VS 2022 ARM64 build tools: https://github.com/nodejs/node/pull/44226
- `node-gyp` PR to add support for the native VS 2022 ARM64 build tools: https://github.com/nodejs/node-gyp/pull/2650

**Comment by Alovchin91** [comment]
@dennisameling FYI while Visual Studio 17.3 itself doesn't yet support ARM64, the Build Tools in version 17.3 do 😉

**Comment by tidy-dev** [comment]
👋 Hey all! It is cool to see all this work on this thread. 

I am working with the GitHub Desktop team and looking to upgrade Electron again. The node version for electron version 21.3.3 that we are targeting is **16.16.0.** Wondering if it would be possible to get that added to the [unofficial builds](https://unofficial-builds.nodejs.org/download/release/)? 

_Secondarily... if it is not too much trouble, 16.17.1 would be much appreciated as well as that goes with Electron version 22 that was recently released?_

**Comment by joaocgreis** [comment]
@tidy-dev here they are:
- https://unofficial-builds.nodejs.org/download/release/v16.16.0/
- https://unofficial-builds.nodejs.org/download/release/v16.17.1/

Note that I wasn't able to properly test them in CI, please make sure they work well for you, and don't expect the same level of quality we have on the official releases.

**Comment by eukarpov** [comment]
it might be needed to have arm64 compilation fixed 
https://github.com/nodejs/node/pull/46231

**Comment by StefanStojanovic** [comment]
Since all of the PRs required for enabling official Windows ARM64 binaries have landed and CI is ready for them, I'm closing this issue as completed.

**Comment by tidy-dev** [comment]
👋 Hey all! 

> Since all of the PRs required for enabling official Windows ARM64 binaries have landed and CI is ready for them, I'm closing this issue as completed.

I am working with the GitHub Desktop team and looking to upgrade Electron again. The node version we need is 18.14.0. Is it possible to run a CI to generate it now? 

🙇 Thank you for all the work on this.

**Comment by joaocgreis** [comment]
@tidy-dev here it is: https://unofficial-builds.nodejs.org/download/release/v18.14.0/

The usual caveat applies, please test it and don't just assume it works. The official releases starting on v20 are fully tested, but this is just best-effort.

**Comment by theofficialgman** [comment]
@joaocgreis maybe I am missing something. Haven't official nodejs binaries for x64 windows supported cross compilation since v15 with https://github.com/nodejs/node/commit/883355125766e35126006507d1d8a09c149fc71d https://github.com/nodejs/node/commit/66807e995de9a16b1cfe035f76958a178c381854 ?

**Comment by sergiou87** [comment]
@joaocgreis Hello! 👋 Another request from the GitHub Desktop team 🙏 Any chance we could get a win-arm64 build for node 18.16.1?

Thanks in advance! (And let us know if there is a better way to do this or a better place to request it 😅 )

**Comment by eukarpov** [comment]
> @joaocgreis Hello! 👋 Another request from the GitHub Desktop team 🙏 Any chance we could get a win-arm64 build for node 18.16.1?
> 
> Thanks in advance! (And let us know if there is a better way to do this or a better place to request it 😅 )

@sergiou87 
JFYI, you can build the latest Arm64 Node.js here
https://github.com/Windows-on-ARM-Experiments/emsdk/actions/workflows/build-deps.yml
we could try to extend our workflow to build particular Node.js version, please let me know.

**Comment by sergiou87** [comment]
Thank you @eukarpov ! ❤️  However, for now we prefer to stick to João's builds to keep changes to a minimum. It's probably more than ok to grab node from other sources like your workflow but we'd rather be a bit conservative here, since we're upgrading Electron and that's quite a big change already 😅

**Comment by sergiou87** [comment]
Don't worry @joaocgreis ! You're still the best 🙇‍♂️🙇‍♂️🙇‍♂️ Thank you again for your help

I see starting with node v19.9.0 there are official builds for win-arm64, I hope it doesn't take too long before Electron uses that version 😄

**Comment by sergiou87** [comment]
Hey @joaocgreis! 👋 Hopefully the last request from the GitHub Desktop team 🙏 Any chance we could get a win-arm64 build for node 18.18.2?

Thanks in advance!
