### ISSUE TITLE
 Jobs failing with java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy21

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2594]
After the Jenkins update (https://github.com/nodejs/build/issues/2593) some jobs are failing with a NoClassDefFoundError,
e.g.
https://ci.nodejs.org/job/node-test-commit-linux/nodes=centos7-64-gcc6/40574/console on [test-softlayer-centos7-x64-1](https://ci.nodejs.org/computer/test-softlayer-centos7-x64-1)
<details>

```
10:00:28 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from fa.55.1732.ip4.static.sl-reverse.com/50.23.85.250:56218
10:00:28 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
10:00:28 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
10:00:28 		at hudson.remoting.Channel.call(Channel.java:1001)
10:00:28 		at hudson.FilePath.act(FilePath.java:1158)
10:00:28 		at hudson.FilePath.act(FilePath.java:1147)
10:00:28 		at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
10:00:28 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:905)
10:00:28 		at hudson.plugins.git.GitSCM.createClient(GitSCM.java:836)
10:00:28 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1289)
10:00:28 		at hudson.scm.SCM.checkout(SCM.java:505)
10:00:28 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
10:00:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
10:00:28 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
10:00:28 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
10:00:28 		at hudson.model.Run.execute(Run.java:1907)
10:00:28 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
10:00:28 		at hudson.model.ResourceController.execute(ResourceController.java:97)
10:00:28 		at hudson.model.Executor.run(Executor.java:429)
10:00:28 java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy21
10:00:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:00:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:00:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:00:28 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:00:28 	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
10:00:28 	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:169)
10:00:28 	at hudson.remoting.Channel.export(Channel.java:811)
10:00:28 	at hudson.remoting.Channel.export(Channel.java:774)
10:00:28 	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:204)
10:00:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:00:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
10:00:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:00:28 	at java.lang.reflect.Method.invoke(Method.java:498)
10:00:28 	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1218)
10:00:28 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1136)
10:00:28 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
10:00:28 	at hudson.remoting.UserRequest._serialize(UserRequest.java:263)
10:00:28 	at hudson.remoting.UserRequest.serialize(UserRequest.java:272)
10:00:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:222)
10:00:28 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
10:00:28 	at hudson.remoting.Request$2.run(Request.java:369)
10:00:28 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
10:00:28 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10:00:28 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
10:00:28 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
10:00:28 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:117)
10:00:28 	at java.lang.Thread.run(Thread.java:748)
10:00:28 Caused: java.io.IOException: Remote call on JNLP4-connect connection from fa.55.1732.ip4.static.sl-reverse.com/50.23.85.250:56218 failed
10:00:28 	at hudson.remoting.Channel.call(Channel.java:1007)
10:00:28 	at hudson.FilePath.act(FilePath.java:1158)
10:00:28 	at hudson.FilePath.act(FilePath.java:1147)
10:00:28 	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:121)
10:00:28 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:905)
10:00:28 	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:836)
10:00:28 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1289)
10:00:28 	at hudson.scm.SCM.checkout(SCM.java:505)
10:00:28 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1204)
10:00:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:636)
10:00:28 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
10:00:28 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:508)
10:00:28 	at hudson.model.Run.execute(Run.java:1907)
10:00:28 	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
10:00:28 	at hudson.model.ResourceController.execute(ResourceController.java:97)
10:00:28 	at hudson.model.Executor.run(Executor.java:429)
10:00:28 All downstream projects complete!
```
</details>

Usually a Jenkins agent restart (with an update to the latest agent jar if required) should fix this.

Hosts affected (agent restarted)
- [x] release-digitalocean-centos7-x64-1
- [x] test-softlayer-centos7-x64-1
- [x] test-rackspace-centos7-x64-1
- [x] test-rackspace-ubuntu1604-x64-1
- [x] test-rackspace-win2012r2_vs2017-x64-3
- [x] test-rackspace-win2012r2_vs2019-x64-3

**Comment by richardlau** [comment]
Restarting agent on https://ci.nodejs.org/computer/test-softlayer-centos7-x64-1

**Comment by richardlau** [comment]
Also https://ci.nodejs.org/computer/test-rackspace-centos7-x64-1 (https://ci.nodejs.org/job/node-test-commit-linux/40576/nodes=centos7-64-gcc8/console)

**Comment by richardlau** [comment]
Ran `playbooks/jenkins/worker/upgrade-jar.yml` on the two centos7-x64 hosts, which has updated the agent jar to 4.6.
Test builds:
- https://ci.nodejs.org/job/node-test-commit-linux/40579/nodes=centos7-64-gcc8/
- https://ci.nodejs.org/job/node-test-commit-linux/40577/nodes=centos7-64-gcc8/

**Comment by richardlau** [comment]
Also restarted agent on https://ci.nodejs.org/computer/test-rackspace-ubuntu1604-x64-1, which has failed for a slightly different NoClassDefFoundError:

https://ci.nodejs.org/job/node-test-node-addon-api-new/nodes=ubuntu1604-64/3837/console
<details>

```
FATAL: Remote call on JNLP4-connect connection from 119.9.51.176/119.9.51.176:58898 failed
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 119.9.51.176/119.9.51.176:58898
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1800)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:525)
		at hudson.model.Run.execute(Run.java:1907)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.NoClassDefFoundError: Could not initialize class jenkins.model.Jenkins
	at jenkins.agents.AgentComputerUtil.getChannelToMaster(AgentComputerUtil.java:48)
	at hudson.util.ProcessTree.get(ProcessTree.java:431)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1164)
	at hudson.Launcher$RemoteLauncher$KillTask.call(Launcher.java:1155)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:375)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:73)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:118)
	at java.lang.Thread.run(Thread.java:748)
Caused: java.io.IOException: Remote call on JNLP4-connect connection from 119.9.51.176/119.9.51.176:58898 failed
	at hudson.remoting.Channel.call(Channel.java:1007)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1147)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:525)
	at hudson.model.Run.execute(Run.java:1907)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```
</details>

**Comment by richardlau** [comment]
Restarted agent on https://ci-release.nodejs.org/computer/release-digitalocean-centos7-x64-1 due to: https://ci-release.nodejs.org/job/iojs+release/6756/nodes=centos7-release-sources/console

I can't reansible this host because the `upgrade-jar.xml` playbook only works on `test-*` hosts and the `jenkins/worker/create.xml` playbook currently errors when run against the centos7-64:(https://github.com/nodejs/build/issues/2587

**Comment by richardlau** [comment]
test-rackspace-win2012r2_vs2017-x64-3 and test-rackspace-win2012r2_vs2019-x64-3 by rerunning the failing platforms from https://ci.nodejs.org/job/windows-update-reboot/1522/ with `FORCE_REBOOT` parameter set.

**Comment by richardlau** [comment]
I think that is all of them, but if anyone finds another please post here or open a new issue.
