### ISSUE TITLE
`test-osuosl-aix72-ppc64_be-4` `.git: Permission denied` error

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2719]
This is a different issue to https://github.com/nodejs/build/issues/2718 -- [`test-osuosl-aix72-ppc64_be-4`](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-4/) is failing builds this morning due to a permissions issue:
e.g. https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/37814/console
```
08:43:58 Caused by: hudson.plugins.git.GitException: Command "git init /home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64" returned status code 1:
08:43:58 stdout: 
08:43:58 stderr: /home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/.git: Permission denied
08:43:58 
08:43:58 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2661)
08:43:58 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2591)
08:43:58 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2587)
08:43:58 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1958)
08:43:58 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1030)
08:43:58 	... 13 more
08:43:58 ERROR: Error cloning remote repo 'origin'
```

**Comment by richardlau** [comment]
Logged into the machine and somehow `/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64` is owned by `root` (!):
```
iojs@p8-aix2-nodejs03:[/home/iojs/build/workspace/node-test-commit-aix/nodes]ls -al
total 0
drwxr-xr-x    4 iojs     iojs            256 Feb 11 14:05 .
drwxr-xr-x    3 iojs     iojs            256 Feb 11 14:05 ..
drwxr-xr-x    2 root     system          256 Aug  1 22:47 aix72-ppc64
drwxr-xr-x    2 iojs     iojs            256 Mar  3 16:41 aix72-ppc64@tmp
iojs@p8-aix2-nodejs03:[/home/iojs/build/workspace/node-test-commit-aix/nodes]
```

Its parent `/home/iojs/build/workspace/node-test-commit-aix/nodes` is correctly owned by `iojs`.

**Comment by richardlau** [comment]
Going to try using the `Clear Workspace` template in AWX.

**Comment by richardlau** [comment]
The template cleared out the workspace.
Started a test CI run: https://ci.nodejs.org/job/node-test-commit-aix/37817/nodes=aix72-ppc64/console
It looks like the workspace has been recreated with the correct owner/group.

**Comment by richardlau** [comment]
While the permissions issue appears to have been fixed, builds on this host are now timing out after an hour's inactivity.

**Comment by richardlau** [comment]
As per https://github.com/nodejs/build/issues/2718#issuecomment-891126582 `/var` was full. I cleared the `yum` cache by running `yum clean all`. 

There has now been one green build on this machine: https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/37828/

**Comment by richardlau** [comment]
We had a couple of green builds but not too many as Jenkins appears to prefer scheduling onto -3 and -2 ahead of -4. We haven't seen the permissions error again though so I'm going to close this. https://github.com/nodejs/build/issues/2718 is still ongoing.
