### ISSUE TITLE
`No Xcode or CLT version detected!` on `test-orka-macos10.15-x64-2` with Node.js 12

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2728]
The Node.js 12 daily builds on macOS are failing when run on `test-orka-macos10.15-x64-2`:
e.g. https://ci.nodejs.org/job/node-test-commit-osx/41801/nodes=osx1015/console
```
11:00:51 python ./configure --verbose 
11:00:55 No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
11:00:55 
11:00:55 No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
11:00:55 
11:00:55 No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
11:00:55 
11:00:55 gyp: No Xcode or CLT version detected!
```
<details>

```
11:00:51 python ./configure --verbose 
11:00:55 No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
11:00:55 
11:00:55 No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
11:00:55 
11:00:55 No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
11:00:55 
11:00:55 gyp: No Xcode or CLT version detected!
11:00:55 Detected clang C++ compiler (CXX=/usr/local/bin/ccache c++) version: 11.0.3
11:00:55 Detected clang C compiler (CC=/usr/local/bin/ccache cc) version: 11.0.3
11:00:55 creating icu_config.gypi
11:00:55 * Using ICU in deps/icu-small
11:00:55 creating icu_config.gypi
11:00:55 { 'target_defaults': { 'cflags': [],
11:00:55                        'default_configuration': 'Release',
11:00:55                        'defines': [],
11:00:55                        'include_dirs': [],
11:00:55                        'libraries': []},
11:00:55   'variables': { 'asan': 0,
11:00:55                  'build_v8_with_gn': 'false',
11:00:55                  'coverage': 'false',
11:00:55                  'dcheck_always_on': 0,
11:00:55                  'debug_nghttp2': 'false',
11:00:55                  'debug_node': 'false',
11:00:55                  'enable_lto': 'false',
11:00:55                  'enable_pgo_generate': 'false',
11:00:55                  'enable_pgo_use': 'false',
11:00:55                  'force_dynamic_crt': 0,
11:00:55                  'host_arch': 'x64',
11:00:55                  'icu_data_in': '../../deps/icu-small/source/data/in/icudt67l.dat',
11:00:55                  'icu_default_data': '',
11:00:55                  'icu_endianness': 'l',
11:00:55                  'icu_gyp_path': 'tools/icu/icu-generic.gyp',
11:00:55                  'icu_locales': 'en,root',
11:00:55                  'icu_path': 'deps/icu-small',
11:00:55                  'icu_small': 'true',
11:00:55                  'icu_ver_major': '67',
11:00:55                  'is_debug': 0,
11:00:55                  'llvm_version': '11.0',
11:00:55                  'napi_build_version': '8',
11:00:55                  'node_byteorder': 'little',
11:00:55                  'node_debug_lib': 'false',
11:00:55                  'node_enable_d8': 'false',
11:00:55                  'node_install_npm': 'true',
11:00:55                  'node_module_version': 72,
11:00:55                  'node_no_browser_globals': 'false',
11:00:55                  'node_prefix': '/usr/local',
11:00:55                  'node_release_urlbase': '',
11:00:55                  'node_shared': 'false',
11:00:55                  'node_shared_brotli': 'false',
11:00:55                  'node_shared_cares': 'false',
11:00:55                  'node_shared_http_parser': 'false',
11:00:55                  'node_shared_libuv': 'false',
11:00:55                  'node_shared_nghttp2': 'false',
11:00:55                  'node_shared_openssl': 'false',
11:00:55                  'node_shared_zlib': 'false',
11:00:55                  'node_tag': '',
11:00:55                  'node_target_type': 'executable',
11:00:55                  'node_use_bundled_v8': 'true',
11:00:55                  'node_use_dtrace': 'true',
11:00:55                  'node_use_etw': 'false',
11:00:55                  'node_use_node_code_cache': 'true',
11:00:55                  'node_use_node_snapshot': 'true',
11:00:55                  'node_use_openssl': 'true',
11:00:55                  'node_use_v8_platform': 'true',
11:00:55                  'node_with_ltcg': 'false',
11:00:55                  'node_without_node_options': 'false',
11:00:55                  'openssl_fips': '',
11:00:55                  'openssl_is_fips': 'false',
11:00:55                  'ossfuzz': 'false',
11:00:55                  'shlib_suffix': '72.dylib',
11:00:55                  'target_arch': 'x64',
11:00:55                  'v8_enable_gdbjit': 0,
11:00:55                  'v8_enable_i18n_support': 1,
11:00:55                  'v8_enable_inspector': 1,
11:00:55                  'v8_enable_lite_mode': 0,
11:00:55                  'v8_enable_object_print': 1,
11:00:55                  'v8_no_strict_aliasing': 1,
11:00:55                  'v8_optimized_debug': 1,
11:00:55                  'v8_promise_internal_field_count': 1,
11:00:55                  'v8_random_seed': 0,
11:00:55                  'v8_trace_maps': 0,
11:00:55                  'v8_use_siphash': 1,
11:00:55                  'v8_use_snapshot': 1,
11:00:55                  'want_separate_host_toolset': 0,
11:00:55                  'xcode_version': '11.0'}}
11:00:55 creating config.gypi
11:00:55 creating config.status
11:00:55 creating config.mk
11:00:55 running: 
11:00:55     python tools/gyp_node.py --no-parallel -Dconfiguring_node=1 -f make-mac
11:00:55 Error running GYP
11:00:55 make: *** [build-ci] Error 1
```
</details>

Builds on test-orka-macos10.15-x64-3 are passing:
e.g. https://ci.nodejs.org/job/node-test-commit-osx/41791/nodes=osx1015/

It also looks like macOS builds from master on  test-orka-macos10.15-x64-2 are passing: https://ci.nodejs.org/computer/test-orka-macos10.15-x64-2/builds
so it's likely that there is some set up difference between -2 and -3 that Node.js 12 is sensitive to but master somehow tolerates.

**Comment by richardlau** [comment]
The `No Xcode or CLT version detected!` error is coming out of `tools/gyp/pylib/gyp/xcode_emulation.py` in the core repo. The difference between test-orka-macos10.15-x64-2 and test-orka-macos10.15-x64-3 is what `/usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables` returns:

On test-orka-macos10.15-x64-2
```
bash-3.2$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
bash-3.2$
```

On test-orka-macos10.15-x64-3
```
bash-3.2$ /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 11.4.0.0.1.1583798712
volume: /
location: /
install-time: 1585247061
groups: com.apple.FindSystemFiles.pkg-group
bash-3.2$
```

Node.js master is tolerant of this difference due to https://github.com/nodejs/node/commit/916516c8d702011fb5a6a3fc3046b602cee39571#diff-442988ab0350a1a08f5229ccd5d3f8cb99c924774b3897dafadba1e25d052d29 from the gyp-next 0.3.0 update which does a fallback `/usr/sbin/softwareupdate --history`. 

I'm a little hesitant to pull gyp updates back into 12 given that 12 is in maintenance.

**Comment by richardlau** [comment]
As an experiment I tried cherry-picking commits that updated `tools/gyp` up to gyp-next 0.7.0 (the later updates dropped support for Python 2 which we can't do in Node.js 12). This did allow Node.js to build on test-orka-macos10.15-x64-2 but the build still fails because building addons uses the version of gyp in node-gyp 5.1.0 (included in npm 6) so hits the original `No Xcode or CLT version detected!` issue: https://ci.nodejs.org/job/node-test-commit-osx/41810/nodes=osx1015/console

**Comment by richardlau** [comment]
Node.js 14 builds `test-orka-macos10.15-x64-2` but fails to build addons due to the older node-gyp (it has the same version of npm as Node.js 12): https://ci.nodejs.org/job/node-test-commit-osx/41874/nodes=osx1015/console

<details>

```
22:35:46 Error: Command failed: /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref
22:35:46 gyp info it worked if it ends with ok
22:35:46 gyp info using node-gyp@5.1.0
22:35:46 gyp info using node@14.17.6-pre | darwin | x64
22:35:46 gyp info chdir /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref
22:35:46 gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
22:35:46 gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
22:35:46 gyp info spawn args [
22:35:46 gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/gyp/gyp_main.py',
22:35:46 gyp info spawn args   'binding.gyp',
22:35:46 gyp info spawn args   '-f',
22:35:46 gyp info spawn args   'make',
22:35:46 gyp info spawn args   '-I',
22:35:46 gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref/build/config.gypi',
22:35:46 gyp info spawn args   '-I',
22:35:46 gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/addon.gypi',
22:35:46 gyp info spawn args   '-I',
22:35:46 gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/common.gypi',
22:35:46 gyp info spawn args   '-Dlibrary=shared_library',
22:35:46 gyp info spawn args   '-Dvisibility=default',
22:35:46 gyp info spawn args   '-Dnode_root_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015',
22:35:46 gyp info spawn args   '-Dnode_gyp_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp',
22:35:46 gyp info spawn args   '-Dnode_lib_file=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/$(Configuration)/node.lib',
22:35:46 gyp info spawn args   '-Dmodule_root_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref',
22:35:46 gyp info spawn args   '-Dnode_engine=v8',
22:35:46 gyp info spawn args   '--depth=.',
22:35:46 gyp info spawn args   '--no-parallel',
22:35:46 gyp info spawn args   '--generator-output',
22:35:46 gyp info spawn args   'build',
22:35:46 gyp info spawn args   '-Goutput_dir=.'
22:35:46 gyp info spawn args ]
22:35:46 No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
22:35:46 
22:35:46 No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
22:35:46 
22:35:46 No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
22:35:46 
22:35:46 gyp: No Xcode or CLT version detected!
22:35:46 gyp ERR! configure error 
22:35:46 gyp ERR! stack Error: `gyp` failed with exit code: 1
22:35:46 gyp ERR! stack     at ChildProcess.onCpExit (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/lib/configure.js:351:16)
22:35:46 gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
22:35:46 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:278:12)
22:35:46 gyp ERR! System Darwin 19.4.0
22:35:46 gyp ERR! command "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node" "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref"
22:35:46 gyp ERR! cwd /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref
22:35:46 gyp ERR! node -v v14.17.6-pre
22:35:46 gyp ERR! node-gyp -v v5.1.0
22:35:46 gyp ERR! not ok 
22:35:46 
22:35:46     at ChildProcess.exithandler (child_process.js:382:12)
22:35:46     at ChildProcess.emit (events.js:400:28)
22:35:46     at maybeClose (internal/child_process.js:1057:16)
22:35:46     at Socket.<anonymous> (internal/child_process.js:442:11)
22:35:46     at Socket.emit (events.js:400:28)
22:35:46     at Pipe.<anonymous> (net.js:676:12) {
22:35:46   killed: false,
22:35:46   code: 1,
22:35:46   signal: null,
22:35:46   cmd: '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref',
22:35:46   stdout: '',
22:35:46   stderr: 'gyp info it worked if it ends with ok\n' +
22:35:46     'gyp info using node-gyp@5.1.0\n' +
22:35:46     'gyp info using node@14.17.6-pre | darwin | x64\n' +
22:35:46     'gyp info chdir /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref\n' +
22:35:46     'gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"\n' +
22:35:46     'gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python\n' +
22:35:46     'gyp info spawn args [\n' +
22:35:46     "gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/gyp/gyp_main.py',\n" +
22:35:46     "gyp info spawn args   'binding.gyp',\n" +
22:35:46     "gyp info spawn args   '-f',\n" +
22:35:46     "gyp info spawn args   'make',\n" +
22:35:46     "gyp info spawn args   '-I',\n" +
22:35:46     "gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref/build/config.gypi',\n" +
22:35:46     "gyp info spawn args   '-I',\n" +
22:35:46     "gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/addon.gypi',\n" +
22:35:46     "gyp info spawn args   '-I',\n" +
22:35:46     "gyp info spawn args   '/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/common.gypi',\n" +
22:35:46     "gyp info spawn args   '-Dlibrary=shared_library',\n" +
22:35:46     "gyp info spawn args   '-Dvisibility=default',\n" +
22:35:46     "gyp info spawn args   '-Dnode_root_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015',\n" +
22:35:46     "gyp info spawn args   '-Dnode_gyp_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp',\n" +
22:35:46     "gyp info spawn args   '-Dnode_lib_file=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/$(Configuration)/node.lib',\n" +
22:35:46     "gyp info spawn args   '-Dmodule_root_dir=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref',\n" +
22:35:46     "gyp info spawn args   '-Dnode_engine=v8',\n" +
22:35:46     "gyp info spawn args   '--depth=.',\n" +
22:35:46     "gyp info spawn args   '--no-parallel',\n" +
22:35:46     "gyp info spawn args   '--generator-output',\n" +
22:35:46     "gyp info spawn args   'build',\n" +
22:35:46     "gyp info spawn args   '-Goutput_dir=.'\n" +
22:35:46     'gyp info spawn args ]\n' +
22:35:46     "No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.\n" +
22:35:46     '\n' +
22:35:46     "No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.\n" +
22:35:46     '\n' +
22:35:46     "No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.\n" +
22:35:46     '\n' +
22:35:46     'gyp: No Xcode or CLT version detected!\n' +
22:35:46     'gyp ERR! configure error \n' +
22:35:46     'gyp ERR! stack Error: `gyp` failed with exit code: 1\n' +
22:35:46     'gyp ERR! stack     at ChildProcess.onCpExit (/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/lib/configure.js:351:16)\n' +
22:35:46     'gyp ERR! stack     at ChildProcess.emit (events.js:400:28)\n' +
22:35:46     'gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:278:12)\n' +
22:35:46     'gyp ERR! System Darwin 19.4.0\n' +
22:35:46     'gyp ERR! command "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/out/Release/node" "/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/deps/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--directory=/Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref"\n' +
22:35:46     'gyp ERR! cwd /Users/iojs/build/workspace/node-test-commit-osx/nodes/osx1015/benchmark/napi/ref\n' +
22:35:46     'gyp ERR! node -v v14.17.6-pre\n' +
22:35:46     'gyp ERR! node-gyp -v v5.1.0\n' +
22:35:46     'gyp ERR! not ok \n'
22:35:46 }
```
</details>

**Comment by richardlau** [comment]
I've marked [test-orka-macos10.15-x64-2](https://ci.nodejs.org/computer/test-orka-macos10.15-x64-2/) offline in Jenkins for now to get builds through.

@AshCripps Please could you look at fixing up the Xcode install on this machine?

**Comment by AshCripps** [comment]
> @AshCripps Please could you look at fixing up the Xcode install on this machine?

on it :+1:

**Comment by AshCripps** [comment]
Reinstalled Xcode 11.7 - had to go for the full fledged version as couldnt find the specific command line tools version but that machine has plenty of diskspace

**Comment by richardlau** [comment]
Looks like the check still fails on the machine:
```
administrator@test-orka-macos10 ~ % /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
administrator@test-orka-macos10 ~ %
```

(the code expects one of 
```
/usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
/usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLI
/usr/sbin/pkgutil --pkg-info com.apple.pkg.DeveloperToolsCLILeo
```
[to succeed](https://github.com/nodejs/node/blob/c7f4ecbdbc1479b843bf151467f2eec6e4f06792/tools/gyp/pylib/gyp/xcode_emulation.py#L1436-L1446).)

**Comment by AshCripps** [comment]
ok ive tracked down 11.5 command line tools - for some reason this is the latest available to me in pure CLT form.

```sh
administrator@test-orka-macos10 ~ % /usr/sbin/pkgutil --pkg-info com.apple.pkg.CLTools_Executables
package-id: com.apple.pkg.CLTools_Executables
version: 11.5.0.0.1.1588476445
volume: /
location: /
install-time: 1629901029
groups: com.apple.FindSystemFiles.pkg-group 
administrator@test-orka-macos10 ~ % 
```
