### ISSUE TITLE
node-test-linter fails with `bad config line 1 in file .git/config`

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2842]
node-test-linter appears to have started consistently failing yesterday:

e.g. https://ci.nodejs.org/job/node-test-linter/43314/console
```console
12:40:30 Fetching changes from the remote Git repository
12:40:30  > git config remote.origin.url git@github.com:nodejs/node.git # timeout=10
12:40:30 ERROR: Error fetching remote repo 'origin'
12:40:30 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
12:40:30 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1001)
12:40:30 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1242)
12:40:30 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
12:40:30 	at hudson.scm.SCM.checkout(SCM.java:505)
12:40:30 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
12:40:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
12:40:30 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
12:40:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
12:40:30 	at hudson.model.Run.execute(Run.java:1888)
12:40:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:40:30 	at hudson.model.ResourceController.execute(ResourceController.java:99)
12:40:30 	at hudson.model.Executor.run(Executor.java:431)
12:40:30 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url git@github.com:nodejs/node.git" returned status code 128:
12:40:30 stdout: 
12:40:30 stderr: fatal: bad config line 1 in file .git/config
12:40:30 
```

Looks like the git config has been corrupted.

**Comment by richardlau** [comment]
I've wiped out the workspace.
FWIW the contents of the corrupted `.git/config` file:
```console
iojs@test-ibm-ubuntu1804-x64-1:~/build/workspace/node-test-linter$ cat .git/config
var test = require('tap').test
const common = require('../common-tap.js')
var npm = require('../..')
var path = require('path')
var rimraf = require('rimraf')
var npmrc = path.join(common.pkg, 'npmrc')
var fs = require('fs')

test('setup', function (t) {
  fs.writeFileSync(npmrc, 'foo = bar\n', 'ascii')
  t.endiojs@test-ibm-ubuntu1804-x64-1:~/build/workspace/node-test-linter$
```

**Comment by richardlau** [comment]
Test build: https://ci.nodejs.org/job/node-test-linter/43315/console

**Comment by mhdawson** [comment]
Also cleared the workspace for https://ci.nodejs.org/job/node-test-commit-linux/ as it looked like it had a similar issue.

**Comment by mhdawson** [comment]
Also wiped workspace for https://ci.nodejs.org/job/node-test-commit-freebsd as it looked liked it had similar issue.

**Comment by richardlau** [comment]
IBM Cloud did send a notification yesterday (I'm still catching up on emails after time off) of an incident at Dallas 13 (where `test-ibm-ubuntu1804-x64-1` is located) relating to SAN issues and a routing failure.
