### ISSUE TITLE
jobs fail with `error: could not lock config file .git/config: File exists`

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2843]
node-test-commit-arm-fanned and node-test-commit-plinux have been failing on test-ibm-ubuntu1804-x64-1 since yesterday (3 Jan 2022) with
e.g. https://ci.nodejs.org/job/node-test-commit-arm-fanned/23473/console
```console
12:42:32 Fetching changes from the remote Git repository
12:42:32  > git config remote.origin.url git@github.com:nodejs/node.git # timeout=10
12:42:32 ERROR: Error fetching remote repo 'origin'
12:42:32 hudson.plugins.git.GitException: Failed to fetch from git@github.com:nodejs/node.git
12:42:32 	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1001)
12:42:32 	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1242)
12:42:32 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
12:42:32 	at hudson.scm.SCM.checkout(SCM.java:505)
12:42:32 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
12:42:32 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
12:42:32 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
12:42:32 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
12:42:32 	at com.tikal.jenkins.plugins.multijob.MultiJobBuild$MultiJobRunnerImpl.run(MultiJobBuild.java:148)
12:42:32 	at hudson.model.Run.execute(Run.java:1888)
12:42:32 	at com.tikal.jenkins.plugins.multijob.MultiJobBuild.run(MultiJobBuild.java:76)
12:42:32 	at hudson.model.ResourceController.execute(ResourceController.java:99)
12:42:32 	at hudson.model.Executor.run(Executor.java:431)
12:42:32 Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url git@github.com:nodejs/node.git" returned status code 255:
12:42:32 stdout: 
12:42:32 stderr: error: could not lock config file .git/config: File exists
12:42:32 
```

It's probably related to https://github.com/nodejs/build/issues/2842.

**Comment by richardlau** [comment]
I've removed `.git/config.lock` files from 
- `/home/iojs/build/workspace/node-test-commit-arm-fanned`
- `/home/iojs/build/workspace/node-test-commit-arm-fanned@2`

Test CI: https://ci.nodejs.org/job/node-test-commit-arm-fanned/23478/

**Comment by richardlau** [comment]
There was also a `.git/config.lock` in `node-test-commit-plinux` and looking at the corresponding job that was also failing since yesterday. I've removed that lock file as well.
