### ISSUE TITLE
All AIX nodes offline

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2854]
Our AIX test instances are all currently offline in Jenkins.

### AIX 7.1
- [test-ibm-aix71-ppc64_be-3](https://ci.nodejs.org/computer/test-ibm-aix71-ppc64_be-3/)
- [test-ibm-aix71-ppc64_be-4](https://ci.nodejs.org/computer/test-ibm-aix71-ppc64_be-4/)

### AIX 7.2
- [test-osuosl-aix72-ppc64_be-2](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/)
- [test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-3/)
- [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-4/)

**Comment by richardlau** [comment]
For [test-osuosl-aix72-ppc64_be-2](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-2/) this is the end of `jenkins_console.log`:
<details>

```console
Jan 21, 2022 10:06:12 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
Jan 21, 2022 10:06:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:06:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:06:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:07:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:07:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:07:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:07:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:08:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:08:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:08:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:08:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:09:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:09:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:09:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:09:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:10:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:10:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:10:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:10:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:11:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:11:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:11:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:11:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:12:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:12:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:12:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:12:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:13:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:13:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:13:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:13:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:14:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:14:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:14:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:14:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:15:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:15:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:15:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:15:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:16:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:16:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:16:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:16:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:17:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:17:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:17:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:17:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:18:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:18:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:18:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:18:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:19:12 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:19:27 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:19:42 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:19:57 AM org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver waitForReady
INFO: Failed to connect to the master. Will try again: java.net.SocketTimeoutException connect timed out
Jan 21, 2022 10:20:10 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Performing onReconnect operation.
Jan 21, 2022 10:20:10 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: onReconnect operation failed.
Jan 21, 2022 10:20:10 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [https://ci.nodejs.org/]
Jan 21, 2022 10:20:40 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to https://ci.nodejs.org/tcpSlaveAgentListener/: connect timed out
java.io.IOException: Failed to connect to https://ci.nodejs.org/tcpSlaveAgentListener/: connect timed out
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
        at hudson.remoting.Engine.innerRun(Engine.java:689)
        at hudson.remoting.Engine.run(Engine.java:514)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:607)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:288)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:203)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:189)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
        at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:211)
        ... 2 more

```
</details>

It looks like the agent got disconnected around two and half hours ago and couldn't reconnect. This would appear to be the same time period that Jenkins was reported as being down in https://github.com/nodejs/build/issues/2853.

**Comment by richardlau** [comment]
Ran the [`upgrade-jar.yml` playbook](https://github.com/nodejs/build/blob/8d5f9018d345727316b4d327ca40cbc0316ac674/ansible/playbooks/jenkins/worker/upgrade-jar.yml) on the AIX 7.2 machines to update the agent and restart it.

**Comment by richardlau** [comment]
Ran the [`upgrade-jar.yml` playbook](https://github.com/nodejs/build/blob/8d5f9018d345727316b4d327ca40cbc0316ac674/ansible/playbooks/jenkins/worker/upgrade-jar.yml) on the AIX 7.1 machines to update the agent and restart it.
