### ISSUE TITLE
`node-test-linter` failing with ImportError

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2865]
It looks like around 7 hours ago https://ci.nodejs.org/job/node-test-linter/ started consistently failing
![image](https://user-images.githubusercontent.com/5445507/153092112-e57f5b9b-4c94-494b-8599-0eb085741454.png)

e.g. https://ci.nodejs.org/job/node-test-linter/43758/console
```console
16:17:17 + make lint-ci PYTHON=python2
16:17:17 Running JS linter...
16:20:59 Running C++ linter...
16:21:36 PYTHONPATH=tools/pip python2 -m flake8 --count --show-source --statistics .
16:21:36 Traceback (most recent call last):
16:21:36   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
16:21:36     "__main__", fname, loader, pkg_name)
16:21:36   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
16:21:36     exec code in run_globals
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/__main__.py", line 2, in <module>
16:21:36     from flake8.main import cli
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/main/cli.py", line 5, in <module>
16:21:36     from flake8.main import application
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/main/application.py", line 11, in <module>
16:21:36     from flake8 import checker
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/checker.py", line 18, in <module>
16:21:36     from flake8 import processor
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/processor.py", line 13, in <module>
16:21:36     from flake8 import utils
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/utils.py", line 16, in <module>
16:21:36     from flake8._compat import lru_cache
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/flake8/_compat.py", line 12, in <module>
16:21:36     import importlib_metadata
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/importlib_metadata/__init__.py", line 16, in <module>
16:21:36     from ._compat import (
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/importlib_metadata/_compat.py", line 36, in <module>
16:21:36     import pathlib2 as pathlib
16:21:36   File "/home/iojs/build/workspace/node-test-linter/tools/pip/site-packages/pathlib2/__init__.py", line 26, in <module>
16:21:36     from six.moves.collections_abc import Sequence
16:21:36 ImportError: No module named collections_abc
16:21:36 Makefile:1485: recipe for target 'lint-py' failed
```

I'm guessing that flake8 has been updated in a way that is incompatible with Python 2. We should drop running the linter with Python 2 but I'll need to check we can still lint Node.js 12.

**Comment by richardlau** [comment]
FWIW it's not `flake8` but one of its dependencies, `pathlib2` which was updated [9 hours ago](https://pypi.org/project/pathlib2/2.3.7.post0/) and included https://github.com/jazzband/pathlib2/pull/75.

**Comment by richardlau** [comment]
Changed the job to drop running with Python 2. Audit trail: https://github.com/nodejs/jenkins-config-test/commit/166a63e3fe27989709d0de3b76819246d46a03e9

Running some test builds across the various release lines:
v12.x-staging: https://ci.nodejs.org/job/node-test-linter/43770/ ✔️ 
v14.x-staging: https://ci.nodejs.org/job/node-test-linter/43771/ 
v16.x-staging: https://ci.nodejs.org/job/node-test-linter/43772/
v17.x-staging: https://ci.nodejs.org/job/node-test-linter/43773/
master: https://ci.nodejs.org/job/node-test-linter/43774/
