### ISSUE TITLE
RISC-V port

### ISSUE THREAD

**Issue by drom** [nodejs/build#2876]

**Comment by mmarchini** [comment]
I moved the issue to nodejs/build as I think it's the most relevant repository to continue this discussion (since there'll be work around setting up infrastructure). As discussed on Slack we can start with setting up one Jenkins agent and having a test job running on it. Once we have that setup we can discuss how many nodes would be convenient for both the Node.js project and for SiFive.

Question for @nodejs/build-infra: would we prefer RISC-V nodes being hosted by SiFive, or do we want to host those ourselves?

**Comment by sxa** [comment]
Assuming we'd have full access to them I think having it hosted by SiFive would generally be the preferred option assuming we had full access to it, although I could probably host one too.
My ]concern would be that I'm not sure it's possible to recover the Unmatched boards if they crash for whatever reason without someone physically pushing the reset button on them unlike most cloud machines so if we had any issues with it that could be a problem.

**Comment by rvagg** [comment]
Managed hosting where we have reason to trust the provider is the preferred option, by far. I've tried to minimise our reliance on infra hosted by individuals wherever possible and it would be good to reduce that even further over time.

Let's try and avoid signing up our infra for more boxes on desks. It's a big weak point in terms of reliability and, to some degree security.

**Comment by sxa** [comment]
> Also builds ok natively in about ten hours with just --shared-openssl

A brief update on this - while it does build ok with the ICU support, it does seem to get stuck when building the `test-doc` target, so the ICU support is probably not working correctly on this platform.

**Comment by sxa** [comment]
I'm looking to get this building with a cross-compiler although I'm currently getting compiler failures when doing so. This PR doesn't resolve the issue I'm seeing. I'm going to build natively on the RISC-V board to see if it's a specific issue with the cross compile. If it can be convinced to work (and it should do) then we can likely get it added as an unofficial build using the existing system fairly quickly afterwards.

**Comment by sxa** [comment]
I've got a clean build with a cross compiler now so we should be able to incorporate this into a suitable dockerfile now. I've got one based on [the `arm_cross` Dockerfile](https://github.com/nodejs/build/blob/master/ansible/roles/docker/templates/ubuntu1804_arm_cross.Dockerfile.j2) that will do the job using a tarball of a cross-compiler I use elsewhere for now.

**Comment by sxa** [comment]
"Unofficial build" support is now live (although the server that's building is is creaking a bit under space limitations) so we have builds at https://unofficial-builds.nodejs.org/download/release/v17.9.0/ so we just need to get that formalised in the docs.

The builds don't pass all the tests (mainly failures in crypto - perhaps due to openssl-no-asm - and addons tests) but it fundamentally works so I'm comfortable that it's good enough for experimental. It is built with full-icu so may well have an issue with the hangs described above with the doc target mentioned previously but we should consider whether we wish to perform some formal testing on this on real boards other than the ones I'm using elsewhere for now :-)

**Comment by rvagg** [comment]
fancy, good work @sxa .. I guess we need to deal with those space problems

**Comment by olof-nord** [comment]
I see RISC-V now included in the unofficial builds, great! Seems that the space issues from April are resolved.
What steps are needed, and what is the progress of, moving the RISC-V support from unofficial to official?

**Comment by sxa** [comment]
The next step would be to look at getting the build passing all the tests that come with node, since they weren't all passing last time I tried. SInce this is pretty much a spare time project for me I haven't had too much time to look at progressing that.

**Comment by sxa** [comment]
FYI There's a build break on 19.0.0 so there is no unofficial build for RISC-V in the latest version yet: https://github.com/nodejs/node/issues/45059

**Comment by sxa** [comment]
Ref the above, 19.1.0 has RISC-V support back again.

While it's not part of the build pipelines yet (Performance would likely be an issue) I have connected in a RISC-V Ubuntu system into the CI and set up a job to build from the `main` branch daily and run the tests against it if any committers are interested in keeping an eye on it and/or fixing any failures. The job is at https://ci.nodejs.org/job/sxa-rvnodetest/ (On it's first run through as I write this but it should complete the build ok.

It would be good to get openssl support building without openssl-no-asm at some point.

**Comment by olof-nord** [comment]
Great update!

With the CI it builds way (way) faster than on the HiFive Unmatched (also with Ubuntu). I have done a few builds (with `--shared-openssl`), and the build times are on an average 8h. Fastest builds I could get were around 2h with `--without-npm --without-corepack --without-ssl --without-node-options --without-intl --without-inspector` - nothing close to 30 minutes like with the Jenkins you linked.

With SSL being the seemingly biggest task open, is what is needed for Node.js risc-v support to provide the assembly for OpenSSL? What is needed to organise this? Is there any documentation, further information what needs doing?

And on a side note, what is the difference of building Node.js with `--openssl-no-asm` vs `--shared-openssl`?

**Comment by sxa** [comment]
> With the CI it builds way (way) faster than on the HiFive Unmatched (also with Ubuntu)

Actually it doesn't - it was a labelling issue on my part and the first builds I left running yesterday built on an x64 system instead of RISC-V 😳   The system that has been added to the Jenkins CI is an Unmatched board so you should see it running with a similar performance to yours. I've had a build complete in about 5 minutes using ccache (second time through obviously) and that's what I'll leave it using, but obviously the times will vary depending on what changes have gone in on any given day which affects how much of the cache can be reused. We could cross compile from an x64 server (I've done this before) and run the testing only on the RISC-V system if we wanted to speed things up, but for now since this is just going to be building daily rather than on every PR I'm going to keep it all native on the board.

> what is needed for Node.js risc-v support to provide the assembly for OpenSSL? What is needed to organise this?

In terms of openssl it would be a case of running the build without any of the openssl options and see what breaks. It's been a while since I tried it but it was a fairly obvious compile failure as I recall and liklely not too hard to resolve.

The other thing that will need to be looked at is any test failures that show up in that job. I don't think there were too many the last time I ran it on my machine.

> And on a side note, what is the difference of building Node.js with --openssl-no-asm vs --shared-openssl?

The Node.js codebase has it's own version of the openssl source in there (`deps/openssl`) which is the one we build with and statically link it into the node.js binary.

`--openssl-no-asm` tells the Node build process to run the openssl `./Configure` with the `no-asm` parameter which tells it not to use any of openssl's integrated assembly language optimisations. So while it works, it will likely not 

`--shared-openssl` tells the Node build process not to build the version of openssl in `deps/openssl` within the codebase, but to take the SSL header files and libraries from the operating system and build and link against those instead.

**Comment by sxa** [comment]
Looks like we have five failures in the main test bucket:
- parallel/test-crypto-keygen (TIMEOUT)
- parallel/test-fs-watch-recursive (TIMEOUT)
- test-net-socket-connect-without-cb (ENOTFOUND localhost - potentially a machine specific problem)
- parallel/test-tcp-wrap-listen (Also ENOTFOUND localhost)
- parallel/test-tls-dhe (TIMEOUT)
The other 3775 tests in the suite passed.

**Comment by sxa** [comment]
Additionally there are a few issues in the testing outside the main set of tests:

## Linter checks:
```
Oops! Something went wrong! :(

ESLint: 8.28.0

/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/node_modules/jsdoc-type-pratt-parser/dist/index.js:94
    const identifierStartRegex = /[$_\p{ID_Start}]|\\u\p{Hex_Digit}{4}|\\u\{0*(?:\p{Hex_Digit}{1,5}|10\p{Hex_Digit}{4})\}/u;
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[$_\p{ID_Start}]|\\u\p{Hex_Digit}{4}|\\u\{0*(?:\p{Hex_Digit}{1,5}|10\p{Hex_Digit}{4})\}/: Invalid property name in character class
```
## Doc related tests
```
=== release test-doctool-html ===
Path: doctool/test-doctool-html
/home/iojs/workspace/sxa-rvnodetest/tools/doc/node_modules/highlight.js/lib/languages/xml.js:18
  const TAG_NAME_RE = regex.concat(/[\p{L}_]/u, regex.optional(/[\p{L}0-9_.-]*:/u), /[\p{L}0-9_.-]*/u);
                                   ^^^^^^^^^^^

SyntaxError: Invalid regular expression: /[\p{L}_]/: Invalid property name in character class
    at internalCompileFunction (node:internal/vm:74:18)
```
## test-make-doc failure:
```
=== release test-make-doc ===
Path: doctool/test-make-doc
node:internal/process/esm_loader:108
    internalBinding('errors').triggerUncaughtException(
                              ^

AssertionError [ERR_ASSERTION]: false == true
    at file:///home/iojs/workspace/sxa-rvnodetest/test/doctool/test-make-doc.mjs:18:8
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v20.0.0-pre
Command: out/Release/node /home/iojs/workspace/sxa-rvnodetest/test/doctool/test-make-doc.mjs
```
## `TracedValue.Escaping(Object|Array)`:
```
[ RUN      ] TracedValue.EscapingObject
../test/cctest/test_traced_value.cc:83: Failure
Expected equality of these values:
  check
    Which is: "{\"a\":\"1\\u00E2\\u0082\\u00AC23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"}"
  string
    Which is: "{\"a\":\"1\xE2\x82\xAC" "23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"}"
    As Text: "{"a":"1€23\"\u0001\b\f\n\r\t\\"}"
With diff:
@@ -1,1 +1,2 @@
-{\"a\":\"1\\u00E2\\u0082\\u00AC23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"}
+{\"a\":\"1\xE2\x82\xAC" "23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"}"
    As Text: "{"a":"1€23\"\u0001\b\f
+\r\t\\"}

[  FAILED  ] TracedValue.EscapingObject (0 ms)
[ RUN      ] TracedValue.EscapingArray
../test/cctest/test_traced_value.cc:95: Failure
Expected equality of these values:
  check
    Which is: "[\"1\\u00E2\\u0082\\u00AC23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"]"
  string
    Which is: "[\"1\xE2\x82\xAC" "23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"]"
    As Text: "["1€23\"\u0001\b\f\n\r\t\\"]"
With diff:
@@ -1,1 +1,2 @@
-[\"1\\u00E2\\u0082\\u00AC23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"]
+[\"1\xE2\x82\xAC" "23\\\"\\u0001\\b\\f\\n\\r\\t\\\\\"]"
    As Text: "["1€23\"\u0001\b\f
+\r\t\\"]

[  FAILED  ] TracedValue.EscapingArray (0 ms)
```

**Comment by richardlau** [comment]
@sxa I suspect those regexp failures are because you're compiling without ICU.

**Comment by olof-nord** [comment]
Great to list out the test errors, re the timeout adjustments there has been some work carried out by @ArchFeh [already](https://github.com/nodejs/node/pull/42674) to accommodate less powerful riscv testing devices.

I looked into the OpenSSL assembly language optimisations for RISC-V, and there is some initial work for `aes` and `modes/ghash` in place, but I could not find it included in any release yet.

From what I can tell, Node.js additionally needs `bn`, `chacha`, `ec`, `poly1305` as well as `sha` group (`keccak1600`, `sha1`, `sha256` as well as `sha512`) asm for an architecture to be complete. Is that correct?

I do not know how much effort is needed here, but it looks like there is quite a lot of work left before this is done. Assuming all ciphers listed are needed, the current status is 20% (2 from 10) complete.

**Comment by sxa** [comment]
Yeah I hadn't realised when I wrote that statement earlier that the upstream openssl likely does not have the asm support in it, so that's not an issue that's specific to the Node.js build process (other than the fact we configure it by default without `no-asm`)

> From what I can tell, Node.js additionally needs bn, chacha, ec, poly1305 as well as sha group (keccak1600, sha1, sha256 as well as sha512) asm for an architecture to be complete. Is that correct?

@richardlau Do you know if that is correct or if it can be considered "complete" with `no-asm`?

**Comment by richardlau** [comment]
> Yeah I hadn't realised when I wrote that statement earlier that the upstream openssl likely does not have the asm support in it, so that's not an issue that's specific to the Node.js build process (other than the fact we configure it by default without `no-asm`)
> 
> > From what I can tell, Node.js additionally needs bn, chacha, ec, poly1305 as well as sha group (keccak1600, sha1, sha256 as well as sha512) asm for an architecture to be complete. Is that correct?
> 
> @richardlau Do you know if that is correct or if it can be considered "complete" with `no-asm`?

No idea what you mean by "complete".

I'm not sure Node.js has a definitive list of supported algorithms -- you're likely to get a different set if using a binary from a Linux distro.

**Comment by sxa** [comment]
> Additionally there are a few issues in the testing outside the main set of tests:

As @richardlau asserted most of these have gone away if I run with full-icu. Previously this was causing some hangs, but at least on my first run that is not happening. All of those failures in my second comment above pass with either `small-icu` or `full-icu` except for the linter:

```
make -s test-doc
Running JS linter...

Oops! Something went wrong! :(

ESLint: 8.28.0

TypeError: Cannot read properties of undefined (reading 'replace')
    at parse (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:839:54)
    at Linter._verifyWithoutProcessors (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1349:33)
    at Linter._verifyWithConfigArray (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1769:21)
    at /home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1888:29
    at Array.map (<anonymous>)
    at Linter._verifyWithProcessor (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1868:37)
    at Linter._verifyWithConfigArray (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1762:25)
    at Linter.verify (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:1476:65)
    at Linter.verifyAndFix (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/linter/linter.js:2028:29)
    at verifyText (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/cli-engine/cli-engine.js:245:48)
    at CLIEngine.executeOnFiles (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/cli-engine/cli-engine.js:823:28)
    at ESLint.lintFiles (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/eslint/eslint.js:551:23)
    at Object.execute (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/lib/cli.js:417:36)
    at async main (/home/iojs/workspace/sxa-rvnodetest/tools/node_modules/eslint/bin/eslint.js:135:24)
Running Markdown linter...
```
I'll leave the job running daily without `--with-intl=none` and see if any hangs show up now.

**Comment by mhdawson** [comment]
> @richardlau Do you know if that is correct or if it can be considered "complete" with no-asm?

I think this mostly affects performance.  I don't think it would necessarily be a blocker.

**Comment by sxa** [comment]
@nodejs/build Revisiting this because it's been marked as stale (and we ran out of time in the call today for me to raise it). We describe experimental platforms as "May or may not pass test suites. The core team does no create releases for these platforms". Given that we have unofficial builds and there is generally a desire to fix those when they go wrong (but it doesn't pass all the test cases yet) are we in a position where we can consider riscv64 a valid "experimental tier" platform?
Related: https://github.com/nodejs/node/pull/42251

**Comment by ilg-ul** [comment]
@sxa, @luyahan, I contacted Ludovic Henry from the [Language Runtime WG in RISE](https://wiki.riseproject.dev/display/HOME/Language+Runtimes+WG) and he would be happy to integrate a group maintaining **node**, if there is interest.

I don't know the team who worked on the RISC-V port, but I think they would also be a good candidate to be part of a RISC-V node WG.

Stewart, apparently you already contacted RISE, perhaps you can catalyse the efforts and reach some agreement with them.

**Comment by sxa** [comment]
Yep I know Ludovic and am involved with that working group ;-) 
I'm obviously happy to help out (I've got four RISC-V boards within arms reach here and obviously I set up the unofficial builds for it) but RISC-V is not my primary day job (unfortunately!) so I can't guarantee that I can look into any problems in a timely manner so ideally we'd have someone else in the community willing to stand up for that before we promote it. I can likely handle infra related stuff but the issue we have is "What if the build breaks due to a code issue?" which is generally the Node.js criteria for bumping it up.

**Comment by ilg-ul** [comment]
@sxa, could you contact me by email?

**Comment by sxa** [comment]
> @sxa, could you contact me by email?

Done - to the address on your github profile. I'm also on the openjsf slack (and various others!) if you want to contact me there :-)

**Comment by mhdawson** [comment]
@sxa are the only RISC-V boards used for teesting currently the ones you have?

**Comment by sxa** [comment]
> @sxa are the only RISC-V boards used for teesting currently the ones you have?

Yes. but only one (not one in my house!) is connected to the Node CI.

**Comment by targos** [comment]
I created the @nodejs/platform-riscv64 GitHub team and invited @sxa to it.
Anyone else who would like to be notified about RISC-V stuff?

**Comment by ilg-ul** [comment]
I'd like to be notified about RISC-V stuff.

**Comment by drom** [comment]
@targos please add me tot the list

**Comment by targos** [comment]
I invited both of you.

**Comment by targos** [comment]
@luyahan would you like to be part of the team?

**Comment by olof-nord** [comment]
I realise I am quite late to reply, but if possible I am also (still) interested to be notified about RISC-V stuff.

**Comment by targos** [comment]
@olof-nord you're invited too :)

**Comment by EwoutH** [comment]
Any updates on this effort? What's needed to move it forward?

**Comment by andreamancuso** [comment]
> Any updates on this effort? What's needed to move it forward?

https://github.com/nodejs/node/issues/56175 was just closed "not planned".

**Comment by mhdawson** [comment]
@andreamancuso, as I understand it we don't have enough volunteers who are keeping the non-official builds building/running/working (II think I heard they have been broken recently) Until more people step up to volunteer their time to work on riskv.

What's need are people to volunteer their time to fist keep the non-official builds green, and then possibly on-ramp more hardware, etc.  See https://github.com/nodejs/build/issues/3511 for a similar request for another architecture and an outline of what it would take.

**Comment by andreamancuso** [comment]
@mhdawson thank you for the feedback.

I'll admit that from a user's perspective I'm happy to use the official Debian Trixie packages for the riscv-64 architecture. At the end of the day they do the job just fine.

That being said, I'll be happy to have a look at the build whenever I can - do I need special permissions to look at the logs, etc.?
How do contributors communicate? Discord, Matrix?

Cheers

**Comment by sxa** [comment]
> That being said, I'll be happy to have a look at the build whenever I can - do I need special permissions to look at the logs, etc.?

For the unofficial builds the logs are all under https://unofficial-builds.nodejs.org/logs/ although I do note that it looks like it hasn't attempted to build for riscv64 in recent builds. I'm not sure if someone disabled them but I expect we'll need to update the cross-compiler that we're using since there have been V8 updates in the last few months that require a later one. Up until quite recently there was a build break but now that's been resolved we should be able to get the builds working again, subject to compiler issues.

> How do contributors communicate? Discord, Matrix?

Here in GitHub or in the openjs-foundation slack (invite link is on the bottom right of nodejs.org)

> https://github.com/nodejs/node/issues/56175 was just closed "not planned".

I just took a look at what you wrote in there. I have access to quite a few unmatched boards that we can use. The issue I have at the moment is that it takes, how should I put it "quite a long time" to build and test on RISC-V hardware and so adding it fully into the main CI is problematic. Also it's a bit more than just buying boards (I have a BananaPi-F3, a Lichee-4A and a VF2 next to me, and while all are quicker than the unmatched, they're still not really at the level we'd like). It's worth also adding in Scaleway's RISC-V offering (TH1520 boards like the LicheePi-4A) which is something I use on the other project I work on.

There are two aspects to the builds:
1. The "unofficial builds" which are just built with a cross-compiler and shipped (No testing) - those are the ones that produce the logs referenced above
2. Integration into the main CI where testing is done. At the moment because of the slowness of machines I decoupled the building and testing of it from the main PR testing and set it to run as a scheduled job periodically to try and make sure things still runs ok after fixes are put in  (Although that's currently broken too and I'll need to get back onto that - the job that does it is at https://ci.nodejs.org/job/sxa-rvnodetest/ (only visible to committers)

**Comment by sxa** [comment]
> Any updates on this effort? What's needed to move it forward?

The blocker at the moment fort the unofficial builds of V22+ is the compiler version that's required which we'll need to update to re-enable them Ref: https://github.com/nodejs/unofficial-builds/issues/154

**Comment by sxa** [comment]
I've just pushed the latest v20up at https://unofficial-builds.nodejs.org/download/release/v20.18.1/node-v20.18.1-linux-riscv64.tar.xz

**Comment by VitaliKaiser** [comment]
Hi, I struggled a bit to find riscv builds for newer versions in the build list.
Is there a build with node: '>=22.0.0' ?

**Comment by silverwind** [comment]
At least Alpine Linux ships a working Node.js on `linux/riscv64` architecture, so this should be possible.

**Comment by sxa** [comment]
@VitaliKaiser I did some work to get the unofficial builds working again so they should be getting produced more regularly again. Regular maintenance is required to keep it up to date with the compilers etc. that Node requires.
