### ISSUE TITLE
Node-addon-api ci failures - Windows machine, process running, how to kill

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#2901]
https://ci.nodejs.org/view/x%20-%20Abi%20stable%20module%20API/job/node-test-node-addon-api-new/nodes=win-vs2019/5566/

```
Regular expression run condition: Expression=[Windows_NT], Label=[Windows_NT]
Run condition [Regular expression match] enabling perform for step [BuilderChain]
[win-vs2019] $ cmd /c call C:\Users\ADMINI~1\AppData\Local\Temp\jenkins6405470488769372122.bat

C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019>rmdir C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019 /s /q 
The process cannot access the file because it is being used by another process.

C:\workspace\node-test-node-addon-api-new\nodes\win-vs2019>exit 0 
Run condition [Always] enabling perform for step [BuilderChain]
[win-vs2019] $ /bin/bash C:\Users\ADMINI~1\AppData\Local\Temp\jenkins535003061964635609.sh
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
	at java.lang.ProcessImpl.start(ProcessImpl.java:140)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 104.130.141.231/104.130.141.231:49170
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at hudson.Launcher$RemoteLauncher.launch(Launcher.java:1122)
		at hudson.Launcher$ProcStarter.start(Launcher.java:507)
		at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:143)

```

**Comment by mhdawson** [comment]
It's been this way for a number of days.  @joaocgreis is it possible for us to log into the machine and fix or is this something you need to do?

**Comment by richardlau** [comment]
We can log into these machines using Remmina -- the [write-ssh-config playbook](https://github.com/nodejs/build/blob/master/ansible/playbooks/write-ssh-config.yml) will write the necessary configuration for e.g. the flatpak version of Remmina installable in Fedora 34.

**Comment by mhdawson** [comment]
thanks, was able to connect to the machine.

**Comment by mhdawson** [comment]
closing as I've resolved the issue.
