### ISSUE TITLE
` Cannot run program "git" (in directory "..."): error=65535, System call error number 65535.` on test-rzkh-ibmi73-ppc64_be-1

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#2966]
e.g. https://ci.nodejs.org/job/libuv-test-commit-ibmi/611/nodes=ibmi73-ppc64/console

```console
Cloning repository git@github.com:ibmruntimes/libuv.git
 > git init /home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64 # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Could not init /home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1042)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:797)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:158)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:151)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:376)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at hudson.remoting.InterceptingExecutorService$$Lambda$86/0000000000000000.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:119)
	at hudson.remoting.Engine$1$$Lambda$61/0000000000000000.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:834)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from ossbuild.rzkh.de/185.113.4.148:28361
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1797)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:1001)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:143)
		at sun.reflect.GeneratedMethodAccessor3378.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:129)
		at com.sun.proxy.$Proxy100.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1224)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1302)
		at hudson.scm.SCM.checkout(SCM.java:505)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1213)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:637)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:509)
		at hudson.model.Run.execute(Run.java:1888)
		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
		at hudson.model.ResourceController.execute(ResourceController.java:99)
		at hudson.model.Executor.run(Executor.java:432)
Caused by: hudson.plugins.git.GitException: Error performing git command: git init /home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2679)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2601)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2597)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1968)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1040)
	... 14 more
Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64"): error=65535, System call error number 65535.

	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at hudson.Proc$LocalProc.<init>(Proc.java:252)
	at hudson.Proc$LocalProc.<init>(Proc.java:221)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:995)
	at hudson.Launcher$ProcStarter.start(Launcher.java:507)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2664)
	... 18 more
Caused by: java.io.IOException: error=65535, System call error number 65535.

	at java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:341)
	at java.lang.ProcessImpl.start(ProcessImpl.java:272)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
ERROR: Error cloning remote repo 'origin'
```

I'll take [test-rzkh-ibmi73-ppc64_be-1](https://ci.nodejs.org/computer/test-rzkh-ibmi73-ppc64_be-1/) offline from Jenkins for now and take a look tomorrow to see if I can figure out what's up with the machine.

cc @ThePrez

**Comment by richardlau** [comment]
hmm @ThePrez I think I might need some help here. AFAICT `git` works on [test-rzkh-ibmi73-ppc64_be-1](https://ci.nodejs.org/computer/test-rzkh-ibmi73-ppc64_be-1/) from an ssh login but is consistently failing in the https://ci.nodejs.org/job/libuv-test-commit-ibmi/ job. I've tried removing the workspace directory on the machine completely, in case it was a corrupt `.git` folder, but https://ci.nodejs.org/job/libuv-test-commit-ibmi/617/nodes=ibmi73-ppc64/console has failed in exactly the same way.

I don't have much else to go on other than the `Cannot run program "git" (in directory "/home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64"): error=65535, System call error number 65535.` exception.

I've taken the machine offline in Jenkins again. FWIW the other two IBM i machines (iinthecloud) are working as expected.

**Comment by ThePrez** [comment]
I noticed the following from jgit in the jenkins.log file
```pascal
SEVERE: Mount point not found
java.io.IOException: Mount point not found
        at java.base/sun.nio.fs.AixFileStore.findMountEntry(AixFileStore.java:88)
        at java.base/sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:67)
        at java.base/sun.nio.fs.AixFileStore.<init>(AixFileStore.java:42)
        at java.base/sun.nio.fs.AixFileSystemProvider.getFileStore(AixFileSystemProvider.java:50)
        at java.base/sun.nio.fs.AixFileSystemProvider.getFileStore(AixFileSystemProvider.java:35)
```

Aligned with my blind hunch that this was related to the UDFS directory. 
Strangely, as you've discovered, the directory seems fully functional, and the `git init` works just fine, and the IOJS user has needed authorities

Assuming the source code [here](https://github.com/openjdk/jdk/blob/af64d316c0f687c4ceab7591e050449c64e3babc/src/java.base/aix/classes/sun/nio/fs/AixFileStore.java#L88) is up-to-date-enough, the failure is related to an inability to find the mount point associated with the directory. One could conceivably believe that something in the OpenJDK filesystem code is not working properly on our very-unique filesystem, but as far as I can tell, nothing has changed since the "working state"

I recreated the UDFS in case it was in some wonky state, but I don't think that will correct the problem. I'll try running jgit standalone for debug...

**Comment by richardlau** [comment]
@ThePrez Well it failed, slightly differently (looks like permissions):
https://ci.nodejs.org/job/libuv-test-commit-ibmi/620/nodes=ibmi73-ppc64/console
```
using credential dea9092d-214b-471a-be5d-5343dd7755c1
Wiping out workspace first.
Also:   java.nio.file.FileSystemException: /home/iojs/build/workspace/libuv-test-commit-ibmi/nodes/ibmi73-ppc64/.git/refs/heads: Operation not permitted.
```

**Comment by richardlau** [comment]
Probably because of this 🙂 :
```
-bash-5.1$ ls -al ../iojs/build/workspace/
total 72
drwxrwsrwx  4 iojs   0  8192 Jun 17 14:43 .
drwxr-xr-x 11 iojs   0 49152 Jun 17 14:21 ..
drwxr-sr-x  2 iojs   0  8192 Jun 17 14:21 .ccache
drwxr-sr-x  3 jesseg 0  8192 Jun 17 14:43 libuv-test-commit-ibmi
-bash-5.1$
```

**Comment by ThePrez** [comment]
directory removed 🤞
