### ISSUE TITLE
`node-stress-single-test` doesn't work on test-digitalocean-ubuntu1804-x64-1

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/build#3008]
From https://github.com/nodejs/node/pull/44144, it seem there is something wrong with the python version or the test.py script on [test-digitalocean-ubuntu1804-x64-1](https://ci.nodejs.org/computer/test-digitalocean-ubuntu1804-x64-1), no tests can be run from test.py there (I confirm that locally this command works, and it seems `node-stress-single-test` is working fine on at least [test-ibm-ubuntu1804-x64-2](https://ci.nodejs.org/computer/test-ibm-ubuntu1804-x64-2) (https://ci.nodejs.org/job/node-stress-single-test/364/nodes=ubuntu1804-64/).

From https://ci.nodejs.org/job/node-stress-single-test/365/nodes=ubuntu1804-64/console

```
12:49:11 + /usr/bin/python3.6 tools/test.py -p tap --logfile test851.tap --mode=release parallel/test-diagnostics-channel-net
12:49:11 No tests to run.
12:49:11 + NOK=851
12:49:11 + echo '851   OK: 0   NOT OK: 851   TOTAL: 1000'
12:49:11 851   OK: 0   NOT OK: 851   TOTAL: 1000
12:49:11 + tap2junit -i test851.tap -o test851.xml
12:49:11 Traceback (most recent call last):
12:49:11   File "/usr/local/bin/tap2junit", line 11, in <module>
12:49:11     sys.exit(main())
12:49:11   File "/usr/local/lib/python2.7/dist-packages/tap2junit/__main__.py", line 44, in main
12:49:11     result = parse(os.path.splitext(args.input.name)[0], data)
12:49:11   File "/usr/local/lib/python2.7/dist-packages/tap2junit/__main__.py", line 11, in parse
12:49:11     tap_parser.parse(data)
12:49:11   File "/usr/local/lib/python2.7/dist-packages/tap2junit/tap13.py", line 124, in parse
12:49:11     self._parse(StringIO.StringIO(source))
12:49:11   File "/usr/local/lib/python2.7/dist-packages/tap2junit/tap13.py", line 115, in _parse
12:49:11     raise ValueError("Missing plan in the TAP source")
12:49:11 ValueError: Missing plan in the TAP source
```

Locally I get

```
python3 tools/test.py -p tap --logfile test851.tap --mode=release parallel/test-diagnostics-channel-net
TAP version 13
1..1
ok 1 parallel/test-diagnostics-channel-net
  ---
  duration_ms: 0.105
  ...
```

**Comment by joyeecheung** [comment]
Oops, nevermind, I think I just used the wrong branch when configuring the CI so the test wasn't there. Sorry for the noise!
