### ISSUE TITLE
V8 CI broken on v19.x

### ISSUE THREAD

**Issue by targos** [nodejs/build#3221]
Example: https://ci.nodejs.org/job/node-test-commit-v8-linux/5221/

```
09:20:58 export PATH="/usr/bin:/home/iojs/build/workspace/node-test-commit-v8-linux/depot_tools:/home/iojs/nghttp2/src:/home/iojs/wrk:/usr/lib/ccache:/usr/lib64/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" && \
09:20:58 	/usr/bin/python3.9 deps/v8/tools/run-tests.py --gn --arch=ppc64 --progress=dots --timeout=120 intl \
09:20:58 			mjsunit cctest debugger inspector message preparser \
09:20:58 			--json-test-results /home/iojs/build/workspace/node-test-commit-v8-linux/v8-tap.json --slow-tests-cutoff 1000000
09:20:58 Traceback (most recent call last):
09:20:58   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/tools/run-tests.py", line 11, in <module>
09:20:58     from testrunner import standard_runner
09:20:58   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/tools/testrunner/standard_runner.py", line 16, in <module>
09:20:58     from testrunner.testproc.progress import ResultsTracker, ProgressProc
09:20:58   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/tools/testrunner/testproc/progress.py", line 9, in <module>
09:20:58     from testrunner.testproc.resultdb import ResultDBIndicator
09:20:58   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/tools/testrunner/testproc/resultdb.py", line 8, in <module>
09:20:58     import requests
09:20:58 ModuleNotFoundError: No module named 'requests'
```

Main branch doesn't seem affected (it's on a more recent version of V8): https://ci.nodejs.org/job/node-test-commit-v8-linux/5222/

**Comment by richardlau** [comment]
> ```console
> 09:20:58 ModuleNotFoundError: No module named 'requests'
> ```

@miladfarca came across this with the upstream V8 work. From https://github.com/nodeshift/v8-build/commit/60937fc18a8bd998e75ea030db9dec7fa4329bd3 it looks like this was introduced in https://crrev.com/c/3905385 but that looks like it was reverted in https://chromium-review.googlesource.com/c/v8/v8/+/3952131 (which is probably why the main branch isn't affected).

**Comment by richardlau** [comment]
V8 backport PR: https://github.com/nodejs/node/pull/47239
