### ISSUE TITLE
AIX Failed to read test report file 

### ISSUE THREAD

**Issue by MoLow** [nodejs/build#3280]
after upgrading `tap2junit` the XML file is generated successfully, but occasionally Jenkins fails to read the file.
it seems related to encoding somehow which is weird since tap2junit explicitly saves the file as `utf-8`:
https://github.com/nodejs/tap2junit/blob/0cfd0301af2f5fa10d41bda0e101e915bd24a5cf/tap2junit/__main__.py#L69

https://ci.nodejs.org/job/node-test-commit-aix/45957/nodes=aix72-ppc64/testReport/junit/test/xml/_failed_to_read_/

```
Failed to read test report file /home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/out/junit/test.xml
org.dom4j.DocumentException: Error on line 3738 of document  : Invalid byte 3 of 3-byte UTF-8 sequence.
	at org.dom4j.io.SAXReader.read(SAXReader.java:511)
	at org.dom4j.io.SAXReader.read(SAXReader.java:392)
	at hudson.tasks.junit.SuiteResult.parse(SuiteResult.java:177)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:384)
	at hudson.tasks.junit.TestResult.parsePossiblyEmpty(TestResult.java:314)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:256)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:242)
	at hudson.tasks.junit.TestResult.parse(TestResult.java:220)
	at hudson.tasks.junit.TestResult.<init>(TestResult.java:174)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:176)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3578)
	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:377)
	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:125)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException; lineNumber: 3738; columnNumber: 22; Invalid byte 3 of 3-byte UTF-8 sequence.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	... 19 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 3 of 3-byte UTF-8 sequence.
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanLiteral(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	... 29 more
```

**Comment by MoLow** [comment]
I don't have permissions to edit the Jenkins job but perhaps if we can store the XML file as an artifact it will make it easier to debug

**Comment by richardlau** [comment]
@MoLow I managed to catch a job in the act and take the machine offline before another job overwrote the workspace.
[test-osuosl-aix72-ppc64_be-3](https://ci.nodejs.org/computer/test-osuosl-aix72-ppc64_be-3/) has been taken offline and the tap and xml can be obtained from the server:
- `/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/test.tap`
- `/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64/out/junit/test.xml`

**Comment by MoLow** [comment]
@richardlau it seems that tap2junit is not installed correctly, although the installation fails, we are still using an old installation:
```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]pip -V
pip 23.0.1 from /opt/freeware/lib/python3.9/site-packages/pip (python 3.9)
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]pip install tap2junit
Requirement already satisfied: tap2junit in /opt/freeware/lib/python3.9/site-packages (0.1.6)
```

but the date does not make any sence:
```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]which tap2junit
/opt/bin/tap2junit
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]ls -l /opt/bin/tap2junit
-rwxr-xr-x    1 root     system          217 Oct  8 2021  /opt/bin/tap2junit
```

also `tap2unit` is missing some arguments added on 0.1.6:

```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]tap2junit -i molow.tap -o molow.xml -c
usage: tap2junit [-h] --input INPUT --output OUTPUT
tap2junit: error: unrecognized arguments: -c
```

and locally:
```console
 tap2junit -V 
usage: tap2junit [-h] --input INPUT --output OUTPUT [--compact] [--name NAME] [--package PACKAGE]
tap2junit: error: the following arguments are required: --input/-i, --output/-o
```

however this does use the latest version:
```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]python3 -m tap2junit
usage: tap2junit [-h] --input INPUT --output OUTPUT [--compact] [--name NAME] [--package PACKAGE]
tap2junit: error: the following arguments are required: --input/-i, --output/-o
```

**Comment by MoLow** [comment]
btw using the proper version results in proper formatted XML:

```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64] python3 -m tap2junit -i molow.tap -o molow.xml && cat molow.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites disabled="0" errors="0" failures="0" tests="1" time="0.000309">
        <testsuite disabled="0" errors="0" failures="0" name="molow" skipped="1" tests="1" time="0.000309" hostname="nodejs02">
                <testcase name="test_runner_default_reporter " time="0.000309" classname="pseudo-tty">
                        <skipped type="skipped" message="[34mℹ tests 3[39m"/>
                </testcase>
        </testsuite>
</testsuites>
```

verses
```console
root@test-osuosl-aix72-ppc64_be-3:[/home/iojs/build/workspace/node-test-commit-aix/nodes/aix72-ppc64]tap2junit -i molow.tap -o molow.xml && cat molow.xml
<?xml version="1.0" encoding="utf-8"?>
<testsuites disabled="0" errors="0" failures="0" tests="1" time="0.309">
        <testsuite disabled="0" errors="0" failures="0" hostname="nodejs02" name="molow" skipped="1" tests="1" time="0.309">
                <testcase name="pseudo-tty/test_runner_default_reporter " time="0.309000">
                        <skipped message="[34m� tests 3[39m" type="skipped"/>
                </testcase>
        </testsuite>
</testsuites>
```

**Comment by richardlau** [comment]
Ah spotted the problem.
https://ci.nodejs.org/job/node-test-commit-aix/configure does this to run tap2junit:
```console
#!/bin/bash -x +e

. ./build/jenkins/scripts/node-test-commit-diagnostics.sh after

export PATH=/opt/bin:/opt/freeware/bin:$PATH
export PYTHONUTF8=1
mkdir -p out/junit
tap2junit -i test.tap -o out/junit/test.xml
[ -e "cctest.tap" ] && tap2junit -i cctest.tap -o out/junit/cctest.xml
rm -Rf out/Release/obj.target
```
I'll remove `/opt/bin` from the PATH so that we should be picking up from `/opt/freeware/bin`.

**Comment by richardlau** [comment]
Looks like https://ci.nodejs.org/job/node-test-commit-aix/45965/nodes=aix72-ppc64/ is running on this machine, so we can keep an eye out to check it's picked up the correct tap2junit.

**Comment by MoLow** [comment]
seems to have worked here https://ci.nodejs.org/job/node-test-commit-aix/45963/nodes=aix72-ppc64/
