### ISSUE TITLE
java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by anonrig** [nodejs/build#3287]
Build: https://ci.nodejs.org/job/node-test-commit-linux/nodes=ubuntu1804-64/51522/console
Machine: ubuntu1804-64

Logs:

```
00:00:00.059 java.io.IOException: No space left on device
00:00:00.059 	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
00:00:00.059 	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
00:00:00.059 	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:132)
00:00:00.059 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:97)
00:00:00.059 	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:67)
00:00:00.059 	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:288)
00:00:00.059 	at java.base/java.nio.channels.Channels.writeFullyImpl(Channels.java:74)
00:00:00.059 	at java.base/java.nio.channels.Channels.writeFully(Channels.java:96)
00:00:00.059 	at java.base/java.nio.channels.Channels$1.write(Channels.java:171)
00:00:00.059 	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:234)
00:00:00.059 	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:340)
00:00:00.059 	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:169)
00:00:00.059 	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:252)
00:00:00.059 	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:269)
```

cc @nodejs/build

**Comment by Trott** [comment]
The machine is [test-digitalocean-ubuntu1804-x64-1](https://ci.nodejs.org/computer/test-digitalocean-ubuntu1804-x64-1). I logged in and removed some stuff from defunct workspaces, but I do think this is going to happen a lot on that machine. (On the other hand, Ubuntu 18 goes out of support in 3 months, so maybe we roll with it?)

**Comment by Trott** [comment]
(The most recent job on the machine passed. I won't close this quite yet, but someone feeling optimistic might do so.)

**Comment by UlisesGascon** [comment]
I think that this was resolved already, so I will close the issue. Please @anonrig re-open it if you need it.
