### ISSUE TITLE
V8 builds are broken with `ModuleNotFoundError: No module named 'requests'`

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3467]
Refs: https://github.com/nodejs/node/pull/49185#issuecomment-1686116048

Beginning 9 August 2023 the V8 CI has failed to fetch dependencies on ppc64le and s390x:
- https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=rhel8-ppc64le,v8test=v8test/
- https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=rhel8-s390x,v8test=v8test/

e.g. https://ci.nodejs.org/job/node-test-commit-v8-linux/nodes=rhel8-s390x,v8test=v8test/5494/console
```console
10:37:16 Traceback (most recent call last):
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gclient.py", line 118, in <module>
10:37:16     import git_cl
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/git_cl.py", line 48, in <module>
10:37:16     import presubmit_support
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/presubmit_support.py", line 50, in <module>
10:37:16     import rdb_wrapper
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/rdb_wrapper.py", line 9, in <module>
10:37:16     import requests
10:37:16 ModuleNotFoundError: No module named 'requests'
10:37:16 Checking out depot_tools.
10:37:16 Traceback (most recent call last):
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/../../tools/v8/fetch_deps.py", line 100, in <module>
10:37:16     FetchDeps(sys.argv[1])
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/../../tools/v8/fetch_deps.py", line 72, in FetchDeps
10:37:16     depot_tools = node_common.EnsureDepotTools(v8_path, True)
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/tools/v8/node_common.py", line 40, in EnsureDepotTools
10:37:16     depot_tools = _Get(v8_path)
10:37:16   File "/home/iojs/build/workspace/node-test-commit-v8-linux/tools/v8/node_common.py", line 35, in _Get
10:37:16     subprocess.check_output(
10:37:16   File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
10:37:16     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
10:37:16   File "/usr/lib64/python3.9/subprocess.py", line 528, in run
10:37:16     raise CalledProcessError(retcode, process.args,
10:37:16 subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/iojs/build/workspace/node-test-commit-v8-linux/deps/v8/_depot_tools/gclient.py', 'metrics', '--opt-out']' returned non-zero exit status 1.
10:37:16 make: *** [Makefile:303: v8] Error 1
```

**Comment by richardlau** [comment]
I started looking at adding `requests` to the machines, but it looks like the builds have started working again without changes? 🤷 
https://ci.nodejs.org/job/node-test-commit-v8-linux/5514/

**Comment by richardlau** [comment]
Going to close this out as the failures are no longer happening. I can only assume an upstream `depot_tools` change introduced the problem and a subsequent one fixed it.
