### ISSUE TITLE
email notifications from jenkins

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#350]
I had configured the aix build/test job to send me emails if the job failed as it only runs once a day.  In the future we may also want to do something similar if we are running the v8 tests once day/week/whatever

In the job the output (https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix61-ppc64/70/console)  was the following which indicates that smtp is not setup.  Is enabling email notifications something that has been discussed/considered before ?

Looking for TAP results report in workspace using pattern: test.tap
Did not find any matching files. Setting build result to FAILURE.
Build step 'Publish TAP Results' marked build as failure
Sending e-mails to: michael_dawson@ca.ibm.com
ERROR: Could not connect to SMTP host: localhost, port: 25
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
    java.net.ConnectException: Connection refused
    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
    at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
    at javax.mail.Service.connect(Service.java:295)
    at javax.mail.Service.connect(Service.java:176)
    at javax.mail.Service.connect(Service.java:125)
    at javax.mail.Transport.send0(Transport.java:194)
    at javax.mail.Transport.send(Transport.java:124)
    at hudson.tasks.MailSender.run(MailSender.java:128)
    at hudson.tasks.Mailer.perform(Mailer.java:145)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
    at hudson.model.Build$BuildExecution.post2(Build.java:185)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
    at hudson.model.Run.execute(Run.java:1763)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
    at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
    at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
    ... 18 more
Notifying upstream projects of job completion
Finished: FAILURE

**Comment by rvagg** [comment]
Any idea where this is coming from? If it's from slave machines then it's probably a no-go, I don't think we're going to want to set up SMTP on each of them, if this is from the Jenkins master then we could consider connecting it in with a mail delivery service to handle it for us.

**Comment by bnoordhuis** [comment]
I'd like getting cc'd on V8 test results, by the way.

**Comment by jbergstroem** [comment]
Perhaps set up aliases at `@iojs.org` until we get control of `@nodejs.org` for posting test results? It'd make it easier to add/remove people. As for outgoing; we could always look at something like mailgun or mailjet which both should work with ssmtp or similar.

**Comment by rvagg** [comment]
I'm more concerned about delivery mechanism, it's not as easy as just setting up an smtp server these days with all of the hoops you have to jump through to make sure you're not automatically labelled as spam.

**Comment by jbergstroem** [comment]
sstmp with spf/dkim through mailgun/mailjet should work?

**Comment by rvagg** [comment]
yeah, if mailgun does smtp then that'd be fine, but again, doing this on the slaves is not so ideal; does anyone know where this email error is coming from? slave or master?

**Comment by jbergstroem** [comment]
@rvagg I don't really know how propagation works either.

**Comment by mhdawson** [comment]
I think it should be a configuration for jenkins.  Looking at the main configuration page https://ci.nodejs.org/configure  there is a section for E-mail Notification which is blank.

**Comment by mhdawson** [comment]
@jbergstroem is there an existing email server I could try pointing jenkins to ?

**Comment by mhdawson** [comment]
Had discussion with @jbergstroem this week we don't necessarily want to configure jenkins directly.  He is going to look at if we can get jenkins to call sendmail instead and is hoping to look at it next week

**Comment by jbergstroem** [comment]
(By sendmail I mean `/usr/bin/sendmail`)

**Comment by mhdawson** [comment]
@jbergstroem any progress on this or something I can help with ?

**Comment by mhdawson** [comment]
Would like to make some progress on this, would really help me not have to go looking for failures every day.

**Comment by rvagg** [comment]
taken briefly to email (ironically) to talk about servers and credentials

**Comment by mhdawson** [comment]
I think I have what I need now to experiment just down to finding the time to do it.

**Comment by Trott** [comment]
Ping! Is this still happening? If not, can we reconfigure the AIX hosts so that this doesn't happen on every test run?:

```
Sending e-mails to: michael_dawson@ca.ibm.com
ERROR: Could not connect to SMTP host: localhost, port: 25
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.ConnectException: Connection refused
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:129)
	at hudson.tasks.Mailer.perform(Mailer.java:170)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	... 18 more
Notifying upstream projects of job completion
```

**Comment by mhdawson** [comment]
As an FYI, finally going to try this out today.

**Comment by mhdawson** [comment]
Ok, configured with server/userid/password provided by Rod, use SSL is enabled, otherwise left as default.

Done through Jenkins->configuration, E-mail Notificaiton section.

I validated by adding a job that just fails and adding a 

I'm getting emails on failure when I add a post-build action to a job:

![email-post-build](https://cloud.githubusercontent.com/assets/9373002/20353630/7dd5f12e-abe9-11e6-9f39-42295864fd03.jpg)

**Comment by mhdawson** [comment]
I'll open a separate issue to gather input on who would like to be added to email notifications

**Comment by annaZeesat** [comment]
i want to enable notifications in jenkins but got error message again and again
