### ISSUE TITLE
`FATAL: script not yet approved for use`

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3552]
Recent [node-test-commit-linux](https://ci.nodejs.org/job/node-test-commit-linux/) and [node-test-commit-linuxone](https://ci.nodejs.org/job/node-test-commit-linuxone/) jobs are failing with:
e.g. https://ci.nodejs.org/job/node-test-commit-linux/54656/console
```console
16:38:07 FATAL: script not yet approved for use
16:38:07 org.jenkinsci.plugins.scriptsecurity.scripts.UnapprovedUsageException: script not yet approved for use
16:38:07 	at org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval.using(ScriptApproval.java:645)
16:38:07 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:373)
16:38:07 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:310)
16:38:07 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript$evaluate.call(Unknown Source)
16:38:07 	at org.jenkinsci.plugins.ScriptRunner.run(ScriptRunner.groovy:71)
16:38:07 	at org.jenkinsci.plugins.ScriptRunner$run.call(Unknown Source)
16:38:07 	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:64)
16:38:07 	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
16:38:07 	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
16:38:07 	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:375)
16:38:07 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
16:38:07 	at hudson.model.Run.execute(Run.java:1900)
16:38:07 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
16:38:07 	at hudson.model.ResourceController.execute(ResourceController.java:101)
16:38:07 	at hudson.model.Executor.run(Executor.java:442)
16:38:07 All downstream projects complete!
```

**Comment by richardlau** [comment]
In https://ci.nodejs.org/manage/ I can see:
![image](https://github.com/nodejs/build/assets/5445507/588a1438-52ab-4dbd-a200-83dba35a75fa)
and the two pending approvals are:
![image](https://github.com/nodejs/build/assets/5445507/69cd78ce-6f54-45c3-897a-5edb978f8ebc)

I believe these are related to CI config changes earlier today which updated the URL for `VersionSelectorScript.groovy` to from `master` to `main`:
```
https://raw.githubusercontent.com/nodejs/build/master/jenkins/scripts/VersionSelectorScript.groovy?
```
to
```
https://raw.githubusercontent.com/nodejs/build/main/jenkins/scripts/VersionSelectorScript.groovy?
```
Refs: https://github.com/nodejs/jenkins-config-test/commit/edcf1527e8a4041c2ae258c73c0876d6483fddb2

I'll approve both scripts.

**Comment by targos** [comment]
I'm sorry, I didn't know scripts needed to be approved.

**Comment by richardlau** [comment]
You do now 🙂. Don't worry about it, it was easily fixed and at least we know the script security plugin still works.
