### ISSUE TITLE
node-test-commit-v8-linux is broken

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/build#3645]
It seems there is some issue with the node-test-commit-v8-linux job:
https://ci.nodejs.org/job/node-test-commit-v8-linux/5835/

```
 error: Cannot delete branch '_jenkins_local_branch' checked out at '/home/iojs/build/workspace/node-test-commit-v8-linux'
```

**Comment by richardlau** [comment]
I've wiped out the workspace.
Retrying: https://ci.nodejs.org/job/node-test-commit-v8-linux/5836/

**Comment by marco-ippolito** [comment]
> I've wiped out the workspace. Retrying: https://ci.nodejs.org/job/node-test-commit-v8-linux/5836/

it seems to still be failing but I'm not sure if its related to infra

**Comment by richardlau** [comment]
> > I've wiped out the workspace. Retrying: https://ci.nodejs.org/job/node-test-commit-v8-linux/5836/
> 
> it seems to still be failing but I'm not sure if its related to infra

https://github.com/nodejs/build/issues/3050 -- we don't have a fix for this. It may go away once we migrate the machines from Nearform (see https://github.com/nodejs/build/issues/3615).

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/5836/nodes=rhel8-ppc64le,v8test=v8test/console failed with

```console
19:00:40 ./node test/pummel/test-hash-seed.js
19:00:41 node:fs:2702
19:00:41       const stats = binding.lstat(baseLong, true, undefined, true /* throwIfNoEntry */);
19:00:41                             ^
19:00:41 
19:00:41 Error: ENOENT: no such file or directory, lstat '/home/iojs/tmp'
19:00:41     at Object.realpathSync (node:fs:2702:29)
19:00:41     at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-v8-linux/test/common/tmpdir.js:25:6)
19:00:41     at Module._compile (node:internal/modules/cjs/loader:1368:14)
19:00:41     at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
19:00:41     at Module.load (node:internal/modules/cjs/loader:1205:32)
19:00:41     at Module._load (node:internal/modules/cjs/loader:1021:12)
19:00:41     at Module.require (node:internal/modules/cjs/loader:1230:19)
19:00:41     at require (node:internal/modules/helpers:179:18)
19:00:41     at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-v8-linux/test/common/index.js:36:16)
19:00:41     at Module._compile (node:internal/modules/cjs/loader:1368:14) {
19:00:41   errno: -2,
19:00:41   code: 'ENOENT',
19:00:41   syscall: 'lstat',
19:00:41   path: '/home/iojs/tmp'
19:00:41 }
```

I looked at [test-osuosl-rhel8-ppc64_le-3](https://ci.nodejs.org/computer/test-osuosl-rhel8-ppc64_le-3) and it is indeed missing `/home/iojs/tmp`. I've recreated the directory.

**Comment by richardlau** [comment]
https://ci.nodejs.org/job/node-test-commit-v8-linux/5838/nodes=benchmark-ubuntu2204-intel-64,v8test=v8test/console didn't encounter https://github.com/nodejs/build/issues/3050 but it has failed with "bad option: --always-opt".

```console
14:29:22 + /usr/bin/python3.10 tools/test.py -j 88 -p tap --mode=release --flaky-tests=run v8-updates
14:29:23 TAP version 13
14:29:23 1..2
14:29:23 ok 1 v8-updates/test-trace-gc-flag
14:29:23   ---
14:29:23   duration_ms: 268.14800
14:29:23   ...
14:29:23 not ok 2 v8-updates/test-linux-perf-logger
14:29:23   ---
14:29:23   duration_ms: 413.91100
14:29:23   severity: fail
14:29:23   exitcode: 1
14:29:23   stack: |-
14:29:23     node:assert:126
14:29:23       throw new AssertionError(obj);
14:29:23       ^
14:29:23     
14:29:23     AssertionError [ERR_ASSERTION]: 2 tests failed
14:29:23     
14:29:23     [ERROR 1] --perf-basic-prof compiled
14:29:23     Errors:
14:29:23     1. running script:
14:29:23     /home/iojs/build/workspace/node-test-commit-v8-linux/out/Release/node: bad option: --always-opt
14:29:23     
14:29:23     Perf map content:
14:29:23     [uninitialized]
14:29:23     </end perf map content>
14:29:23     
14:29:23     --------
14:29:23     [ERROR 2] --perf-basic-prof-only-functions compiled
14:29:23     Errors:
14:29:23     1. running script:
14:29:23     /home/iojs/build/workspace/node-test-commit-v8-linux/out/Release/node: bad option: --always-opt
14:29:23     
14:29:23     Perf map content:
14:29:23     [uninitialized]
14:29:23     </end perf map content>
14:29:23     
14:29:23         at runSuite (/home/iojs/build/workspace/node-test-commit-v8-linux/test/v8-updates/test-linux-perf-logger.js:145:10)
14:29:23         at Object.<anonymous> (/home/iojs/build/workspace/node-test-commit-v8-linux/test/v8-updates/test-linux-perf-logger.js:148:1)
14:29:23         at Module._compile (node:internal/modules/cjs/loader:1368:14)
14:29:23         at Module._extensions..js (node:internal/modules/cjs/loader:1426:10)
14:29:23         at Module.load (node:internal/modules/cjs/loader:1205:32)
14:29:23         at Module._load (node:internal/modules/cjs/loader:1021:12)
14:29:23         at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
14:29:23         at node:internal/main/run_main_module:28:49 {
14:29:23       generatedMessage: false,
14:29:23       code: 'ERR_ASSERTION',
14:29:23       actual: 2,
14:29:23       expected: 0,
14:29:23       operator: 'strictEqual'
14:29:23     }
14:29:23     
14:29:23     Node.js v21.7.0
14:29:23   ...
14:29:23 
14:29:23 Failed tests:
14:29:23 out/Release/node /home/iojs/build/workspace/node-test-commit-v8-linux/test/v8-updates/test-linux-perf-logger.js
```

**Comment by targos** [comment]
^ That's https://github.com/nodejs/node/issues/51308

**Comment by RafaelGSS** [comment]
> ^ That's [nodejs/node#51308](https://github.com/nodejs/node/issues/51308)

That's flaky, right? Since it was encountered in 2023 and we've made some releases after that without issues.

**Comment by targos** [comment]
Maybe it's flaky, but I have never seen it pass myself.

**Comment by richardlau** [comment]
`/home/iojs/build/workspace/node-test-commit-v8-linux/out/Release/node: bad option: --always-opt` means that the node process failed to start. Possibly https://github.com/nodejs/node/commit/515b007faedf529861b22823f8a722eebed837fa should be backported -- it's part of a larger number of commits from a semver-major V8 update, but if the test is using an option that the version of V8 in that version of Node.js doesn't support that test is never going to work.
