### ISSUE TITLE
`FATAL: Command "git clean -ffdx" returned status code 1` on release-rackspace-win2022_vs2022-x64-2

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3757]
[iojs+release](https://ci-release.nodejs.org/job/iojs+release/) is failing on [release-rackspace-win2022_vs2022-x64-2](https://ci-release.nodejs.org/computer/release-rackspace-win2022_vs2022-x64-2) with
e.g. https://ci-release.nodejs.org/job/iojs+release/10264/nodes=vs2022-x86/console
```console
16:21:20 hudson.plugins.git.GitException: Command "git clean -ffdx" returned status code 1:
16:21:20 stdout: 
16:21:20 stderr: warning: failed to remove out/Release/license.rtf: Invalid argument
16:21:20 
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2846)
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2766)
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2761)
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2051)
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2063)
16:21:20 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.clean(CliGitAPIImpl.java:1095)
16:21:20 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:21:20 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
16:21:20 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:21:20 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
16:21:20 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:924)
16:21:20 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:902)
16:21:20 	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:853)
16:21:20 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
16:21:20 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
16:21:20 	at hudson.remoting.Request$2.run(Request.java:377)
16:21:20 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
16:21:20 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
16:21:20 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
16:21:20 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
16:21:20 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:137)
16:21:20 	at java.base/java.lang.Thread.run(Thread.java:840)
```

I've restarted the machine in case it is a stale open file handle.

**Comment by richardlau** [comment]
Two most recent iojs+release runs on the machine passed, so looks like this is fixed.
