### ISSUE TITLE
Machine failure on rhel9-x64

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/build#3763]
I'm trying to release [v20.15.0](https://github.com/nodejs/node/pull/53486), it seems this machine keeps failing: 
https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/58472/
previously also other machines were failing like fedora

```
13:45:50 Cloning repository git@github.com:nodejs/node.git
13:45:50  > git init /home/iojs/build/workspace/node-test-commit-linux # timeout=10
13:45:50 ERROR: Error cloning remote repo 'origin'
13:45:50 hudson.plugins.git.GitException: Could not init /home/iojs/build/workspace/node-test-commit-linux
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1073)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:819)
13:45:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:170)
13:45:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:161)
13:45:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
13:45:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
13:45:50 	at hudson.remoting.Request$2.run(Request.java:377)
13:45:50 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
13:45:50 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
13:45:50 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
13:45:50 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
13:45:50 	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:137)
13:45:50 	at java.base/java.lang.Thread.run(Thread.java:840)
13:45:50 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 5c.96.3ca9.ip4.static.sl-reverse.com/169.60.150.92:37438
13:45:50 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)
13:45:50 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
13:45:50 		at hudson.remoting.Channel.call(Channel.java:1003)
13:45:50 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:153)
13:45:50 		at jdk.internal.reflect.GeneratedMethodAccessor470.invoke(Unknown Source)
13:45:50 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:45:50 		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
13:45:50 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:138)
13:45:50 		at jdk.proxy106/jdk.proxy106.$Proxy199.execute(Unknown Source)
13:45:50 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1222)
13:45:50 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1305)
13:45:50 		at hudson.scm.SCM.checkout(SCM.java:540)
13:45:50 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1248)
13:45:50 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:649)
13:45:50 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
13:45:50 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:521)
13:45:50 		at hudson.model.Run.execute(Run.java:1894)
13:45:50 		at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
13:45:50 		at hudson.model.ResourceController.execute(ResourceController.java:101)
13:45:50 		at hudson.model.Executor.run(Executor.java:442)
13:45:50 Caused by: hudson.plugins.git.GitException: Error performing git command: git init /home/iojs/build/workspace/node-test-commit-linux
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2862)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2766)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2761)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:2051)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1071)
13:45:50 	... 12 more
13:45:50 Caused by: java.io.IOException: Cannot run program "git" (in directory "/home/iojs/build/workspace/node-test-commit-linux"): error=2, No such file or directory
13:45:50 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
13:45:50 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
13:45:50 	at hudson.Proc$LocalProc.<init>(Proc.java:252)
13:45:50 	at hudson.Proc$LocalProc.<init>(Proc.java:221)
13:45:50 	at hudson.Launcher$LocalLauncher.launch(Launcher.java:994)
13:45:50 	at hudson.Launcher$ProcStarter.start(Launcher.java:506)
13:45:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2839)
13:45:50 	... 16 more
13:45:50 Caused by: java.io.IOException: error=2, No such file or directory
13:45:50 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
13:45:50 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
13:45:50 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
13:45:50 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
13:45:50 	... 22 more
13:45:50 ERROR: Error cloning remote repo 'origin'
```

**Comment by richardlau** [comment]
According to `/var/log/dnf.rpm.log` on [test-ibm-rhel9-x64-1](https://ci.nodejs.org/computer/test-ibm-rhel9-x64-1/) the JDK was updated yesterday:

```
2024-06-17T10:31:10-0500 SUBDEBUG Upgrade: java-17-openjdk-headless-1:17.0.11.0.9-2.el9.x86_64
```

this tends to require the agent to be restarted.

**Comment by richardlau** [comment]
Affected machines

- [ ] [test-ibm-rhel9-x64-1](https://ci.nodejs.org/computer/test-ibm-rhel9-x64-1/)
