### ISSUE TITLE
coverity build failed

### ISSUE THREAD

**Issue by richardlau** [nodejs/build#3936]
Today's [node-daily-coverity](https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-coverity/) build failed:

https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-coverity/3176/console
```console
07:57:42 Your build is already in the queue for analysis. Please wait till analysis finishes before uploading another build.
```

**Comment by richardlau** [comment]
According to https://scan.coverity.com/projects/node-js
![image](https://github.com/user-attachments/assets/11b27d31-95ec-4b4f-be0b-2fe3498ca387)

Version v23.0.0-pre-019efe1453 is from https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-coverity/3174/ which succeeded. 

There's no entry for build 3175 in the web UI for Jenkins, but there is a directory/log on the server (in `/var/lib/jenkins/jobs/node-daily-coverity/builds/3175/log`) which seems to indicate that the build was interrupted during the first part of the upload to Coverity:

<details>

```console
+ ./node --version
+ git rev-parse --short HEAD
+ VERSION=v24.0.0-pre-e2242b4e25
+ FILE=nodejs-v24.0.0-pre-e2242b4e25.tar.gz
+ tar -czf nodejs-v24.0.0-pre-e2242b4e25.tar.gz cov-int
+ set +x
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1221    0  1038  100   183   1394    245 --:--:-- --:--:-- --:--:--  1641
{"url":"https://storage.googleapis.com/sig-scan-prod-upload/6507/647974/nodejs-v24.0.0-pre-e2242b4e25.tar.gz?X-Goog-Algorithm=GOOG4-RSA-SHA256\u0026X-Goog-Credential=upload-sa%40sig-scan-prod.iam.gserviceaccount.com%2F20241017%2Fauto%2Fstorage%2Fgoog4_request\u0026X-Goog-Date=20241017T070115Z\u0026X-Goog-Expires=86400\u0026X-Goog-SignedHeaders=host\u0026X-Goog-Signature=aaed1dbe5c590a9b906de2fe7d282b90d07c9355c43c08a19f052f89dfe45d282841d7a7967f269681768f26d261a21c13011fd1a6efc1c0b46b5dd7c11d86ebabca9201ca2e34a9e4f387ce30a7462af9c0ea0cec0c42e2b84318b4da03ca2c90cd7c738fa0c3ec22e1e7bff1050c377dfdd954209a483cb77fbf4df2d6d4abea3123137f65cc84a6accaa2b47d2a6307af4491936381e51d8e3c95e01e847811d432598b25e512fdb0645390b7c37f669d34cac7558ffc042b823e1ea3a76de7370102de0ae0417f134306e27ec5b1ad74207cc08f592d81d3d5eda11a57aa7b0b9db39701c1eabf80cc9491375f8669a32ab89098b9afb4e3075b37cf9cde","expires":"2024-10-18T00:01:15.722-07:00","build_id":647974,"info":"Please ensure that 'cov-build version' matches one of these: 2023.6.2 | 2022.12.2"}  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 24 9616M    0     0   24 2332M      0  35.3M  0:04:32  0:01:05  0:03:27 36.2MFATAL: command execution failed
java.nio.channels.ClosedChannelException
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:241)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
        at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:177)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:279)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:501)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:244)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:196)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:209)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:793)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:343)
        at hudson.remoting.Channel.close(Channel.java:1536)
        at hudson.remoting.Channel.close(Channel.java:1489)
        at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:949)
        at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:915)
        at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:97)
        at jenkins.model.Jenkins.lambda$_cleanUpDisconnectComputers$15(Jenkins.java:3797)
        at hudson.model.Queue._withLock(Queue.java:1409)
        at hudson.model.Queue.withLock(Queue.java:1283)
        at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3793)
        at jenkins.model.Jenkins.cleanUp(Jenkins.java:3674)
        at hudson.WebAppMain.contextDestroyed(WebAppMain.java:398)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:1059)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:636)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.contextDestroyed(ContextHandler.java:1016)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:306)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:412)
        at Jenkins Main ClassLoader//org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:413)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:497)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:1039)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:399)
        at Jenkins Main ClassLoader//org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1311)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1087)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:312)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.doStop(Server.java:517)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//winstone.Launcher.shutdown(Launcher.java:442)
        at Jenkins Main ClassLoader//winstone.ShutdownHook.run(ShutdownHook.java:28)
Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from static.214.104.27.37.clients.your-server.de/37.27.104.214:51608' is disconnected.
        at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:215)
        at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:285)
        at jdk.proxy2/jdk.proxy2.$Proxy199.isAlive(Unknown Source)
        at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1212)
        at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1204)
        at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:195)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:145)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
        at hudson.model.Build$BuildExecution.build(Build.java:199)
        at hudson.model.Build$BuildExecution.doRun(Build.java:164)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
        at hudson.model.Run.execute(Run.java:1894)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
        at hudson.model.ResourceController.execute(ResourceController.java:101)
        at hudson.model.Executor.run(Executor.java:446)
FATAL: Unable to delete script file /tmp/jenkins2956066036718976444.sh
java.nio.channels.ClosedChannelException
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:241)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:221)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:825)
        at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:289)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:177)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:279)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:501)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:244)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:196)
        at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:209)
        at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:793)
        at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:172)
        at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:343)
        at hudson.remoting.Channel.close(Channel.java:1536)
        at hudson.remoting.Channel.close(Channel.java:1489)
        at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:949)
        at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:915)
        at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:97)
        at jenkins.model.Jenkins.lambda$_cleanUpDisconnectComputers$15(Jenkins.java:3797)
        at hudson.model.Queue._withLock(Queue.java:1409)
        at hudson.model.Queue.withLock(Queue.java:1283)
        at jenkins.model.Jenkins._cleanUpDisconnectComputers(Jenkins.java:3793)
        at jenkins.model.Jenkins.cleanUp(Jenkins.java:3674)
        at hudson.WebAppMain.contextDestroyed(WebAppMain.java:398)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.callContextDestroyed(ContextHandler.java:1059)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.callContextDestroyed(ServletContextHandler.java:636)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.contextDestroyed(ContextHandler.java:1016)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletHandler.doStop(ServletHandler.java:306)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.security.SecurityHandler.doStop(SecurityHandler.java:412)
        at Jenkins Main ClassLoader//org.eclipse.jetty.security.ConstraintSecurityHandler.doStop(ConstraintSecurityHandler.java:413)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.session.SessionHandler.doStop(SessionHandler.java:497)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.stopContext(ContextHandler.java:1039)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.stopContext(ServletContextHandler.java:399)
        at Jenkins Main ClassLoader//org.eclipse.jetty.webapp.WebAppContext.stopContext(WebAppContext.java:1311)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.ContextHandler.doStop(ContextHandler.java:1087)
        at Jenkins Main ClassLoader//org.eclipse.jetty.servlet.ServletContextHandler.doStop(ServletContextHandler.java:312)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:182)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:205)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:97)
        at Jenkins Main ClassLoader//org.eclipse.jetty.server.Server.doStop(Server.java:517)
        at Jenkins Main ClassLoader//org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
        at Jenkins Main ClassLoader//winstone.Launcher.shutdown(Launcher.java:442)
        at Jenkins Main ClassLoader//winstone.ShutdownHook.run(ShutdownHook.java:28)
Caused: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@a824064:JNLP4-connect connection from static.214.104.27.37.clients.your-server.de/37.27.104.214:51608": Remote call on JNLP4-connect connection from static.214.104.27.37.clients.your-server.de/37.27.104.214:51608 failed. The channel is closing down or has closed down
        at hudson.remoting.Channel.call(Channel.java:1035)
        at hudson.FilePath.act(FilePath.java:1229)
        at hudson.FilePath.act(FilePath.java:1218)
        at hudson.FilePath.delete(FilePath.java:1765)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:163)
        at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:92)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:818)
        at hudson.model.Build$BuildExecution.build(Build.java:199)
        at hudson.model.Build$BuildExecution.doRun(Build.java:164)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:526)
        at hudson.model.Run.execute(Run.java:1894)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
        at hudson.model.ResourceController.execute(ResourceController.java:101)
        at hudson.model.Executor.run(Executor.java:446)
Build step 'Execute shell' marked build as failure
```
</details>

This is most likely to be an unfortunate piece of timing -- ci.nodejs.org was upgraded yesterday to apply security updates and this is around the time that happened. The interrupted build told Coverity to start a build but never got round to uploading it. I'll "Terminate Build", which should allow the next build to go through the next time the job runs.

**Comment by richardlau** [comment]
Build terminated:

> The build has been scheduled for termination. There may be a delay before a new build can be resubmitted.

I'll close if the next build is successfully submitted.

**Comment by richardlau** [comment]
Three most recent builds since I terminated the stuck one in Coverity have been successful:
![image](https://github.com/user-attachments/assets/d08b4e64-5257-42c5-bc36-0b5fbdcaeb12)
