### ISSUE TITLE
OSX reporting as failed even though sub job ran/was ok

### ISSUE THREAD

**Issue by mhdawson** [nodejs/build#617]
Noticed this when looking through results for recent run:

https://ci.nodejs.org/job/node-test-commit-osx/7668/console

```bash
Run condition [Always] enabling perform for step [Builder to mark whether executed]
Triggering node-test-commit-osx » osx1010
FATAL: null
java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at hudson.model.ParametersAction.shouldSchedule(ParametersAction.java:218)
	at hudson.model.Queue.scheduleInternal(Queue.java:590)
	at hudson.model.Queue.schedule2(Queue.java:560)
	at hudson.matrix.MatrixConfiguration.scheduleBuild(MatrixConfiguration.java:493)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.scheduleConfigurationBuild(DefaultMatrixExecutionStrategyImpl.java:245)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.run(DefaultMatrixExecutionStrategyImpl.java:157)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:364)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
[PostBuildScript] - Execution post build scripts.
[PostBuildScript] Build is not success : do not execute script
[PostBuildScript] - Execution post build scripts.
[workspace] $ /bin/sh -xe /tmp/hudson252866088209225725.sh
```

**Comment by mhdawson** [comment]
Its been that way as far back as history goes, Feb 4

**Comment by mhdawson** [comment]
Looks like it is ok now closing.
