### ISSUE TITLE
node-test-commit-osx consistently failing with NullPointerException

### ISSUE THREAD

**Issue by aqrln** [nodejs/build#681]
```
...
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Run condition [Always] enabling perform for step [Builder to mark whether executed]
Triggering node-test-commit-osx » osx1010
FATAL: null
java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:118)
	at hudson.model.ParametersAction.shouldSchedule(ParametersAction.java:228)
	at hudson.model.Queue.scheduleInternal(Queue.java:615)
	at hudson.model.Queue.schedule2(Queue.java:585)
	at hudson.matrix.MatrixConfiguration.scheduleBuild(MatrixConfiguration.java:512)
...
```

https://ci.nodejs.org/job/node-test-commit-osx/8928/console
https://ci.nodejs.org/job/node-test-commit-osx/8929/console
https://ci.nodejs.org/job/node-test-commit-osx/8930/console

**Comment by jbergstroem** [comment]
ping @rvagg

**Comment by Trott** [comment]
Looks like this has been resolved. Would be great to get a comment describing the fix if someone knows what fixed it. In any event, closing...
