### ISSUE TITLE
build fail paradox

### ISSUE THREAD

**Issue by refack** [nodejs/build#783]
If a build fails early enough Jenkins will use the previous run's remaining `.tap` files, so you get a paradoxical status report:

---

```
...
> git checkout -f e7904648532bc3660cc2c093f34cb6be9bf61223
FATAL: Could not checkout e7904648532bc3660cc2c093f34cb6be9bf61223
hudson.plugins.git.GitException: Command "git checkout -f e7904648532bc3660cc2c093f34cb6be9bf61223" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: e7904648532bc3660cc2c093f34cb6be9bf61223
...
Run condition [Always] enabling perform for step [[Execute a set of scripts]]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: *.tap
Saving reports...
...
```
<details>
<summary>full console output</summary>

```
Started by upstream project "node-test-commit-linux" build number 11013
originally caused by:
 Started by upstream project "node-test-commit" build number 10980
 originally caused by:
  Started by upstream project "node-test-pull-request" build number 9006
  originally caused by:
   Started by user Trevor Norris
[EnvInject] - Loading node environment variables.
Building remotely on test-softlayer-debian8-x86-1 (debian8-x86) in workspace /home/iojs/build/workspace/node-test-commit-linux/nodes/debian8-x86
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
Fetching upstream changes from https://github.com/nodejs/node.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* +refs/pull/13991/head:refs/remotes/origin/_jenkins_local_branch # timeout=20
Checking out Revision e7904648532bc3660cc2c093f34cb6be9bf61223 (refs/remotes/origin/_jenkins_local_branch)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f e7904648532bc3660cc2c093f34cb6be9bf61223
FATAL: Could not checkout e7904648532bc3660cc2c093f34cb6be9bf61223
hudson.plugins.git.GitException: Command "git checkout -f e7904648532bc3660cc2c093f34cb6be9bf61223" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: e7904648532bc3660cc2c093f34cb6be9bf61223

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1903)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2188)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:62)
	at java.lang.Thread.run(Thread.java:745)
Caused: hudson.plugins.git.GitException: Could not checkout e7904648532bc3660cc2c093f34cb6be9bf61223
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2211)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:62)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to Channel to /169.44.16.126(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
	at sun.reflect.GeneratedMethodAccessor343.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
	at com.sun.proxy.$Proxy83.execute(Unknown Source)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1155)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Run condition [Always] enabling perform for step [[Execute a set of scripts]]
Run condition [Always] enabling perform for step [[Execute a set of scripts]]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: *.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/debian8-x86/builds/11013/tap-master-files/cctest.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/debian8-x86/builds/11013/tap-master-files/cctest.tap].
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/debian8-x86/builds/11013/tap-master-files/test.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/debian8-x86/builds/11013/tap-master-files/test.tap].
TAP Reports Processing: FINISH
Checking ^not ok
Notifying upstream projects of job completion
Finished: FAILURE
```

</details>

---

![image](https://user-images.githubusercontent.com/96947/27911864-ad395b5e-6228-11e7-8a33-add3319e2694.png)

---

https://ci.nodejs.org/job/node-test-commit-linux/11013/nodes=debian8-x86/console

**Comment by joaocgreis** [comment]
The Jenkins Git plugin clears the workspace only after checkout. I remember that was the only choice we had, but now I see before and after checkout options, probably added in some Jenkins update.

Cleaning both before and after should do no harm, we should experiment first and add it to every job.

**Comment by gibfahn** [comment]
We could just clean before, is there a reason to clean after checkout?

**Comment by targos** [comment]
Sometimes a checkout can leave untracked files behind (not sure exactly what are the conditions)

**Comment by refack** [comment]
Just for argument's sake why clean? wholesale cleaning that is. Won't the old artifacts speed up building?
Maybe only clean for releases? Maybe do custom cleaning?

> Sometimes a checkout can leave untracked files behind (not sure exactly what are the conditions)

AFAIK if a newly added file does exist in the checkout target branch, git will not delete it, just untrack it.

**Comment by targos** [comment]
> Won't the old artifacts speed up building?

We have ccache for that

**Comment by gibfahn** [comment]
>Sometimes a checkout can leave untracked files behind (not sure exactly what are the conditions)

I guess if something was not in `.gitignore` before checkout, but is in `.gitignore` after, then it wouldn't be deleted, so fair enough.

**Comment by Trott** [comment]
Closing due to long period of inactivity. Feel free to re-open if this is a thing. I'm just trying to close stuff that has been ignored for sufficiently long that it seems likely it's not something we're going to get to.
