### ISSUE TITLE
ci-release is borked

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#818]
No bueno

```
Started by user Myles Borins
[EnvInject] - Loading node environment variables.
Building on master in workspace /var/lib/jenkins/ws
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
Fetching upstream changes from https://github.com/nodejs/node.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --progress https://github.com/nodejs/node.git +refs/heads/*:refs/remotes/origin/* # timeout=30
 > git rev-parse f15e12453a^{commit} # timeout=10
JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
Checking out Revision f15e12453ad16a7d914880765e7b6cc5188fa959 (detached)
Commit message: "2017-08-01, Version 6.11.2 'Boron' (LTS)"
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f15e12453ad16a7d914880765e7b6cc5188fa959
 > git rev-list f15e12453ad16a7d914880765e7b6cc5188fa959 # timeout=10
Cleaning workspace
 > git rev-parse --verify HEAD # timeout=10
Resetting working tree
 > git reset --hard # timeout=10
 > git clean -fdx # timeout=10
Triggering iojs+release » smartos13-release
Triggering iojs+release » ppcbe-ubuntu1404-release-64
Triggering iojs+release » ppcle-ubuntu1404-release-64
Triggering iojs+release » vs2013-x86
Triggering iojs+release » armv7-wheezy-release
Triggering iojs+release » centos5-release-32
Triggering iojs+release » pi1-raspbian-wheezy
Cancelled iojs+release » armv7-wheezy-release
Cancelled iojs+release » centos5-release-32
Cancelled iojs+release » ppcbe-ubuntu1404-release-64
Cancelled iojs+release » ppcle-ubuntu1404-release-64
Cancelled iojs+release » smartos13-release
Cancelled iojs+release » vs2013-x86
FATAL: null
java.lang.NullPointerException
	at java.util.HashSet.<init>(HashSet.java:116)
	at hudson.model.ParametersAction.shouldSchedule(ParametersAction.java:228)
	at hudson.model.Queue.scheduleInternal(Queue.java:615)
	at hudson.model.Queue.schedule2(Queue.java:585)
	at hudson.matrix.MatrixConfiguration.scheduleBuild(MatrixConfiguration.java:512)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.scheduleConfigurationBuild(DefaultMatrixExecutionStrategyImpl.java:247)
	at hudson.matrix.DefaultMatrixExecutionStrategyImpl.run(DefaultMatrixExecutionStrategyImpl.java:159)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:364)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by rvagg** [comment]
on it

**Comment by rvagg** [comment]
_Both_ Pi1's we use for building seem to be completely borked, probably needing a rebuild, hopefully not an SD card replacement. I'm going to try and get them back online today but to let you get on with building I've just removed armv6 as a target completely while I sort this out. It'll just mean you won't get the `-armv6l.*` files and we'll have to run the job again after it's fixed. Don't let that stop a release or RC build though @MylesBorins.

**Comment by MylesBorins** [comment]
kicked off build for 6.11.2

Executors do not seem to be starting up... thoughts?

**Comment by rvagg** [comment]
As per IRC: I killed everything off and restarted Jenkins and I see you've successfully kicked off your build again.

The Pi1's turned out to be not as borked as I feared and it wasn't to much drama to get them back up and running. They are both connected again and are back in the iojs+release job and one is building your current job, so no need to redo later: https://ci-release.nodejs.org/job/iojs+release/1900/nodes=pi1-raspbian-wheezy/console
