### ISSUE TITLE
Constant git failures for test-mininodes-ubuntu1604-arm64_odroid_c2-2

### ISSUE THREAD

**Issue by Trott** [nodejs/build#832]
test-mininodes-ubuntu1604-arm64_odroid_c2-2 was failing to build consistently. -1 and -3 are not exhibiting problems, so I took -2 offline temporarily. Here's the output of a typical failed run:

```console
Started by upstream project "node-test-commit-arm" build number 11475
originally caused by:
 Started by upstream project "node-test-commit" build number 11737
 originally caused by:
  Started by upstream project "node-daily-master" build number 824
  originally caused by:
   Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on test-mininodes-ubuntu1604-arm64_odroid_c2-2 (ubuntu1604-arm64_odroid_c2) in workspace /home/iojs/build/workspace/node-test-commit-arm/nodes/ubuntu1604-arm64_odroid_c2
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/nodejs/node.git # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/nodejs/node.git
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:817)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1084)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1115)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: hudson.plugins.git.GitException: Command "git config remote.origin.url https://github.com/nodejs/node.git" returned status code 255:
stdout: 
stderr: error: could not lock config file .git/config: Read-only file system

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1892)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1888)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1533)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1545)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.setRemoteUrl(CliGitAPIImpl.java:1179)
	at hudson.plugins.git.GitAPI.setRemoteUrl(GitAPI.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:887)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:862)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:821)
	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at hudson.remoting.Engine$1$1.run(Engine.java:90)
	at java.lang.Thread.run(Thread.java:748)
	at ......remote call to Channel to /70.167.220.148(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:257)
	at com.sun.proxy.$Proxy84.setRemoteUrl(Unknown Source)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl.setRemoteUrl(RemoteGitImpl.java:295)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:805)
	... 11 more
ERROR: Error fetching remote repo 'origin'
Run condition [Always] enabling perform for step [[]]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: *.tap
Did not find any matching files. Setting build result to FAILURE.
Checking ^not ok
Jenkins Text Finder: File set '*.tap' is empty
Notifying upstream projects of job completion
Finished: FAILURE
```

That's https://ci.nodejs.org/job/node-test-commit-arm/11475/nodes=ubuntu1604-arm64_odroid_c2/console but there's a bunch of others that are identical and the hosts build history is all red right now.

(Is mininodes an @rvagg thing? Or should someone else get pinged?)

**Comment by rvagg** [comment]
The C2's are hosted at https://www.mininodes.com/, we email David Tischler to deal with them on the hardware front when required.

This machine locked up last week when I was doing an OS update and needed a forced restart by David. I guess the filesystem got corrupted in the process. I've done an e2fsck on it and restarted and it's back up again with a read/write filesystem. Let me know if you notice this again because it could indicate a corrupt disk (I think these guys are eMMC rather than MicroSD so they _should_ be closer in reliability to SSDs).

**Comment by rvagg** [comment]
_(nodejs_build_test folks should have access to that machine to do what I just did fwiw, this doesn't require any special privs)_
