### ISSUE TITLE
Please add tempdir to Ubuntu 1604

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/build#833]
Consistently seeing failures with Readable stream in CITGM
```
 Error: ENOENT: no such file or directory, lstat '/home/iojs/tmp'
               at Error (native)
               at Object.fs.lstatSync (fs.js:994:11)
               at Object.realpathSync (fs.js:1676:21)
               at Object.<anonymous> (/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/citgm_tmp/fbb8bac7-e783-424b-96cf-4a288b300a2e/readable-stream/test/common.js:69:47)
               at Module._compile (module.js:570:32)
               at Object.Module._extensions..js (module.js:579:10)
               at Module.load (module.js:487:32)
               at tryModuleLoad (module.js:446:12)
               at Function.Module._load (module.js:438:3)
               at Module.require (module.js:497:17)
         command: "/home/iojs/build/workspace/citgm-smoker/nodes/ubuntu1604-64/smoker/bin/node test-stream-big-packet.js"
```

**Comment by gibfahn** [comment]
Isn't this what https://github.com/nodejs/build/pull/785 (and previously https://github.com/nodejs/build/pull/658) aim to do?

**Comment by rvagg** [comment]
oh, you know ... on occasion I've deleted that directory in general cleanup of machines that need cleaning up, this could very well be my fault on particular machines, will try and remember not to be overzealous with cleaning in future
