### ISSUE TITLE
non-stop CI build failures on centos5-32

### ISSUE THREAD

**Issue by Trott** [nodejs/build#853]
8 builds in a row have all failed.

Example: https://ci.nodejs.org/job/node-test-commit-linux/12069/nodes=centos5-32/console

```console
Started by upstream project "node-test-commit-linux" build number 12069
originally caused by:
 Started by upstream project "node-test-commit-node-v8" build number 123
 originally caused by:
  Started by upstream project "node-update-v8-canary" build number 154
  originally caused by:
   Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on test-digitalocean-centos5-x86-1 (centos5-32-gcc41 centos5-32) in workspace /home/iojs/build/workspace/node-test-commit-linux/nodes/centos5-32
java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy10
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.reflect.Proxy.newInstance(Proxy.java:764)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:755)
	at hudson.remoting.RemoteInvocationHandler.wrap(RemoteInvocationHandler.java:143)
	at hudson.remoting.Channel.export(Channel.java:621)
	at hudson.remoting.Channel.export(Channel.java:590)
	at org.jenkinsci.plugins.gitclient.LegacyCompatibleGitAPIImpl.writeReplace(LegacyCompatibleGitAPIImpl.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeWriteReplace(ObjectStreamClass.java:1118)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1134)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
	at hudson.remoting.UserRequest._serialize(UserRequest.java:157)
	at hudson.remoting.UserRequest.serialize(UserRequest.java:166)
	at hudson.remoting.UserRequest.perform(UserRequest.java:128)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at hudson.remoting.Engine$1$1.run(Engine.java:62)
	at java.lang.Thread.run(Thread.java:745)
	at ......remote call to Channel to /192.241.250.186(Native Method)
	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1545)
	at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
	at hudson.remoting.Channel.call(Channel.java:830)
Caused: java.io.IOException: Remote call on Channel to /192.241.250.186 failed
	at hudson.remoting.Channel.call(Channel.java:838)
	at hudson.FilePath.act(FilePath.java:985)
Caused: java.io.IOException: remote file operation failed: /home/iojs/build/workspace/node-test-commit-linux/nodes/centos5-32 at hudson.remoting.Channel@65e5dd78:Channel to /192.241.250.186
	at hudson.FilePath.act(FilePath.java:992)
	at hudson.FilePath.act(FilePath.java:974)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:137)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:756)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:747)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1109)
	at hudson.scm.SCM.checkout(SCM.java:496)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1281)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:604)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:529)
	at hudson.model.Run.execute(Run.java:1728)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Run condition [Always] enabling perform for step [[]]
Run condition [Always] enabling perform for step [[]]
TAP Reports Processing: START
Looking for TAP results report in workspace using pattern: *.tap
Saving reports...
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/centos5-32/builds/12069/tap-master-files/cctest.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/centos5-32/builds/12069/tap-master-files/cctest.tap].
Processing '/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/centos5-32/builds/12069/tap-master-files/test.tap'
Parsing TAP test result [/var/lib/jenkins/jobs/node-test-commit-linux/configurations/axis-nodes/centos5-32/builds/12069/tap-master-files/test.tap].
TAP Reports Processing: FINISH
Checking ^not ok
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by Trott** [comment]
Logged into the host and did `cd /etc/init.d/jenkins restart`. That seems to have fixed it. Didn't investigate *why* it had the problem in the first place.  So, uh, feel free! But I'm going to close. Thanks!
